### ISSUE TITLE
PDF labels always printing A4 when A6 is set

### ISSUE THREAD

**Issue by GitTworn** [myparcelnl/woocommerce#1009]
### Plugin version

4.21.0

### WooCommerce version

6.3.1

### WordPress version

8.0.3

### PHP version

7.4

### What went wrong?

Note: In the version before this everything worked as expected.

When in the admin section of the MyParcel plugin, select A6 as paper size.
When generating the PDF labels, an A4 page with 4 labels on a page is generated in stead of 1 label per A6 page.

### Reproduction steps

1. In the admin panel > WooCommerce
2. Order
3. Select any number of orders
4. From the dropdown, select MyParcel: Print, and click the Apply
5. A new tab will appear with the labels.

### Relevant log output

```shell
N/A
```

### Additional context

This worked with the previous version of WooCommerce and WordPress.

**Comment by EdieLemoine** [comment]
Hi @GitTworn, this should not occur anymore in the [v5.0.0 beta](https://github.com/myparcelnl/woocommerce/releases) versions of the plugin.

Please read [this issue](https://github.com/myparcelnl/woocommerce/issues/1057) for more information and how to report bugs in the new version.
