### ISSUE TITLE
Selectie rondjes bij afhalen PostNL locatie op checkout page verspringen

### ISSUE THREAD

**Issue by guicher** [myparcelnl/woocommerce#101]
Als er bij de checkout wordt gekozen voor afhalen bij PostNL locatie en je scrolt naar beneden in de lijst met afhaalpunten dan verspringen/verschuiven de selectierondjes. Hierdoor is het mogelijk dat je de verkeerd locatie selecteerd, omdat het rondje wat je selecteerd bij een andere locatie hoort. Hoe kan ik dit oplossen?

<img width="763" alt="myparcel-afhaal-locatie" src="https://user-images.githubusercontent.com/40121811/41193220-87f63448-6c09-11e8-8ca6-94a907f44235.png">

**Comment by RichardPerdaan** [comment]
Beste @guicher,

Dank je wel voor het sturen van jouw bericht.
In het bestand:
* woocommerce/wp-content/plugins/woocommerce-myparcel/includes/views/wcmp-delivery-options-template.php 

Zou je het volgende kunnen aanpassen: op regel 170 `padding: 9px 15px 16px 15px;` veranderen naar `padding: 5px 15px 16px 15px;`


Eventueel is het ook mogelijk om bij de instellingen van MyParcel -> Custom styles het volgende te plaatsen` .mypa-row-title{
      display: inline-block;
      padding: 5px 15px 16px 15px;
      width: 80%
    }`
