### ISSUE TITLE
Bug report for v5.0.0 BETA - WooCommerce

### ISSUE THREAD

**Issue by lpro-1** [myparcelnl/woocommerce#1039]
### Version check

- [X] My version of the plugin is v5.0.0-alpha.0 or above.

### WordPress version

6.3.2

### PHP version

8.0.28

### What went wrong?

Hi Team,

The following issues have been found:

Plugin WooCommerce 8.2.0 and MyParcel BETA 5.0.0
Ticket nr MyParcel: #01673686

1. When changing the address credentials in an order, these changes are not visible on the shipping label. The export function is not taking these changes into account. This also applies if you change the order from a standard delivery to a delivery that is insured.
2. Trigger and send a return label to the email address of the customer is not available. This option was available in previous versions
3.  Transport status updates/milestones are not updated within WooCommerce for example for PostNL

### Reproduction steps

Hi Team,

The following issues have been found:

Plugin WooCommerce 8.2.0 and MyParcel BETA 5.0.0
Ticket nr MyParcel: #01673686

1. When changing the address credentials in an order, these changes are not visible on the shipping label. The export function is not taking these changes into account. This also applies if you change the order from a standard delivery to a delivery that is insured.
2. Trigger and send a return label to the email address of the customer is not available. This option was available in previous versions
3.  Transport status updates/milestones are not updated within WooCommerce for example for PostNL

**Comment by RichardPerdaan** [comment]
Hi @lpro-1 ,

Thank you for jour feedback.

1. I tried to reproduce the problem with 5.0.0-beta.2 and I don't see the problem there. I opened and adjusted an order and the adjustment was reflected on the shipping label
2. When a shipment has been created, a button will be visible. The return email will be sent to your customer:
![image](https://github.com/myparcelnl/woocommerce/assets/11389731/3ee2f7d5-49cc-46ee-bfdc-3f0524569a67)
3. We are aware of this and we are working on a solution. We are expected to have the fix this week.
