### ISSUE TITLE
[BETA]: Multiple issues/bugs 

### ISSUE THREAD

**Issue by christiantraets** [myparcelnl/woocommerce#1050]
### Version check

- [X] My version of the plugin is v5.0.0-beta.0 or above.

### WordPress version

6.3.2

### PHP version

8.1

### What went wrong?

[Voor het gemak heb ik dit even in het Nederlands uitgetypt]

Afgelopen weekend heb ik de versie van de plugin binnen mijn webshop terug naar de 4.x versie gezet omdat de plugin binnen mijn webshop nog niet lekker loopt en voor extra werk zorgt. Afgelopen week heb ik al twee issues binnen GitHub gemeld maar er vielen mij nog een aantal punten op:

-  Bezorgopties (vervoerders niveau)
Ondanks dat de bezorgopties op vervoerdersniveau niet ingeschakeld stond, werd avondbezorging (binnen 4.x ooit eens geactiveerd gehad) alsnog getoond in de checkout. 

- Afhaalpunt
Binnen de checkout kan een klant een afhaalpunt selecteren. Ondanks de selectie wordt het afhaalpunt niet meegenomen in de bestelling en niet zichtbaar in de backend. Ook na het exporteren wordt het afhaalpunt niet geëxporteerd. 

- Dubbele verzending-orderregels
Zowel in de checkout als de backend wordt in 5.x een extra orderregel toegevoegd met verzending of afhalen (met 0 euro). Dit gebeurt naast de bestaande verzendregel die is toegevoegd in de 'Verzendmethodes' binnen de backend.

### Reproduction steps

1. Navigate to ...
2. Click on ...
3. See ...

**Comment by EdieLemoine** [comment]
Hi @christiantraets,

Bedankt voor het melden, we gaan ermee aan de slag!

Over je tweede punt, de afhaallocatie wordt wel geëxporteerd, mits je niet handmatig de order settings opnieuw opslaat.

**Comment by christiantraets** [comment]
Hi @EdieLemoine,

Dankjewel voor je reactie!

Heb je het dan over de order settings binnen een bestelling? Zo ja: ik heb een order geëxporteerd zonder aan deze settings te komen en daarmee kwam de bestelling als 'standaard bezorging' in Myparcel te staan.
