### ISSUE TITLE
Plugin cannot handle address line 2

### ISSUE THREAD

**Issue by Vincent-appinco** [myparcelnl/woocommerce#1054]
### Plugin version

4.21.0

### WooCommerce version

8.2.2

### WordPress version

latest

### PHP version

7.4

### What went wrong?

The plugin cannot handle address line 2 in orders. When address line 2 has been filled in, exporting an order results in an error: "Invalid full street supplied:".

### Reproduction steps

1. Create an order with address line 2 filled
2. In the orders overview, export the order to myparcel
3. Observe error in log

**Comment by EdieLemoine** [comment]
Hi @Vincent-appinco, this should not occur anymore in the [v5.0.0 beta](https://github.com/myparcelnl/woocommerce/releases) versions of the plugin.

Please read [this issue](https://github.com/myparcelnl/woocommerce/issues/1057) for more information and how to report bugs in the new version.
