### ISSUE TITLE
Barcode in refund mail

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#107]
When a client sends a refund mail to the customer, the barcode is included in this mail (see below). This is not necessary.

![image](https://user-images.githubusercontent.com/22811561/42604176-b6d8c07e-8571-11e8-8789-725c95eeab73.png)

**Comment by TimBlom** [comment]
Case 00374012

**Comment by adem-demir** [comment]
Can't reproduce client doesn't answer questions
