### ISSUE TITLE
Feature:  Option Send to a different address turn off when a PostNL location delivery selected

### ISSUE THREAD

**Issue by RichardPerdaan** [myparcelnl/woocommerce#108]
If you choose '' Pick up at a PostNL location '' the Woocommerce option '' Send to a different address '' will remain. This should actually disappear, since you already choose a delivery address ...

**Comment by RichardPerdaan** [comment]
Case: 00368729

**Comment by EdieLemoine** [comment]
Fixed in v3.0.5
