### ISSUE TITLE
Make template that lives inside views an actual template

### ISSUE THREAD

**Issue by Coders91** [myparcelnl/woocommerce#1080]
### What problem does this feature solve?

It would be nice to use the delivery-options-template.php as an actual template that can be overwritten by placing it inside the theme directory. This is common practice for plugins and will give a little bit more freedom by adding classes to the wrapper element for example. 

### What should the solution look like?

The template used in views can be overwritten by placing the file inside the theme directory.

**Comment by EdieLemoine** [comment]
Hi @Coders91, we're not using this file anymore in the [new version of the plugin](https://myparcelnl.github.io/github-release-linker?repo=myparcelnl/woocommerce) and won't be adding features to the old one anymore.

In [this file](https://github.com/myparcelnl/woocommerce/blob/d4ae5b382ab0aa15083b96303abf536e4f7abf5d/src/Pdk/Service/WcFrontendRenderService.php#L23-L42) we render the delivery options div. There are hooks before and after it's rendered, does that suffice for being able to manipulate the wrapper element the way you need? (Note this only applies to the legacy checkout, not the Blocks checkout.)

Closing this issue, please create a new issue for the beta version of the plugin if you run into any issues with the new implementation.
