### ISSUE TITLE
PostNL Small parcel (Klein pakket) not supported

### ISSUE THREAD

**Issue by Maarten112** [myparcelnl/woocommerce#1095]
### Plugin version

4.22.1

### WooCommerce version

8.8.2

### WordPress version

6.5.2

### PHP version

8.1

### What went wrong?

PostNL small parcel (klein pakket) is not supported in the plugin, while it is available in the MyParcel backend. Manually changing the shipping option in the MyParcel backend to Small Parcel and thereafter printing the label from WooCommerce results in an error. 

### Reproduction steps

1. Export an order to MyParcel with default settings
2. Change the order to Klein Pakket in the myParcel backend
3. Print the label from woocommerce

**Comment by EdieLemoine** [comment]
Fixed in [v4.24.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.24.0)
