### ISSUE TITLE
Compatibility MyParcelBE plugin (branched from this repo) with latest WooCommerce version (8.8)

### ISSUE THREAD

**Issue by Yestix** [myparcelnl/woocommerce#1100]
### Plugin/theme name

WooCommerce

### Pricing

Free

### What problem does this feature solve?

The interface does not work. It is for example not possible to export from the order page nor from the overview. In short, there is no way to export available.

### What should the solution look like?

Make it possible for MyParcelBE customers to use the BE plugin (and thus the integration) with the latest version of WooCommerce.

### Additional context

Please update the plugin as it is necessary to update WooCommerce for e.g. security reasons.

**Comment by EdieLemoine** [comment]
Hi @Yestix, we've rebuilt the entire plugin, which is currently in the beta phase. We won't be updating the existing BE plugin anymore. That repository will be archived and redirect to this one as we're building both plugins from the same source code now. This also means there will be no disparity in features and bug fixes between the MyParcelNL and MyParcelBE versions anymore :)

Maybe you're willing to [try the new version](https://github.com/myparcelnl/woocommerce/releases), it'll help us fix issues and release it as stable sooner.
