### ISSUE TITLE
[BETA]: Default country of origin shouldn't be Afghanistan

### ISSUE THREAD

**Issue by Vincent-appinco** [myparcelnl/woocommerce#1117]
### Version check

- [X] My version of the plugin is v5.0.0-beta.0 or above.

### WordPress version

latest

### PHP version

8.1

### What went wrong?

In MyParcel settings > Douane > Country of origin, considering MyParcel NL is a Dutch service I wouldn't expect the default to be Afghanistan.

### Reproduction steps

.

**Comment by EdieLemoine** [comment]
Fixed in PDK [v2.22.0](https://github.com/myparcelnl/pdk/releases/tag/v2.22.0)
