### ISSUE TITLE
[BETA]: Double PostNL settings tab entries

### ISSUE THREAD

**Issue by Vincent-appinco** [myparcelnl/woocommerce#1119]
### Version check

- [X] My version of the plugin is v5.0.0-beta.0 or above.

### WordPress version

latest

### PHP version

8.1

### What went wrong?

There's 2 PostNL settings tabs.

![image](https://github.com/myparcelnl/woocommerce/assets/125973996/e7d3a232-41a5-4afb-935d-b305fd30148e)

### Reproduction steps

.

**Comment by EdieLemoine** [comment]
This has been fixed a while ago in the PDK

https://github.com/myparcelnl/pdk/releases/tag/v2.42.1
https://github.com/myparcelnl/pdk/releases/tag/v2.39.3
