### ISSUE TITLE
PHP notices/warnings after update to 3.0

### ISSUE THREAD

**Issue by Spreeuw** [myparcelnl/woocommerce#122]
> **Notice:** Undefined index: checkout_position in /wp-content/plugins/woocommerce-myparcel/includes/class-wcmp-frontend.php on line 51

**Comment by Spreeuw** [comment]
To set default settings you can add them the upgrade method (using the 3.0.2 version to do this for people that have already updated but not saved settings too):
https://github.com/myparcelnl/woocommerce/blob/v3.0.0/woocommerce-myparcel.php#L277

**Comment by RichardPerdaan** [comment]
31c403a1142ea077fec5c5751cfc15eaa2d357bc  A possible solution

**Comment by Spreeuw** [comment]
You'll probably want to cast `$taxRate` to float as well before performing arithmics (plus this does not address the default settings notification that is actually a separate issue)

**Comment by RichardPerdaan** [comment]
Hi @Spreeuw,

Thank you for addition.
I have added the adjustment b2aaa7b84c730bb322aabde055fe5a6bf398fa0c 

Today there will be another update with this addition.

**Comment by RichardPerdaan** [comment]
This problem is solved in [v3.0.2](https://github.com/myparcelnl/woocommerce/releases/tag/v3.0.2) of the MyParcel plugin.
