### ISSUE TITLE
PG delivery locations details checkout V2

### ISSUE THREAD

**Issue by adem-demir** [myparcelnl/woocommerce#124]
Feedback: Change the hover on the clock in the PG details.

case: 00436337

**Comment by RichardPerdaan** [comment]
Dit probleem is opgelost in de volgende versie (v 3.0.3), de code is hier terug te vinden: ab8bb7f06d9c6b3b91f840fa7b37a82d601a05fd

**Comment by RichardPerdaan** [comment]
Versie 3.0.3 is live gezet en daarbij is dit probleem opgelost
