### ISSUE TITLE
Support of channel engine checkout V2

### ISSUE THREAD

**Issue by adem-demir** [myparcelnl/woocommerce#127]
checkout V2 doesn't support channel engine

case:00437138

**Comment by RichardPerdaan** [comment]
The code in the previous version can be found in the following branch [support-channelEngine](https://github.com/myparcelnl/woocommerce/commit/c7dc54b8e0427cf1c82d83d1874c0b37060b94a5)

**Comment by EdieLemoine** [comment]
Fixed in v3.0.5
