### ISSUE TITLE
Address details and Mollie Payments

### ISSUE THREAD

**Issue by davdebcom** [myparcelnl/woocommerce#137]
Recently we launched a new version for the Mollie Payments plugin (40k sites) that now sends the address details to Mollie for Klarna payments.

We noticed that the WooCommerce address fields aren't always populated, and that sites with this issue use this MyParcel plugin. I also found this post:
https://wordpress.org/support/topic/works-but-adds-custom-checkout-fields/

> these custom fields are only added for The Netherlands and the Address 1 and Address 2 fields are disabled

This seems to confirm that this plugin doesn't use the default WooCommerce address fields, is that correct? And don't you populate the default fields after the processing that your plugin does during checkout?

Hope we can find a solution together, so our plugins can keep working together on the same sites. 
 
Might be related: 
#33

**Comment by davdebcom** [comment]
Here:
https://github.com/myparcelnl/woocommerce/blob/ef63d1ee3097d6acd65b596ef8acb61443d6f45b/includes/class-wcmp-nlpostcode-fields.php#L569

Don't you want:
```		if ( ($_POST['shipping_country'] == 'NL' || $_POST['shipping_country'] == 'BE') && $ship_to_different_address == true ) {```

**Comment by RichardPerdaan** [comment]
#139 The changes are inside a pull request

**Comment by davdebcom** [comment]
Great. Holding off my update a few days in anticipation of your update. My update will make it impossible for payments without shipping street address to go threw, so better to release it after your update.

**Comment by RichardPerdaan** [comment]
The solution has been processed in version [3.0.4](https://github.com/myparcelnl/woocommerce/releases/tag/v3.0.4)  of the MyParcel plugin.
