### ISSUE TITLE
"Undefined index" Php notices on checkout page

### ISSUE THREAD

**Issue by EdieLemoine** [myparcelnl/woocommerce#143]
### Problem
On the checkout screen this notice appears (6 times):
```
Notice: Undefined index: in /Users/edie/myparcel/woocommerce/includes/class-wcmp-frontend-settings.php on line 416
```

Context in class-wcmp-frontend-settings.php:
```php
public function get_total_price_with_tax($price){
    $price              = (float)$price;
    $base_tax_rates     = WC_Tax::get_base_tax_rates( '');
    $base_tax_key       = key($base_tax_rates);
    $taxRate            = 0 ?? (float)$base_tax_rates[$base_tax_key]['rate']; // Line 416
    $tax                = $price * $taxRate / 100;
    $total_price        = money_format('%.2n', $price + $tax);

    return $total_price;
}
```

### How to reproduce: 
Have no tax rates set up in WooCommerce. (At `.../admin.php?page=wc-settings&tab=tax&section=standard`)

Because `WC_Tax::get_base_tax_rates('')` doesn't return anything the index `$base_tax_key` doesn't exist.

(Temporary?) fix could be to default to 0 if there's no tax rate set up:
```
$taxRate = isset($base_tax_key) ? (float) $base_tax_rates[$base_tax_key]['rate'] : 0;
```

**Comment by RichardPerdaan** [comment]
This issue has been resolved since [3.1.5](https://github.com/myparcelnl/woocommerce/releases/tag/v3.1.5)
