### ISSUE TITLE
Text update on checkout page / myparcel.js

### ISSUE THREAD

**Issue by lgoedhart** [myparcelnl/woocommerce#156]
In myparcel.js version 3.05 on line 964

Instead of the text: <h3>Adresgegevens zijn niet ingevuld</h3>
I would like to suggest: <h3>Adresgegevens zijn _nog_ niet ingevuld</h3>
It's easier to understand for clients.

**Comment by RichardPerdaan** [comment]
The text change d2396303b7eec27fa3e18220587e8e513eba93cf
