### ISSUE TITLE
Unable to use streetNr and streetNrSuffix on mobile-views

### ISSUE THREAD

**Issue by nickurt** [myparcelnl/woocommerce#158]
Hello,

Our customers having problems with adding their streetNumber and streetNumberSuffix on the mobile-view, see screenshot for mobile and desktop-part:

**Mobile**

![afbeelding](https://user-images.githubusercontent.com/5840084/48268972-bf152100-e436-11e8-9bfc-a751d359ccc7.png)

**Desktop**

![afbeelding](https://user-images.githubusercontent.com/5840084/48269015-d3f1b480-e436-11e8-91f1-2391a1f81046.png)

How can I solve this?

**Comment by EdieLemoine** [comment]
Hi,

Thank you for your feedback! In our next release we will add an option to use the default WooCommerce fields instead of our custom fields. This will drastically improve compatibility with themes and other plugins. You can install this version right now by downloading our develop branch. 

We hope to release this version before the end of next week.

**Comment by nickurt** [comment]
Thanks, I tried the develop-version and on the mobile is looks already better, but on the desktop I see some glitches ..

![afbeelding](https://user-images.githubusercontent.com/5840084/48272805-c987e880-e43f-11e8-81e2-770bd82ed7ff.png)

I see 2 times street address for the country Netherlands, and is is possible to move the "suffix" to the right side of Street name and No?, there is some white space for it it seems ..

**Comment by EdieLemoine** [comment]
Please turn on the new address fields setting in the checkout tab in the MyParcel plugin. Thanks again for the feedback, we will make both versions of the fields work as expected!

**Comment by nickurt** [comment]
Thank you Edie,

I did some changes in the settings and I'm now using the (new) option; WooCommerce default shipping fields (_address_1 and _address_2).

Just to make it clear for me, with this new setting the street/housenumber will be splitted in the background (maybe with a regex?) and that will be send to the MyParcel API?

**Comment by EdieLemoine** [comment]
That is correct. The full address (_address_1 + _address_2) is concatenated and then split by a regex. The values are sent to the MyParcel API the same way as when using the three separate fields. 

I improved the responsiveness of the split fields and made them work correctly with Chrome's autofill functionality, in case people want to keep using them.

**Comment by nickurt** [comment]
Thanks, updated to v3.0.5
