### ISSUE TITLE
Texts in template not translatable

### ISSUE THREAD

**Issue by soft79** [myparcelnl/woocommerce#17]
Certain texts in the view-files are hardcoded in html. These can't be translated with the .mo/.po files.

For example:

`<span class="mypa-highlight">Thuis of op het werk bezorgd</span>`

should be replaced by:

`<span class="mypa-highlight"><?php _e('Thuis of op het werk bezorgd', 'woocommerce-myparcel' ); ?></span>`

**Comment by Spreeuw** [comment]
Thanks for the heads up! We are aware of this and will gettext the delivery options strings in the next release. These are not the only strings from the delivery options though, some others come from the MyParcel API scripts (JS) and also need to be translated. For uniformity it's now all dutch.

**Comment by Spreeuw** [comment]
I tried fixing this in b48eb3658aa6dcddd12156bcc96e2c37910f7859 but ran into an issue with several other hardcoded strings and localized date formats. This will need to be fixed in the MyParcel API scripts first.

**Comment by RichardPerdaan** [comment]
it is now possible to change all the texts in the checkout, this is solved in version 3.0.2 of the plugin.
