### ISSUE TITLE
Error: data.shipments[0].recipient.street Must be at least 1 caracters long (Code 0)

### ISSUE THREAD

**Issue by jurjens** [myparcelnl/woocommerce#19]
When trying to export a shipment I'm presented this error. The full adress _is_ present though.

**Comment by Spreeuw** [comment]
Can you share your export data? You can get this by enabling debug logging on the MyParcel settings page, doing the export and then downloading the log file there.

**Comment by jurjens** [comment]
Sure! This is the data it's creating. The street is indeed empty, but Woocommerce does actually have the address

```
2017-03-22 09:13:27 *** Creating shipments started ***
2017-03-22 09:13:27 Shipment data for order 3887:
array (
  0 => 
  array (
    'recipient' => 
    array (
      'cc' => 'NL',
      'city' => 'Amsterdam',
      'person' => 'xxx',
      'company' => '',
      'email' => 'xxx@xxx.xxx',
      'phone' => '',
      'street' => '',
      'number' => '',
      'number_suffix' => '',
      'postal_code' => 'xxxxxx',
    ),
    'options' => 
    array (
      'package_type' => 1,
      'only_recipient' => 0,
      'signature' => 1,
      'return' => 0,
      'large_format' => 0,
      'label_description' => '',
      'delivery_type' => 2,
    ),
    'carrier' => 1,
  ),
)
```

**Comment by Spreeuw** [comment]
Was the MyParcel plugin active when this order was placed? It can't use the 'address_1' and 'address_2' fields from WooCommerce, MyParcel saves the street, number and suffix separately.

**Comment by RichardPerdaan** [comment]
this problem can be solved with a split street function.
Here you can see an example 5a1549c87b7badb32cd4da848e2c1422fa90eeb8
