### ISSUE TITLE
Feature: Cut the product title after 60 characters

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#190]
Currently the plugin gives an error when the title of the product is more than 60 characters long if I try to export a world shipment. I would like to add an option that cuts the title after 60 characters.

**Comment by TimBlom** [comment]
notify the client in case 00470593 when the feature has been released.

**Comment by adem-demir** [comment]
Will be implemented with next version

**Comment by RichardPerdaan** [comment]
This issue has been resolved since [3.1.5](https://github.com/myparcelnl/woocommerce/releases/tag/v3.1.5)
