### ISSUE TITLE
Error in log file: ID was called incorrectly

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#192]
In the log file the following error occurs:

1. PHP message: id was called incorrectly. Order properties should not
be accessed directly. Backtrace: do_action('wp_ajax_wc_myparcel'),
WP_Hook->do_action, WP_Hook->apply_filters,
WooCommerce_MyParcel_Export->export,
WooCommerce_MyParcel_Export->add_shipments, WC_Order->update_status,
WC_Order->save, WC_Order->status_transition,
do_action('woocommerce_order_status_completed'), WP_Hook->do_action,
WP_Hook->apply_filters, WC_Emails::send_transactional_email,
do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters,
WC_Email_Customer_Completed_Order->trigger, WC_Email->get_content,
WC_Email_Customer_Completed_Order->get_content_html,
wc_get_template_html, wc_get_template,
include('/plugins/woocommerce/templates/emails/customer-completed-order.php'),
do_action('woocommerce_email_order_details'), WP_Hook->do_action,
WP_Hook->apply_filters, WC_Emails->order_details, wc_get_template,
include('/plugins/woocommerce/templates/emails/email-order-details.php'),
do_action('woocommerce_email_before_order_table'),...

**Comment by TimBlom** [comment]
Contact case 00478571 after fix

**Comment by adem-demir** [comment]
Can't reproduce client doesn't answer questions
