### ISSUE TITLE
Delivery options not showing label text

### ISSUE THREAD

**Issue by volmerf** [myparcelnl/woocommerce#222]
After updating to Woocommerce 3.5.6 and Myparcel 3.1.3 the delivery options text labels won't show anymore.. See screenshots. I already tried disabling and enabling the delivery options but no luck. Also changing the text won't help.

Please help because now we have to disable the delivery options.

<img width="661" alt="screenshot 2019-03-08 at 20 05 33" src="https://user-images.githubusercontent.com/4939781/54049934-405ea380-41de-11e9-91a6-225be3de24ec.png">
<img width="825" alt="screenshot 2019-03-08 at 20 05 42" src="https://user-images.githubusercontent.com/4939781/54049935-40f73a00-41de-11e9-84f4-7dd8d8b868f1.png">

**Comment by RichardPerdaan** [comment]
Hi @volmerf,

Do you have a caching plugin that cached the page and / or the settings?

**Comment by volmerf** [comment]
Hey Richard,

We have the w3 total cache plugin but of course we clear the whole cache after upgrading our plugins.

Met vriendelijke groet / Best regards,

Frank

Mediablox
Parallelweg 20 | 3959 BC Overberg
T: 0343 - 410999 | Fax: 084 - 2296121
info@mediablox.nl<mailto:info@mediablox.nl> | http://www.mediablox.nl

On Mar 11, 2019, wk 11, at 14:39, Richard Perdaan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @volmerf<https://github.com/volmerf>,

Do you have a caching plugin that cached the page and / or the settings?

**Comment by volmerf** [comment]
Any update on this @RichardPerdaan?

**Comment by RichardPerdaan** [comment]
Hi @volmerf ,
Unfortunately I have no idea why the titles are not visible. If you send an email to support@myparcel.nl then can I look at your website.

**Comment by RichardPerdaan** [comment]
Hi @volmerf 
Is this problem already solved and can I close the issue?

**Comment by volmerf** [comment]
Hi Richard,

Yes, sorry. This was probably caused due to a problem with our Succuri Firewall caching.

**Comment by RichardPerdaan** [comment]
Hi @volmerf,
Good to hear that the problem has been solved, then I will close the issue
