### ISSUE TITLE
compabiliteit met woocommerce eu vat assistant

### ISSUE THREAD

**Issue by soedesh** [myparcelnl/woocommerce#224]
Wanneer de klant gebruik maakt van bovenstaande plugin, dan wordt de VAT regel op zijn pdf factuur overschreven. Zie screenshot.

<img width="1876" alt="vat" src="https://user-images.githubusercontent.com/46486914/54204385-7187ee00-44d4-11e9-96e4-2b66fa3cd974.png">

**Comment by RichardPerdaan** [comment]
There were no questions about this compatibility in 4 years. We have made the choice to close the issue.
