### ISSUE TITLE
Checkout translation issue HOUSE NUMBER/POSTCODE COMBINATION UNKNOWN

### ISSUE THREAD

**Issue by Chris707** [myparcelnl/woocommerce#230]
<img width="747" alt="woolang" src="https://user-images.githubusercontent.com/25433104/55550537-af91bf80-56d8-11e9-90dd-3f9124a5a189.png">

This must be translated to Dutch!

**Comment by RichardPerdaan** [comment]
This issue has been resolved since [3.1.5](https://github.com/myparcelnl/woocommerce/releases/tag/v3.1.5)
