### ISSUE TITLE
Disable delivery date in orderview for Belgium shipments

### ISSUE THREAD

**Issue by adem-demir** [myparcelnl/woocommerce#231]
Disable delivery date in orderview for Belgium shipments.You can't use any delivery day so don't show in the orderview. Also check the mail if this will be send to customers.

Case: 00548704

**Comment by RichardPerdaan** [comment]
This issue has been resolved since [3.1.5](https://github.com/myparcelnl/woocommerce/releases/tag/v3.1.5)
