### ISSUE TITLE
Postal Code string misaligned

### ISSUE THREAD

**Issue by f3bruary** [myparcelnl/woocommerce#24]
In the latest version of the plugin in combination with the Flatsome WooCommerce theme, the postal code on the checkout form is not aligned properly. The text shows up behind the address number extension. But the text area for the postal code is below it.

![image](https://user-images.githubusercontent.com/5641933/28116524-b89e92f8-6709-11e7-8065-5cd8ee9b6ab2.png)

**Comment by f3bruary** [comment]
I wanted to add that this happens on small screens. The theme is responsive. On mobile screens for example, this issue is visible.

**Comment by bluekachina** [comment]
We solved it by changing the mobile only css of out flatsome the to:

#billing_postcode{
  width: 30%;
}

**Comment by f3bruary** [comment]
Thanks! I'll give it a shot
