### ISSUE TITLE
Digitale postzegel wordt ongeacht het gewicht geëxporteerd met het laagste tarief 

### ISSUE THREAD

**Issue by soedesh** [myparcelnl/woocommerce#240]
Als er een order met digitale postzegel met een waarde boven de 100 gram binnenkomt en direct wordt geëxporteerd, dan wordt het gedaan met het gewicht voor het laagste tarief (0,83 ct). Als de zending wordt geëxporteerd nadat het is opgeslagen, dan wordt wel gehouden aan het juiste tarief.

**Comment by RichardPerdaan** [comment]
Dit probleem is opgelost sinds [3.1.5](https://github.com/myparcelnl/woocommerce/releases/tag/v3.1.5)
