### ISSUE TITLE
Shipment validation error - PakjeGemak

### ISSUE THREAD

**Issue by adem-demir** [myparcelnl/woocommerce#244]
Wanneer de instellingen standaard op "retour bij geen gehoor" is aangevinkt, krijg je bij PakjeGemak label een shipment validation error bij het exporteren.

**Comment by RichardPerdaan** [comment]
Dit probleem is opgelost sinds [3.1.5](https://github.com/myparcelnl/woocommerce/releases/tag/v3.1.5)
