### ISSUE TITLE
Issue with Address field

### ISSUE THREAD

**Issue by f3bruary** [myparcelnl/woocommerce#25]
Klanten voeren soms hun postcode in bij 'Toevoeging'. MyParcel plugin kan dan geen label exporteren. Ik moet dit zelf corrigeren door de tekst uit de toevoeging weg te halen (en uit het adres veld) voordat ik een label kan aanmaken.

Misschien is het een idee om hier een check voor te plaatsen tijdens de checkout ?

**Comment by RichardPerdaan** [comment]
Beste @f3bruary ,

Deze issue staat al heel lang open en in de tussentijd zijn er veel aanpassingen geweest omtrent de MyParcel WooCommerce plugin. Één van de aanpassingen is het ondersteunen van de standaard WooCommerce adres velden. Daarnaast is er ook een check ingebouwd die controleert of alle velden zijn ingevuld. 

Mocht dit probleem nog steeds plaatsvinden dan zou ik je willen adviseren om de standaard WooCommerce velden te gebruiken.

Mocht dit niet de oplossing zijn dan hoor ik dat graag van je, voor nu sluit ik de issue. Deze kan natuurlijk altijd weer heropend worden.

**Comment by f3bruary** [comment]
@RichardPerdaan Ik gebruik de standaard checkout fields van WC, en het gaat hier niet om ontbrekende velden. Het gaat hier om een te lange string in het 'Toevoeging' veld.

Dit komt omdat sommige klanten als baby te vaak op hun hoofd zijn gevallen en bij Toevoeging, waar je normaal 'A' or '-2' gebruikt, iets zoals "Appartement" of hun postcode invullen.

Hierdoor word de waarde van shipping_address "Straatnaam 123-Appartement", en MyParcel kan dan geen label aanmaken en ik krijg de melding dat het veld te lang is.

Het is al een poosje niet meer gebeurd, dus misschien zit het nu wel goed. Ik hou het wel in de gaten en laat het je weten als het nogmaals voorkomt.

Heb je dit zelf al getest ? Ik heb zelf geen test omgeving...

**Comment by RichardPerdaan** [comment]
@f3bruary,

Ik heb dit probleem meerdere malen getest en bij mij kwam het probleem niet meer voor. Mocht het toch niet goed gaan dan kan je de issue weer openen en dan gaan we ermee aan de slag.
