### ISSUE TITLE
Wordpress 5.2 error

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#256]
The clients of MyParcel NL and BE an error since Wordpress version 5.2:

**NL**

`Hallo!

Sinds WordPress 5.2 is er een ingebouwde functie die herkent wanneer een plugin of thema een fatale fout veroorzaakt op je site en die je op de hoogte stelt met deze automatische e-mail.

In dit geval heeft WordPress een probleem gevonden met één van je plugins,WooCommerce MyParcel.

Bezoek eerst je website (https://myxboutique.nl/) en kijk of er zichtbare problemen zijn. Bezoek daarna de pagina waar de fout was gevonden (https://myxboutique.nl/wp-admin/post.php?post=7586&action=edit&myparcel_done=true) en kijk of er zichtbare problemen zijn.

Neem contact op met je host voor hulp bij het verder onderzoeken van dit probleem.

In het geval dat je site kapot lijkt te zijn, en je het dashboard niet op de normale manier kunt benaderen, heeft WordPress nu een speciale 'herstelmodus". Deze laat je op een veilige manier op je dashboard inloggen om het probleem verder te onderzoeken.

https://myxboutique.nl/wp-login.php?itsec-hb-token=boutiquemyx&action=enter_recovery_mode&rm_token=AF8ommiyoNk3a48n2SNL1Y&rm_key=UlEFE9s0Lrm3GNOonO6jQj

Om je site veilig te houden verloopt deze link over 1 dag. Maak je daar maar niet druk om, er wordt een nieuwe link naar je gestuurd wanneer het probleem zich weer voordoet nadat de link is verlopen.

Foutdetails
===========
Een fout van het type E_ERROR werd veroorzaakt op regelnummer 134 van het bestand /home/jerb1937/public_html/myxboutique.nl/wp-content/plugins/woocommerce-myparcel/includes/class-wcmp-rest.php. Foutmelding: Uncaught Error: Cannot use object of type WP_Error as array in /home/jerb1937/public_html/myxboutique.nl/wp-content/plugins/woocommerce-myparcel/includes/class-wcmp-rest.php:134
Stack trace:
#0 /home/jerb1937/public_html/myxboutique.nl/wp-content/plugins/woocommerce-myparcel/includes/class-wcmp-rest.php(93): WC_MyParcel_REST_Client->request('https://api.myp...', 'GET', Array, NULL, NULL, false)
#1 /home/jerb1937/public_html/myxboutique.nl/wp-content/plugins/woocommerce-myparcel/includes/class-wcmp-api.php(134): WC_MyParcel_REST_Client->get('https://api.myp...', Array)
#2 /home/jerb1937/public_html/myxboutique.nl/wp-content/plugins/woocommerce-myparcel/includes/class-wcmp-export.php(1165): WC_MyParcel_API->get_shipments(48326115)
#3 /home/jerb1937/public_html/myxboutique.nl/wp-content/plugins/woocommerce-myparcel/includes/class-wcmp-admin.php(382): WooCommerce_MyParcel_Export->get_shipment_data(48326115, Object(WC_Order))
#4 /home/jerb1937/public_html/myxboutique.nl/wp-admin/includes/template.php(1304): WooCom`

**BE**

`Howdy!

Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, WC MyParcel Belgium.

First, visit your website (https://ray.care/) and check for any visible issues. Next, visit the page where the error was caught (https://ray.care/wp-admin/post.php?post=8475&action=edit) and check for any visible issues.

Please contact your host for assistance with investigating this issue further.

If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.

https://ray.care/wp-login.php?action=enter_recovery_mode&rm_token=JTSJSGuz7rCKglol1KfhUA&rm_key=OKsAJZUVNxx8mT4dpj6wr7

To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.

Error Details
=============
An error of type E_ERROR was caused in line 134 of the file /data/sites/web/raycare/www/wp-content/plugins/wc-myparcel-belgium/includes/class-wcmp-rest.php. Error message: Uncaught Error: Cannot use object of type WP_Error as array in /data/sites/web/raycare/www/wp-content/plugins/wc-myparcel-belgium/includes/class-wcmp-rest.php:134
Stack trace:
#0 /data/sites/web/raycare/www/wp-content/plugins/wc-myparcel-belgium/includes/class-wcmp-rest.php(93): wc_myparcelbe_REST_Client->request('https://api.myp...', 'GET', Array, NULL, NULL, false)
#1 /data/sites/web/raycare/www/wp-content/plugins/wc-myparcel-belgium/includes/class-wcmp-api.php(134): wc_myparcelbe_REST_Client->get('https://api.myp...', Array)
#2 /data/sites/web/raycare/www/wp-content/plugins/wc-myparcel-belgium/includes/class-wcmp-export.php(1051): wc_myparcelbe_API->get_shipments(48314477)
#3 /data/sites/web/raycare/www/wp-content/plugins/wc-myparcel-belgium/includes/class-wcmp-admin.php(380): WooCommerce_MyParcelBE_Export->get_shipment_data(48314477, Object(WC_Order))
#4 /data/sites/web/raycare/www/wp-admin/includes/template.php(1304): WooCommerce_MyParcelBE_Admin->create_box_content(Object(WP_Post), Array)
#5 /data/sites`

**Comment by TimBlom** [comment]
Case 00583639 & 00583625

**Comment by adem-demir** [comment]
tested with v3.1.6
