### ISSUE TITLE
Barcode in order afgerond niet actueel na recreëren zending

### ISSUE THREAD

**Issue by soedesh** [myparcelnl/woocommerce#260]
Wanneer de klant een afgeronde zending weer op status in behandeling wijzigt, en vervolgens een nieuwe barcode genereert >> bestelling afgerond markeert, dan staat op de automatisch gegenereerde notificatie de vorige barcode. Wanneer de email handmatig op afgerond/ verzonden wordt verstuurd, dan komt naast de vorige barcode, ook de actuele in de notificatie te staan.

PostNL/MyParcel case: 586722

**Comment by RichardPerdaan** [comment]
Opgelost vanaf versie v4.0.0
