### ISSUE TITLE
Barcode wordt niet mee genomen op de verzonden notificatie

### ISSUE THREAD

**Issue by soedesh** [myparcelnl/woocommerce#261]
Wanneer je vanuit het orderoverzicht in woocommerce een zending exporteert en uitprint (met de instelling Orderstatus automatisering aangevinkt, dan worden de barcode niet meegenomen op de verzonden notificatie van woocommerce.

Wanneer je de zending opent en dan exporteert, uitprint, dan wordt de barcode wel meegenomen.

**Comment by RichardPerdaan** [comment]
De issue is hetzelfde als #277
