### ISSUE TITLE
Barcode wordt na export zending niet direct getoond in het orderoverzicht 

### ISSUE THREAD

**Issue by soedesh** [myparcelnl/woocommerce#262]
De barcode wordt in het zendingoverzicht in woocommerce alleen getoond als je de zending exporteert in een geopende order, en dan weer teruggaat naar het orderoverzicht.

**Comment by stonjohnsson** [comment]
Wij ervaren dit probleem ook. Is dit inmiddels al opgelost?

**Comment by stonjohnsson** [comment]
@adem-demir heb je misschien een update hiervoor? :-)

**Comment by adem-demir** [comment]
@stonjohnsson We merken dat dit nu **weer** niet meer wordt getoond in sommige browsers inderdaad. Ik zal deze weer openzetten. Helaas kan ik je nog geen indicatie geven, wanneer we deze gaan oppakken.
