### ISSUE TITLE
Verzendadres wordt niet als leidend gebruikt bij het aanmaken zending vanuit buitenland

### ISSUE THREAD

**Issue by soedesh** [myparcelnl/woocommerce#272]
Wanneer je een zending aanmaakt vanuit het buitenland met een buitenlandse factuuradres, en deze naar een Nederlandse adres wilt versturen, dan wordt er geen bezorgopties getoond. Het lijkt erop dat het factuuradres hier als leidend wordt gebruikt.

Case: 619440

**Comment by RichardPerdaan** [comment]
Het Factuuradres zal niet als leidend worden beschouwd. Wat hier het probleem is, is dat de shop zich in het buitenland bevind en hier PostNL niet actief is.
