### ISSUE TITLE
Add BBP and Pakket option to each Bolder Elements option

### ISSUE THREAD

**Issue by adem-demir** [myparcelnl/woocommerce#274]
Case: 00584268

**Example**
![Shipping zones ‹ Shipping ‹ Settings ‹ Lieve Labels nl — WooCommerce 2019-08-20 13-21-50](https://user-images.githubusercontent.com/37372250/63343101-7be4c880-c34d-11e9-8719-71a386acd2d4.jpg)

**Comment by DarkAllMan** [comment]
Excellent!

**Comment by RichardPerdaan** [comment]
It is possible from version 3.0 to add shipping classes in the Bolder Elements plugin. This makes it possible to link the shipping classes to MyParcel, with the correct package type.

![image](https://user-images.githubusercontent.com/11389731/188577643-201763a0-0429-4a56-8631-209efbb64346.png)

**Comment by DarkAllMan** [comment]
You are right that we can use shipping classes in BETRS.
However, in my case a shipping class can have multiple shipping types.
For instance I have a shipping class "Brievenbuspakketje Max 5"
When the QTY of the items is <= 5, shipping type = Brievenbuspakketje
When the QTY of the item is > 5, shipping type will change to Pakket.
Therefor I created my own plugin that adds the MyParcel Shippingtype per BETRS Table Row

![image](https://user-images.githubusercontent.com/1582343/188583042-adb96a0f-e180-40c1-ae63-df67c2d4c6aa.png)
