### ISSUE TITLE
Fatal error in class-wcmp-rest

### ISSUE THREAD

**Issue by SHoogland** [myparcelnl/woocommerce#275]
Hi, ik krijg mailtjes met de volgende informatie. Is dit iets wat fout gaat op mijn site? of handelt de plugin een error niet goed af?

woocommerce-myparcel: v3.1.7 

[Mon Aug 26 07:27:32.677819 2019] [:error] [pid 26146] [client 213.127.40.133:56214] PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /content/plugins/woocommerce-myparcel/includes/class-wcmp-rest.php:134
Stack trace:
#0 /content/plugins/woocommerce-myparcel/includes/class-wcmp-rest.php(93): WC_MyParcel_REST_Client->request('https://api.myp...', 'GET', Array, NULL, NULL, false)
#1 /content/plugins/woocommerce-myparcel/includes/class-wcmp-api.php(134): WC_MyParcel_REST_Client->get('https://api.myp...', Array)
#2 /content/plugins/woocommerce-myparcel/includes/class-wcmp-export.php(1204): WC_MyParcel_API->get_shipments(51514955)
#3 /content/plugins/woocommerce-myparcel/includes/class-wcmp-admin.php(389): WooCommerce_MyParcel_Export->get_shipment_data(51514955, Object(WC_Order))
#4 /wordpress/wp-admi in /content/plugins/woocommerce-myparcel/includes/class-wcmp-rest.php on line 134, referer: https://****/wordpress/wp-admin/edit.php?s=string&post_status=all&post_type=shop_order&action=-1&m=0&_customer_user&paged=1&action2=-1

**Comment by adem-demir** [comment]
Hi,

Zou je mij kunnen laten weten of dit altijd op een maandag gebeurd? Wij kunnen dit helaas niet recreëren en ons test omgeving.

**Comment by stonjohnsson** [comment]
Ik haak even in en ik heb het ook al een keer op een donderdag meegemaakt (dus zal ook wel op andere dagen zo zijn) ;-)

**Comment by Nikitaverh** [comment]
@case:00649368

**Comment by RichardPerdaan** [comment]
Fixed in version 3.1.8 of the MyParcel plugin.
