### ISSUE TITLE
Update order status when package is delivered

### ISSUE THREAD

**Issue by TeunSmit** [myparcelnl/woocommerce#276]
Client asks if it is possible to add a feature like the 'Automatische orderstatus', but then have the orderstatus change when the package is delivered. 
<img width="1917" alt="MyParcel Automatische orderstatus" src="https://user-images.githubusercontent.com/54140671/63866646-cef4f600-c9b3-11e9-9a42-e734137acc30.png">

**Comment by TeunSmit** [comment]
00626920
00632215

**Comment by adem-demir** [comment]
same as https://github.com/myparcelnl/woocommerce/issues/15
