### ISSUE TITLE
bezorgopties uit PostNL woocommerce op de orderbevestiging

### ISSUE THREAD

**Issue by soedesh** [myparcelnl/woocommerce#278]
Klant (fulfilment bedrijf) wilt de bezorgopties uit PostNL woocommerce op de orderbevestiging. Bij Magento schijnt dit wel het geval te zijn? Het is op deze manier erg lastig werken voor hun.

Case: 643923

**Comment by RichardPerdaan** [comment]
Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin. De update is vanmorgen live gezet en kan via de reguliere update worden geïnstalleerd.
