### ISSUE TITLE
Issue with exporting 2nd time

### ISSUE THREAD

**Issue by f3bruary** [myparcelnl/woocommerce#28]
Ik heb een lijst met 8 orders. Ik 'bulk exporteer' allen naar MyParcel. Nu krijg ik een foutmelding dat 1 van de addressen incorrect it. Een klant heeft zijn/haar postcode bij Toevoeging ingevuld en dit veroorzaakt een veld dat te lang is. Nu heb ik het adres handmatig gecorrigeerd en wou alle orders opnieuw exporteren (omdat de foutmelding eerder ook aangaf dat een aantal orders niet waren ge-exporteerd).

Nu lukt het me niet meer om opnieuw de orders te exporteren. Niet via bulk acties en ook niet via de order pagina. De melding is: De geselecteerde orders zijn nog niet naar MyParcel geëxporteerd!

De track/trace status op de order pagina is "(Unknown)	-".
Het retouricoon is ook niet aanwezig.

Het pdf bestand heeft wel een barcode. Maar bij het printen (via Wordpress Dymo plugin) komt deze niet op het label terecht.

**Comment by f3bruary** [comment]
logs (klantinfo hernoemd)

`10-09-2017 @ 13:29:07 - *** Creating shipments started ***
10-09-2017 @ 13:29:07 - Shipment data for order 21514:
array (
  0 => 
  array (
    'recipient' => 
    array (
      'cc' => 'NL',
      'city' => 'Stad',
      'person' => 'Voornaam Achternaam',
      'company' => '',
      'email' => 'email@hotmail.com',
      'phone' => '0600000000',
      'street' => 'Straat',
      'number' => '16',
      'number_suffix' => 'a',
      'postal_code' => '1111AA',
    ),
    'options' => 
    array (
      'package_type' => 1,
      'only_recipient' => 0,
      'signature' => 0,
      'return' => 0,
      'large_format' => 0,
      'label_description' => '',
      'delivery_type' => 2,
      'delivery_date' => '2017-10-10 00:00:00',
    ),
    'carrier' => 1,
  ),
)
10-09-2017 @ 13:29:07 - API response (order 21514):
array (
  'code' => 200,
  'body' => 
  array (
    'data' => 
    array (
      'ids' => 
      array (
        0 => 
        array (
          'id' => 26766688,
        ),
      ),
    ),
  ),
  'headers' => 
  array (
    'server' => 'nginx/1.10.3',
    'date' => 'Mon, 09 Oct 2017 11:28:58 GMT',
    'content-type' => 'application/json;charset=utf-8',
    'transfer-encoding' => 'chunked',
    'connection' => 'keep-alive',
    'x-powered-by' => 'PHP/5.6.30-10+deb.sury.org~trusty+2',
    'access-control-allow-origin' => '*',
  ),
)
10-09-2017 @ 13:29:07 - *** Failed label request (not exported yet) ***`

**Comment by f3bruary** [comment]
Ik zie in de backend van myparcel dat ze wel zijn voorgemeld.

**Comment by adem-demir** [comment]
@f3bruary Goedemiddag!

Is dit probleem nog steeds aanwezig met de huidige versie van de plugin?

**Comment by f3bruary** [comment]
@adem-demir nee, heb ik niet meer terug zien komen.

**Comment by RichardPerdaan** [comment]
Beste @f3bruary,

Goed om te horen dat je het niet meer terug heb zien komen. Ik zou daarom de issue willen sluiten. Mocht het toch weer voorkomen dan kan je de issue gewoon weer openen.
