### ISSUE TITLE
Order status and stock levels changes after creating label 

### ISSUE THREAD

**Issue by markjongkind** [myparcelnl/woocommerce#280]
After we issue the label via MyParcel, it changes the order status from `processing` to `awaiting payment`. It also automatically increases the stock back (as if no sale happened).

Why is this happening and how can I fix this?

![myparkcel_issue](https://user-images.githubusercontent.com/7794593/68110157-9e1dc980-feec-11e9-8d14-695c173b09e3.png)

**Comment by adem-demir** [comment]
@markjongkind je kan bij de instellingen aanpassen welk status je order krijgt bij een export. Je zou hiernaar moeten kijken, maar de code doet niks met de voorraad.
