### ISSUE TITLE
Feature Request: Compatibility WC Checkout 

### ISSUE THREAD

**Issue by NikitaMyParcel** [myparcelnl/woocommerce#285]
Shipping option like evening delivery are not shown when WooCommerce Checkout Plugin (https://www.checkoutwc.com/) is used. 

When plugin is deactivated, the shipping options are shown

**Comment by Nikitaverh** [comment]
00666875

**Comment by RichardPerdaan** [comment]
Omdat er de afgelopen 3 jaar geen vragen zijn geweest over de Compatibility van de WC Checkout sluit ik de issue, wanneer er meer vragen zijn dan kunnen we de issue gewoon weer heropenen.
