### ISSUE TITLE
Checkout: Slow loading and customers aborting

### ISSUE THREAD

**Issue by bluekachina** [myparcelnl/woocommerce#29]
We have implemented the checkout features on our live website.
Since that moment the numbers of customers completing the checkout have dropped.

Could the plugin be altered so these shipping options only appear (and are loaded) after the customer selects a checkbox?

[ x ] shipping options

When I look at heatmaps I that customers are confused by the current GUI. There is a lot of information that they sometimes do not even need.

**Comment by RichardPerdaan** [comment]
The speed has been improved in version 3.0.2 of the plugin
