### ISSUE TITLE
Feature request: Product_ID in label description

### ISSUE THREAD

**Issue by Nikitaverh** [myparcelnl/woocommerce#292]
Would like the possibility to add product_id to label description to work faster.

**Comment by Nikitaverh** [comment]
00687416

**Comment by RichardPerdaan** [comment]
Hoe moet die gedaan worden als er meerdere producten in een pakket zit?

**Comment by RichardPerdaan** [comment]
Voor nu heeft deze functionaliteit geen prio. Daarnaast zal er meer conflicten komen zodra we dit gaan realiseren.

Mocht er meer vraag naar zijn dan kan de issue altijd weer geopend worden.
