### ISSUE TITLE
Feature request: Custom step checkout support

### ISSUE THREAD

**Issue by NikitaMyParcel** [myparcelnl/woocommerce#324]
Klant heeft custom stap in de checkout en daar zouden ze de PostNL-bezorgopties willen tonen. Nu moeten ze dit zelf in de code aanpassen en bij een update van de plugin, verdwijnt dit weer. Zouden mogelijkheid willen om dit aan te passen in de instellingen.

**Comment by Nikitaverh** [comment]
00720621

**Comment by RichardPerdaan** [comment]
Dit is mogelijk door de optie `Bezorgopties positie`. Door deze opties is het mogelijk doormiddel van meerdere hooks om de locatie te bepalen.
