### ISSUE TITLE
Evening delivery isn't shown in order details

### ISSUE THREAD

**Issue by Nikitaverh** [myparcelnl/woocommerce#327]
When 'levervenster' is 0 days, evening delivery isn't shown in the order details. 
![Bestelling bewerken ‹ MyParcel — WordPress 2020-03-23 14-16-35](https://user-images.githubusercontent.com/54140706/77320840-929f3380-6d11-11ea-8102-33762d1d602c.png)

When 'levervenster' is 1 day or more, evening delivery is shown in the order details.
<img width="1552" alt="Bestelling bewerken ‹ MyParcel — WordPress 2020-03-23 14-17-00" src="https://user-images.githubusercontent.com/54140706/77320865-9c289b80-6d11-11ea-88af-b49ff223b999.png">

(Screenshots show the same order, but with the different settings activated) 

Would like to see the delivery option for 'levervenster = 0' the same as 'levervenster > 1'

**Comment by Nikitaverh** [comment]
00725846

**Comment by adem-demir** [comment]
We will solve this option with version 4.0.0
