### ISSUE TITLE
Issues Afterpay 

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#33]
When someone uses Afterpay and chooses for a pick up location the order cannot be placed (same issue that has been fixed in Magento).

When changes are made, please contact 00242015

**Comment by RichardPerdaan** [comment]
Also case: 00143416

**Comment by adem-demir** [comment]
also case 422856

**Comment by adem-demir** [comment]
00439924

**Comment by adem-demir** [comment]
00441703
