### ISSUE TITLE
Multisite ondersteuning

### ISSUE THREAD

**Issue by adem-demir** [myparcelnl/woocommerce#355]
We zouden graag 2 of meer webshops willen installeren op een wordpress omgeving. Alleen ondersteund de MyParcel plugin dit op dit moment niet.

**Comment by Nikitaverh** [comment]
00847394

**Comment by RichardPerdaan** [comment]
Dit is mogelijk vanaf versie : [v4.2.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.2.0)
