### ISSUE TITLE
Export an order with an old delivery date

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#36]
When a customer chooses for a delivery day (12-12 for example) and I try do export it on 14-12 I get an error.

![image](https://user-images.githubusercontent.com/22811561/33809145-5e58ddca-ddf2-11e7-930f-716f0ee8e6f3.png)

The error only occurs with the extra delivery options (evening delivery for example)

Case 00257346

**Comment by TimBlom** [comment]
Also case 260378

**Comment by RichardPerdaan** [comment]
The fix for this issue https://github.com/myparcelnl/woocommerce/pull/55
