### ISSUE TITLE
Versie 4.0.1: Bezorgopties worden getoond bij digitale postzegel en brievenbuspakje

### ISSUE THREAD

**Issue by Nikitaverh** [myparcelnl/woocommerce#366]
Gewenst is dat de bezorgopties worden verborgen wanneer er wordt geswitched naar een brievenbuspakje/digitale postzegel in het overzicht van de bestelling. 

![Uploading Bestellingen ‹ MyParcel — WordPress 2020-07-29 16-34-28.png…]()

**Comment by RichardPerdaan** [comment]
Opgelost vanaf versie 4.1.4
