### ISSUE TITLE
Version 4.0.1 no pick-up location in order confirmation

### ISSUE THREAD

**Issue by TeunSmit** [myparcelnl/woocommerce#367]
In the new beta there is no "Afhalen bij PostNL: [Location]" in the order confirmation email. 
How to reproduce issue:
Customer places order with a pick-up location > Confirms and pays the order > gets a WooCommerce email with the order confirmation 
This email is missing the location information, which makes it confusing for the consumer to see if it all came true correctly.

**Comment by RichardPerdaan** [comment]
In the previous versions, this functionality was also not possible, therefore I marked it as a feature.

**Comment by RichardPerdaan** [comment]
This has been fixed in version [4.3.1] (https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1) of the MyParcel WooCommerce plugin.
