### ISSUE TITLE
Incorrect # of exports when exporting from order page

### ISSUE THREAD

**Issue by f3bruary** [myparcelnl/woocommerce#37]
When I export an order from the order details page I get the message "3 zendingen met succes geëxporteerd naar Myparcel" although just 1 order has been exported.

**Comment by RichardPerdaan** [comment]
Hi @f3bruary,

It has been a long time since this is reported. I am curious if this problem still exists?
When it is still there then I would like to solve it for you.

**Comment by f3bruary** [comment]
I haven't seen this error in a while so it could have been fixed in any of the updates since then. I know it only happened when an couldn't be processed. This was usually because of an error in the checkout field. For example a "Toevoeging" that was too long. Some clients enter their postal code here and the plugin couldn't process it cause it was too long. Afterwards I was always unable to export it again and had to create it manually on the myparcel dashboard.

I've had some failed exports this week, but I could always re-export them after fixing the invalid shipping fields. So I assume this won't occur anymore.

I do request the feature to validate checkout fields upon entry (javascript). So if one of the fields couldn't be exported to MyParcel, the checkout form should not be submittable.
