### ISSUE TITLE
No pickup point for 8710 in Begium

### ISSUE THREAD

**Issue by Goldenlion2020** [myparcelnl/woocommerce#377]
When a customer wants to select a pickup point for postal code 8710 (Belgium) there are no options. But there are certainly options when I look on the pickup point checker on the Belgian PostNL website.

Besides that it is strange that when there is no selection to be made, the customer can still choose the option Pickup at Parcelpoint, it should be better if the selection switches back to Home delivery.

**Comment by EdieLemoine** [comment]
I tried it on https://myparcelnl.github.io/delivery-options and I get results for this postal code. It might have been an error in our API or an API of one of the provided carriers at that time.

The other issue is unrelated to this plugin. I created myparcelnl/delivery-options#36 for that.
