### ISSUE TITLE
Checkout continuously reloads when shipping method not in selected shipping methods

### ISSUE THREAD

**Issue by ricklambrechts** [myparcelnl/woocommerce#379]
Hi,

We want to make use of the local_pickup option in WooCommerce next to the My Parcel plugin.

So we want My Parcel frontend only be showed when the flatrate option is selected. That is currently possible with the settings.
But when the user selects the local_pickup shipping method, the checkout is being reloaded. This is because of this else statement.
https://github.com/myparcelnl/woocommerce/blob/0d4ab8af3b78812de182dac4adcc3f9f566c65c1/assets/js/wcmp-frontend.js#L75-L94

Could you look in to it?

**Comment by ricklambrechts** [comment]
Maybe you could check if the shipping_method is in "Ongefrankeerd".
![image](https://user-images.githubusercontent.com/1367665/91971640-d31bc800-ed19-11ea-9ec3-c12cc967e060.png)

**Comment by Mitchell-MyParcel** [comment]
@ricklambrechts : This should be fixed in v4.0.7 that will be released later this week.
