### ISSUE TITLE
Total weight of EU3 / Global shipment

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#38]
When an order contains more than 1 product the total weight is not the sum of the weights combined. 

Case 00264808

**Comment by TimBlom** [comment]
Also case 00270304

**Comment by adem-demir** [comment]
00442237

**Comment by RichardPerdaan** [comment]
The fix: 39b18f4e6b0cc0a5a249c8341d4ef08256dc543d
