### ISSUE TITLE
18+ instellen op product niveau/ MyParcel en PostNL plugin

### ISSUE THREAD

**Issue by Chris707** [myparcelnl/woocommerce#380]
In de WooCommerce plugin bestaat de optie om leeftijdscheck toe te voegen als bezorgoptie. Het lijkt er alleen op dat je het alleen ‘aan’ of ‘uit’ kan zetten, maar dat het niet in te stellen is op productniveau. 
Graag de aanpassing maken zodat het op product niveau in te stellen is. (net zoals de HS codes bij producten bv.....)

**Comment by RichardPerdaan** [comment]
PR #388
