### ISSUE TITLE
Bolder Elements Table Rate package type issue

### ISSUE THREAD

**Issue by robindelaater** [myparcelnl/woocommerce#383]
Bolder Elements table rate plugin shows one package type double.
<img width="470" alt="Screenshot 2020-09-04 at 14 35 22" src="https://user-images.githubusercontent.com/47381559/92370458-99bcd100-f0fa-11ea-8863-6e124b556a7e.png">

**Comment by DarkAllMan** [comment]
I have the same. Also I just sent an email to support@myparcel about other issues.
Table Rates is especially to get 1 class per product and calculate the shipping cost.
Which means a shipping class is not either post or packet. It can be calculated.

**Comment by DarkAllMan** [comment]
class-wcmp-shipping-methods.php line 175
`            /*
             * It appears that after version 4.0.0 the separator changed from "_" to ":". We're adding both variants
             * here for compatibility.
             */
            foreach ([':', '_'] as $separator) {
                $this->addShippingMethod(
                    self::TABLE_RATES_BOLDER_ELEMENTS . "$separator{$zoneShippingMethod->instance_id}-{$optionId}",
                    "{$zone->get_zone_name()} - {$label}"
                );
            }`
This creates 2 entries for each shipping zone!

**Comment by RichardPerdaan** [comment]
I've looked into this problem but the problem doesn't seem to exist anymore. This is why I am closing the issue. if the problem still exists, it is possible to open the issue again.

**Comment by DarkAllMan** [comment]
Confirmed
