### ISSUE TITLE
Deprecated functions

### ISSUE THREAD

**Issue by adem-demir** [myparcelnl/woocommerce#394]
Deprecated: WC_Abstract_Legacy_Order::get_product_from_item is verouderd sinds versie 4.4.0. Gebruik in plaats daarvan $item->get_product(). in /home/saiteenl/domains/saitee.nl/public_html/wp-includes/functions.php on line 4773

Deprecated: WC_Abstract_Legacy_Order::get_product_from_item is verouderd sinds versie 4.4.0. Gebruik in plaats daarvan $item->get_product(). in /home/saiteenl/domains/saitee.nl/public_html/wp-includes/functions.php on line 4773
Soort zending:

Deprecated: WC_Abstract_Legacy_Order::get_product_from_item is verouderd sinds versie 4.4.0. Gebruik in plaats daarvan $item->get_product(). in /home/saiteenl/domains/saitee.nl/public_html/wp-includes/functions.php on line 4773

**Comment by RichardPerdaan** [comment]
Duplicated issue #344
