### ISSUE TITLE
allowedShippingMethods not matching with ID

### ISSUE THREAD

**Issue by BwamNL** [myparcelnl/woocommerce#395]
I have multiple regions with the same shipping methods. For example, region "The Netherlands" has free_shipping, flat_rate and local_pickup, but for the region "Belgium" I have added the same methods, but with different rates.

Now the ID between these methods is different, for example:
flat_rate:2 for Netherlands
flat_rate:6 for Belgium

In the MyParcel Plugin I have selected to show only for allowedShipping Methods. In the Javascript Array it shows [flat_rate, free_shipping].

In the function currentShippingMethodHasDeliveryOptions of wcmp-frontend.js it checks if MyParcel is allowed for the shipping method. But it compares flat_rate:2 with flat_rate, which results in a false.

Is it possible to add the complete allowed ID, to the allowedShippingMethods settings in the admin?

Versie: 4.0.2

**Comment by Mitchell-MyParcel** [comment]
@BwamNL : This is fixed in the latest version. Could you install the latest version and let us know if your issue is solved?

**Comment by BwamNL** [comment]
@Mitchell-MyParcel, Yes it works!

**Comment by RichardPerdaan** [comment]
Hi @BwamNL ,
Good to hear, I will also close the issue
