### ISSUE TITLE
Afgeleverde bestelling verdwijnen

### ISSUE THREAD

**Issue by sebas6691** [myparcelnl/woocommerce#396]
MyParcel past de Order Status van orders aan waarvan deze succesvol is afgeleverd bij de klant.
Echter is de Order Status "Delivered" niet geregistreerd waardoor het lijkt dat de orders verdwijnen uit de orderlijst.
MyParcel past de order status pas aan wanneer ik de order in ga (edit) en weer er terug uit ga.

In PHPMyAdmin zie ik dat de order nog wel in de database staat, maar met de post_status "custom-delivered".
Wanneer ik deze Order status aanmaak in de functions.php van mijn thema komen de orders inderdaad tevoorschijn.

Ik heb de plugin terug gerold naar versie 3.2.0 gezien dit probleem erg vervelend is voor mijn boekhouding.

![Custom Order Status Bug](https://user-images.githubusercontent.com/72159116/94720763-2c950800-0355-11eb-97df-3fdfdf2d4fec.jpg)

**Comment by SitiWeb** [comment]
Ik heb hetzelfde probleem. Ik heb het alleen opgelost door zelf de custom order status aan te maken.

add_filter( 'woocommerce_register_shop_order_post_statuses', 'sitiweb_register_custom_order_status' );
 
function sitiweb_register_custom_order_status( $order_statuses ){
    if (!in_array('custom-delivered', $order_statuses)){
   
   $order_statuses['custom-delivered'] = array(                                 
   'label'                     => _x( 'Order delivered', 'Order status', 'woocommerce' ),
   'public'                    => false,                                 
   'exclude_from_search'       => false,                                 
   'show_in_admin_all_list'    => true,                                 
   'show_in_admin_status_list' => true,                                 
   'label_count'               => _n_noop( 'Orders delivered <span class="count">(%s)</span>', 'Custom Status <span class="count">(%s)</span>', 'woocommerce' ),                              
   );      
    return $order_statuses;  
    }
   return $order_statuses;
}

**Comment by sebas6691** [comment]
Die workaround heb ik idd ook gebruikt.
Verbaasd mij alleen dat de plugin zo gereleased is. Kan voor veel ondernemers even schrikken zijn als een groot deel van de orders missen.

**Comment by DarkAllMan** [comment]
https://github.com/myparcelnl/woocommerce/commit/1f4acd511b5f4c4538d67829313d327b1bb327bf
Ik heb dit bij mij uitgevoerd en dit heeft het probleem verholpen voor nu!

**Comment by robindelaater** [comment]
We hebben tijdelijk een fix zie: https://github.com/myparcelnl/woocommerce/commit/1f4acd511b5f4c4538d67829313d327b1bb327bf

We hebben een nieuw plan voor deze feature bedacht. We hebben deze bij ons gedocumenteerd, helaas kunnen we nog niet zeggen wanneer deze functionaliteit beschikbaar is. Voor nu zullen we deze status uitzetten binnen de plugin.

**Comment by keeslamper** [comment]
Robin, ook de fix helpt in veel gevallen niet. Wanneer verwachten jullie het probleem definitief opgelost te hebben?

**Comment by DarkAllMan** [comment]
De fix helpt bij mij wel. Zorg wel dat al je caches geleegd zijn etc. Bij mij zijn er geen orders meer naar die status veschoten.

**Comment by DarkAllMan** [comment]
@robindelaater Er is een update uit. Wat is er gewijzigd in deze update?

**Comment by Mariovisie** [comment]
@DarkAllMan 

Fix: Disable order status delivered
Fix: Package type not being recognized
Fix: migrate all package types in export defaults settings

Zo te zien is dus eigenlijk het probleem niet opgelost maar alleen tijdelijk uitgezet

**Comment by RichardPerdaan** [comment]
Beste @Mariovisie ,
We hebben een keuze gemaakt om de status `delivered` op een iets andere wijze te laten verlopen.
Helaas is hiervoor wel meer tijd nodig. Dit kunnen we op dit moment niet doen omdat we de plugin nu zo snel mogelijk stabiel willen krijgen. Hierdoor hebben wij ook de keuze gemaakt om het tijdelijk uit te zetten.

Er is een story bij ons aangemaakt zodat we dit niet zullen gaan vergeten.

**Comment by Mariovisie** [comment]
@RichardPerdaan , dank voor de terugkoppeling, Graag voortaan ook hier wat sneller, Wij doen ons best om jullie en onze klanten te helpen, maar zien dat via de updates wat er weer wat veranderd is zonder aankondiging hier. Beetje slordig vind ik zelf

**Comment by eyeinorange** [comment]
Bedankt dat de fix er nu is. Er vielen mij echter nog 2 dingen op (in volgorde van belangrijkheid):

- Vanuit mijn WordPress dashboard kon ik kiezen welk etiket van de 4 op het vel ik wil printen. Dat lukt nu niet meer!

- En ik moet nu invullen welk soort pakje maar dan moet ik ook nog het gewicht invullen. Dat is onlogisch. als ik brievenbuspakje zou kiezen zou het gewicht automatisch geselecteerd moeten zijn.

**Comment by RichardPerdaan** [comment]
@eyeinorange ,

Dank je wel voor jou feedback. Voor maandag staat er een nieuwe release gepland. 
In deze versie zullen deze problemen verholpen moeten zijn.

Onze testers zijn op dit moment bezig om alles zo goed mogelijk te testen. Zodra wij hiervan geen feedback ontvangen dan zullen we de plugin maandag live zetten.

**Comment by DarkAllMan** [comment]
We hebben geen release gezien gisteren. Is er een grote vertraging onstaan of kunnen we de release vandaag verwachten?

**Comment by RichardPerdaan** [comment]
@DarkAllMan ,
De release stond voor gisteren gepland, helaas waren niet alle testen succesvol. Hierdoor hebben wij de keuze gemaakt om een onderdeel uit de release te halen. Onze testers zijn op dit moment bezig om de plugin weer te testen. Zodra ik hier een goedkeuring van heb, zal ik de plugin gelijk live zetten.

Dit zijn de onderdelen die op dit moment klaar staan voor de release:
- Free_shipping gekoppeld aan pakket -> dan moet je ook de delivery options zien
- Als je een shipping method heb met flatrate:181 en de method geeft flatrate:18 dan moet je niet de delivery options niet zien 
- Error CRITICAL Uncaught TypeError: Return value of WCMP_Export::getShippingMethod()

**Comment by DarkAllMan** [comment]
Dank voor de update. Zodra de nieuwe versie is geinstalleerd, zal ik mijn bevindingen delen.

**Comment by eyeinorange** [comment]
En nu zie ik dat 4.06 er is.

4.0.6 (2020-10-14)
Fix: Free_shipping linked to package then you should also see the delivery options
Fix: If you have a shipping method with flatrate: 181 and the method gives flatrate: 18 then you should not see the delivery options
Fix: Error CRITICAL Uncaught TypeError: Return value of WCMP_Export::getShippingMethod()

**Comment by RichardPerdaan** [comment]
Gisteren is versie 4.0.6 live gezet.
Het probleem wat in de titel staat is dan ook verholpen.

Dit is dan ook de reden dat ik de issue zal sluiten. Mochten er andere problemen zijn dan wil ik jullie vragen om een nieuw issue aan te maken. Hierdoor zal het voor ons overzichtelijk blijven en kunnen we de problemen sneller oplossen.
