### ISSUE TITLE
Pakkettype tonen ipv 'details onder kolom bestemming

### ISSUE THREAD

**Issue by Nikitaverh** [myparcelnl/woocommerce#397]
Klant ziet graag in de nieuwe plugin het woord 'Details' weer vervangen worden door het pakkettype, zoals in de oudere versies zo was.

![WOO_ACTIE BESTEMMING](https://user-images.githubusercontent.com/54140706/94787858-234a8080-03d3-11eb-9967-810c88ab883c.jpg)

Nu staat er 'Details' ipv het pakkettype, wat minder overzichtelijk is!

**Comment by Nikitaverh** [comment]
00859531

**Comment by soedesh** [comment]
Case: 00859854

**Comment by DarkAllMan** [comment]
Idem hier!

**Comment by luissimo** [comment]
Idem
