### ISSUE TITLE
Streetname, house number & suffix not propperly loaded from user

### ISSUE THREAD

**Issue by jbrocker** [myparcelnl/woocommerce#399]
Hi,

When creating an order from the back-end, select a customer (with shipping address completely filled in in the profile, including streetname, housenumber and suffix). The order shipping address is loaded from the customer profile, all fields are prefilled except the streetname, housenumber and suffix. 

Cheers,
Jop

**Comment by RichardPerdaan** [comment]
This issue is solved with [v4.0.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.0.0)
