### ISSUE TITLE
Feature request: HS Code veldje als Custom Field

### ISSUE THREAD

**Issue by NikitaMyParcel** [myparcelnl/woocommerce#400]
_"Wij gebruiken ook de plugin WPML om onze website meertalig te maken.
In WPML kan ik Custom Fields selecteren die mee gekopieerd dienen te worden naar het vertaalde product met variaties. Custom Fields zoals prijs, voorraad etc.
Nu zou het ons heel veel werk schelen als de HS Code veld ook mee gekopieerd kan worden naar het vertaalde product. Echter lijkt het erop dat het HS Code veldje niet geregistreerd is als Custom Field en dus niet herkent wordt door WPML._

Zou het voor jullie mogelijk zijn om het HS Code veldje als Custom Field te registreren zodat WPML (en wellicht andere vertaal plugins) daar gebruik van kan maken?"_

**Comment by Nikitaverh** [comment]
00859520
