### ISSUE TITLE
PostNL Pickup Issue

### ISSUE THREAD

**Issue by DarkAllMan** [myparcelnl/woocommerce#401]
PostNL Pickup integratie werkt nog niet lekker of ik doe iets verkeerd.
Ik heb de optie ingeschakeld.
Extra kosten = 0.
De labels aangepast.
Ik zie nu op de checkout wel de opties en ik kan een pickup point selecteren. Maar het is allemaal niet duidelijk.
2 radio buttons die niet te selecteren zijn.
Als ik overigens voor afhalen kies bij mijn verzend opties, zou ik willen dat de pickup points verdwijnen.....
Zie http://test.lievelabels.nl
![afbeelding](https://user-images.githubusercontent.com/1582343/94917398-bf968500-04b0-11eb-812e-92c0021d1b04.png)

**Comment by Nikitaverh** [comment]
Goedemiddag!

Je kunt dit oplossebn doen door de verzendmethoden waarbij je de bezorgopties wel wilt tonen in het vak bij 'Pakket' te zetten in 'Standaard exportinstellingen'. En vervolgens de instelling 'Toon bij' op 'Verzendmethoden gekoppeld aan Pakket' te zetten.

Mocht je toch nog vragen hebben, kun je altijd contact opnemen met support@myparcel.nl! 

Fijne dag!

**Comment by DarkAllMan** [comment]
Ik begrijp idd het principe. Echter loop ik hier tegen de problemen van jullie plugin met Bolder Elements Table Rates.
Bij mij is een verzendklasse variabel via Tabel Rates.
Een klasse kan dus een briefpost zijn, zolang het aantal stuks kleiner is dan een bepaalde waarde. Wanneer deze waarde wordt overschreven, zal Table Rates het tarief van een pakket gaan berekenen. Echter, MyParcel ziet dit niet, die kijkt echt alleen naar de verzendklasse en niet naar de berekening.

**Comment by Nikitaverh** [comment]
@DarkAllMan Zou je hierover even contact op willen nemen met support@myparcel.nl?

Alvast bedankt!

**Comment by DarkAllMan** [comment]
Done!

**Comment by DarkAllMan** [comment]
Extra informatie. Ik heb contact opgenomen met Bolder Elements voor het toevoegen van meta data aan de order op basis van de table rates. Dan zou ik een custom field kunnen gebruiken waarin ik specifieer wat voor verzendtype het is.
MyParcel zou dit veld kunnen gebruiken...
