### ISSUE TITLE
Bug: saving package types does not work properly

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#403]
When I want to save the package types it looks like every type is using the same field.
**Video:** https://monosnap.com/file/vX9hlBdvUZwdDZ97hefUx9GQABmPDT

**Comment by DarkAllMan** [comment]
I confirm this behaviour

**Comment by RichardPerdaan** [comment]
We are currently looking at this problem.

**Comment by RichardPerdaan** [comment]
Fixed in version 4.1.4 of the MyParcel plugin
