### ISSUE TITLE
 BBP voor Belgie wordt geselecteerd (adhv verzendklasse) niet meer te wijzigen

### ISSUE THREAD

**Issue by NikitaMyParcel** [myparcelnl/woocommerce#405]
Wanneer een product in de verzendklasse gekoppeld is aan brievenbuspakje en de zending moet naar België, blijft het een pakkettype brievenbuspakje. Dit is niet aan te passen en levert wel een error op. 

<img width="1260" alt="Bestellingen ‹ MyParcel — WordPress 2020-10-05 15-13-32" src="https://user-images.githubusercontent.com/54140706/95088430-405cb780-0723-11eb-8859-9d3cfd974c81.png">

Ook is er een afhaallocatie aan gekoppeld?

**Comment by Nikitaverh** [comment]
00863351

**Comment by RichardPerdaan** [comment]
Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin. De update is vanmorgen live gezet en kan via de reguliere update worden geïnstalleerd.
