### ISSUE TITLE
Batch export: all orders fail if one orders contains an error

### ISSUE THREAD

**Issue by kdesigns** [myparcelnl/woocommerce#408]
I ship to different countries (theoretically all countries in the world).

When I process orders I usually select all orders on the page, say 30 orders at once.
When I click the export to MyParcel button, I often get an error notification because one of the 30 selected orders has an error in the address (for example) or because it's missing a product weight (can be different issues).

The error would read something like "Product missing Weight".
However, the error message does not tell me which order/product is missing the weight or has has problem with the address.

Also, none of the selected (30) orders are actually exported to MyParcel.

I have to now keep selecting less orders at a time to try and find the order that is generating the error.

This can take hours when I have to process a couple hundred orders.

Using latest MyParcel plugin at the time (4.0.5) and Wordpress (5.5.1) and WooCommerce (4.5.2)

**Comment by DarkAllMan** [comment]
Also, batch print fails, if selected orders contain a non exported order.....
I think it should print all possible!

**Comment by RichardPerdaan** [comment]
Currently we made this functionality in Magento, we look which orders are possible to export. These will also be exported and printed. There is also a clear error to see why a specific order can not been exported.

Would this functionality be the solution for you when we implement this in WooCommerce?

**Comment by DarkAllMan** [comment]
For me that would suffice, I think.

**Comment by TimBlom** [comment]
Case 00869711 is having the same issues. Wish to export all shipments except the one with the error.
Client says this worked in older versions.

**Comment by TimBlom** [comment]
Case 00868085 as well

**Comment by joelvdvoort** [comment]
I would love to see the proposal by @RichardPerdaan implemented as well. To add; It would be beneficial if the error was more specific too. Currently you get "Unexpected error" or something along those lines. This confuses less technical users as they're not sure where to look where this happens. An error message like "Failed to export: please check the order's address" would be better in my opinion. When multiple orders have errors maybe even display all order numbers that contain errors.

**Comment by TimBlom** [comment]
Case 00953314 as well

**Comment by RichardPerdaan** [comment]
This has been fixed in version [4.3.1] (https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1) of the MyParcel WooCommerce plugin.
