### ISSUE TITLE
Age check in default exports should be ignored for non-NL shipments

### ISSUE THREAD

**Issue by adem-demir** [myparcelnl/woocommerce#409]
+18 check is enabled by default in product. This need to be set to disabled

**Comment by RichardPerdaan** [comment]
Dit is bij wereld zendingen

**Comment by EdieLemoine** [comment]
This happens when you have age check enabled in the default export settings. This option is not allowed for shipments outside the Netherlands but is still applied when exporting.

**Comment by RichardPerdaan** [comment]
This has been fixed in version [4.3.1] (https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1) of the MyParcel WooCommerce plugin
