### ISSUE TITLE
WooCommerce PDF Invoices & Packing Slips Premium Templates compatibility

### ISSUE THREAD

**Issue by Spreeuw** [myparcelnl/woocommerce#412]
The `{{myparcel_delivery_date}}` placeholder stopped working after the 4.0 upgrade, while the other three placeholders (`{{myparcel_delivery_options}}`, `{{myparcel_tracktrace}}` & `{{myparcel_tracktrace_links}}`) still work.

**Comment by RichardPerdaan** [comment]
Beste @Spreeuw,

Op 8 oct heb je een PR aangemaakt. Is het probleem nog steeds aanwezig of kan de issue gelosten worden?

**Comment by Spreeuw** [comment]
Je hebt er zelf een variant op gemaakt: https://github.com/myparcelnl/woocommerce/pull/411#issuecomment-732021697
Daar waren nog wat problemen mee, maar ik geloof dat die inmiddels zijn verholpen. Omdat er bij elke release functies worden gewijzigd weet ik niet of dit bij de volgende release nog steeds werkt.
