### ISSUE TITLE
PostNL Pickup problemen

### ISSUE THREAD

**Issue by DarkAllMan** [myparcelnl/woocommerce#419]
In onze webshop wil ik WEL gebruik maken van Pickup Points, maar niet van afleverdagen.
https://test.lievelabels.nl/afrekenen/

![afbeelding](https://user-images.githubusercontent.com/1582343/95990370-b51ea880-0e2b-11eb-9d1a-9c695eeadcbe.png)
![afbeelding](https://user-images.githubusercontent.com/1582343/95990427-c9fb3c00-0e2b-11eb-8d15-15350b2440eb.png)

In deze configuratie is het voor de klant niet duidelijk wanneer ze hebben gekozen voor normale zending of een pickup point.
![afbeelding](https://user-images.githubusercontent.com/1582343/95991551-30cd2500-0e2d-11eb-823b-37f0bf2e5a48.png)

Is het mogelijk om een radio button te maken voor Reguliere zending of Pickup point?

Tevens zie ik na het plaatsen van een test bestelling zonder pickup point alsnog dit in de email staan:
MyParcel zending:
Pickup, dinsdag 20-10

Eventueel wil ik het best via een teamsmeeting toelichten/laten zien of een admin account op mijn testomgeving creëren.

**Comment by DarkAllMan** [comment]
Deze is dus helaas nog niet opgenomen in de release van vandaag?

**Comment by DarkAllMan** [comment]
Is deze nu wel opgenomen in de release van vandaag?

**Comment by DarkAllMan** [comment]
Getest, maar helaas krijg ik het nog steeds niet voor elkaar om leveringen thuis of bij pickuppoints te leveren zonder dat je een specifieke leverdag moet kiezen

**Comment by Mitchell-MyParcel** [comment]
@DarkAllMan : Als ik het goed begrijp wil je dus dat klanten simpelweg kunnen kiezen tussen reguliere bezorging zonder dagkeuze of afhalen. De aanname is dan nog wel dat je de reguliere zending wel verwerkt met onze plugin. Bedoel je zoals op onderstaande screenshot?
<img width="414" alt="Screenshot 2021-01-25 at 16 52 47" src="https://user-images.githubusercontent.com/69574208/105729859-ef6d0b00-5f2d-11eb-9d89-77f72136bd71.png">

Als bovenstaande inderdaad is zoals je het wilt dan kun je dat bereiken door in de PostNL tab deze setting op 0 te zetten: Delivery days window/Aantal dagen die je wilt tonen. Je moet dan wel de delivery options activeren. In bovenstaand voorbeeld heb ik ook ochtendlevering, avondbezorging, handtekening voor ontvangst en alleen huisadres gedeactiveerd. 

Ik gebruik hiervoor v4.2.0, maar dit moet ook in de huidige stabiele versie al zo werken. Mocht je toch v4.2.0 willen gebruiken dan raden we je wel aan om deze eerst te testen op een veilige (test) omgeving. Graag eerst de plugin de-installeren en daarna de .zip handmatig installeren.

Je kunt de .zip hier vinden samen met de release notes: https://github.com/myparcelnl/woocommerce/releases/tag/v4.2.0

**Comment by DarkAllMan** [comment]
Dat is exact wat ik wilde! Op mijn test site zie ik alleen nog de verzendkosten erachter staan (ex btw)
https://test.lievelabels.nl/afrekenen/
Moet ik dat nog ergens aanpassen?

**Comment by Mitchell-MyParcel** [comment]
@DarkAllMan: Top! Wat betreft de verzendkosten, die zijn niet te verbergen. We krijgen daar wel meer feedback over dus we gaan even kijken of we daar nog iets mee kunnen. De BTW is wel iets waar we op korte termijn wat voor gaan releasen. Zie hier de PR die daarvoor openstaat:

https://github.com/myparcelnl/woocommerce/pull/547

Zoals het er nu naar uitziet gaan we deze toevoegen aan een nieuwe versie van de pre-release.

**Comment by DarkAllMan** [comment]
Hoi Mitchell
Wanneer verwachten jullie de pre-release update?
Het verbergen van de prijzen, indien er geen meerprijs wordt berekend is echt wel een must. Zolang dat niet geimplementeerd is, kan ik eigenlijk niet met een gerust hart deze opties inschakelen. Dan ga ik teveel vragen krijgen.

**Comment by Mitchell-MyParcel** [comment]
@DarkAllMan De pre-release verwacht ik deze week te updaten met o.a. de BTW fix. Zodat daar geen verwarring over bestaat, een aanpassing aan de manier waarop we de prijzen tonen, zit afgezien van de BTW fix niet in die update.

**Comment by RichardPerdaan** [comment]
@DarkAllMan ,
Vandaag is versie 4.3.1 live gezet. Met deze versie is het mogelijk om een meerprijs/totaalprijs in te stellen. Zodra je meerprijs heb geselecteerd, zou je de prijzen niet meer moeten zien.
