### ISSUE TITLE
Print label werkt niet

### ISSUE THREAD

**Issue by DarkAllMan** [myparcelnl/woocommerce#421]
Single print of Bulk print werkt niet.  Opent een nieuw venster met JSON
![afbeelding](https://user-images.githubusercontent.com/1582343/96094496-b6081680-0ecd-11eb-9da6-268dfd2d78ce.png)

**Comment by RichardPerdaan** [comment]
Beste @DarkAllMan ,

Er lijkt iets verkeerd te gaan bij ons in het hoofdsysteem, we zijn ermee bezig.
Zodra het opgelost is, laat ik je het weten.

**Comment by DarkAllMan** [comment]
@RichardPerdaan Dit lijkt nu weer in orde! Ik krijg weer netjes een PDF terug.

**Comment by RichardPerdaan** [comment]
Beste @DarkAllMan ,
Goed om te horen, we hadden snel door wat er fout ging.
