### ISSUE TITLE
Bezorgopties positie toevoegen

### ISSUE THREAD

**Issue by DarkAllMan** [myparcelnl/woocommerce#422]
Ik zou veel liever de Bezorgopties onder de Woocommerce subtotalen zien.
`woocommerce_review_order_before_payment`

Zie hier een voorbeeld:
https://test.lievelabels.nl/afrekenen/

![afbeelding](https://user-images.githubusercontent.com/1582343/96100316-89a3c880-0ed4-11eb-9588-d6f9df81c856.png)

**Comment by Mitchell-MyParcel** [comment]
Will be added in 4.0.7

**Comment by DarkAllMan** [comment]
When is a next release expected?

**Comment by RichardPerdaan** [comment]
Hi @DarkAllMan ,
Today we have a new version released. This issue has been included in this version (4.1.0). Hereby I also close the issue.
