### ISSUE TITLE
Tonen pick up point in bevestiging mail

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#425]
In versie 4.0.6 kunnen postpunten zichtbaar gemaakt worden door 'Aantal dagen die je wilt tonen' in de checkout instellingen in te schakelen, maar de gegevens van het punt worden niet in de bevestigingsmail gezet:

![image](https://user-images.githubusercontent.com/22811561/96252610-854ddd00-0fb2-11eb-89e5-1b46c97c6645.png)

In eerdere versies werkte dit wél.

**Comment by Amelandbor** [comment]
Even ter bevestiging hoe dit werkt in 3.2.0

![chrome_2020-11-20_09-37-47](https://user-images.githubusercontent.com/457756/99778637-3ac10280-2b14-11eb-81c4-9cf1dc911370.png)

In de oude code zit het op het einde van de functie `show_order_delivery_options`

**Comment by phemels** [comment]
Ook "MyParcel zending" aanpassen aan "Afhalen bij PostNL" a.u.b. anders is het verwarrend.

**Comment by RichardPerdaan** [comment]
Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin
