### ISSUE TITLE
MyParcel verzendopties verschijnt niet bij ontbreken postcode Winkelmand

### ISSUE THREAD

**Issue by Sebvandenbrink** [myparcelnl/woocommerce#428]
Een tweede bug vandaag is het volledig ontbreken van de MyParcel verzendopties bij het Afrekenen wanneer een postcode/plaats ontbreekt in het Winkelmandje. Ook na het invullen van de adresgegevens verschijnen de opties niet. Het formulier is wel af te ronden en de bestelling is af te ronden, al ziet de gebruiker geen opties (bijv. afhalen of laten bezorgen). 

- custom CSS verwijderen helpt niet
- wanneer het Winkelmandje al een postcode/plaats is ingevuld, dan verschijnt de box wel
- PostcodeChecker plugin verwijderen verhelpt het niet

Screenshot zoals verwacht: https://studiolegenda.nl/github/screenshot-mp-bug2.png
Screenshot bug: https://studiolegenda.nl/github/screenshot-mp-ontbrekend.png

**Comment by adem-demir** [comment]
@Sebvandenbrink ten eerste sorry voor de late reactie. Staan de verzendklasse wel goed ingesteld? Meestal krijg je zo'n error wanneer dit niet goed is ingesteld. Je zou mij ook een mail kunnen sturen, zodat 1 van de support collega;'s mee kunnen kijken.

**Comment by Sebvandenbrink** [comment]
Ik heb daar niets aan veranderd de afgelopen maanden. Is er iets veranderd in een update? 

Zo is het ingesteld: https://www.studiolegenda.nl/github/screenshot-mp-verzendklassen.png
Momenteel zijn er alleen pakket-producten.

**Comment by RichardPerdaan** [comment]
Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin. De update is vanmorgen live gezet en kan via de reguliere update worden geïnstalleerd.
