### ISSUE TITLE
Verschil in prijs bezorgopties checkout

### ISSUE THREAD

**Issue by NikitaMyParcel** [myparcelnl/woocommerce#429]
In de checkout wordt de prijs ex btw weergegeven en in de totaalprijs opsomming zie je de prijs met btw staan.

Dit zorgt voor verwarring. 

<img width="1301" alt="Checkout – MyParcel 2020-10-21 16-41-29" src="https://user-images.githubusercontent.com/54140706/96736000-71dcb080-13bc-11eb-9bfc-6b462df83586.png">

**Comment by TimBlom** [comment]
Ook in case 00902967

**Comment by TimBlom** [comment]
Ook in case 00957375

**Comment by NikitaMyParcel** [comment]
00894099

**Comment by EdieLemoine** [comment]
Fixed in 4.2.1
