### ISSUE TITLE
Meerdere labels per zending buiten NL aanmaken vanuit plugin

### ISSUE THREAD

**Issue by NikitaMyParcel** [myparcelnl/woocommerce#431]
In plugin versie 3.2.1 was het mogelijk om meerdere labels aan te maken voor 1 zending buiten NL & BE, in de nieuwe versie is dit niet meer mogelijk. Dit is wel gewenst.

**Comment by Nikitaverh** [comment]
00875316

**Comment by Mitchell-MyParcel** [comment]
Results in this error:

Error in MyParcel API request: data.shipments[0].options.package_type - data.shipments[0].options.package_type multi collo shipments only supported in the following countries: NL, BE - Shipment validation error Url: https://api.myparcel.nl/shipments Request: {"data":{"shipments":[{"recipient":{"cc":"DE","person":"xxxxxxx","postal_code":"xxxxxx","city":"xxxxx","email":"xxxxx","phone":"xxxxxx","street":"xxxxxxxx","street_additional_info":"xxxxxxx"},"carrier":1,"reference_identifier":"xxxxx","options":{"package_type":1,"label_description":"xxxxxxxxxxxxx","only_recipient":1,"signature":1,"return":0,"large_format":1,"delivery_date":"2020-10-21 15:04:03","delivery_type":2},"general_settings":{"save_recipient_address":1,"disable_auto_detect_pickup":0},"physical_properties":{"weight":6015},"secondary_shipments":

**Comment by RichardPerdaan** [comment]
Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin. De update is vanmorgen live gezet en kan via de reguliere update worden geïnstalleerd.
