### ISSUE TITLE
Urgent! Alleen afhalen zichtbaar in checkout 

### ISSUE THREAD

**Issue by outlandweb-ecom** [myparcelnl/woocommerce#433]
Na de meest recente update (4.0.6) is er iets niet goed gegaan, het is niet meer mogelijk om toeslagen in te stellen. Alle opties worden nu getoond als gratis. Er zijn hierdoor 30 bestellingen automatisch naar het dichtstbijzijnde afhaalpunt bij het klantadres bezorgd. De klant had geen andere optie tijdens het afrekenen.

<img width="839" alt="Screenshot 2020-10-22 at 09 26 15" src="https://user-images.githubusercontent.com/15428631/96838856-b150de80-1448-11eb-89b8-ca44d50b40fa.png">

Ook viel het op dat in de plugin instellingen geen toeslagen ingesteld meer kunnen worden waardoor alle opties gratis zijn. 
<img width="855" alt="Screenshot 2020-10-22 at 09 22 41" src="https://user-images.githubusercontent.com/15428631/96838575-54552880-1448-11eb-9a6b-de2d54d8e016.png">

Hoe lossen we dit op? We hebben nu alles uitstaan qua bezorgopties in checkout. 

Voor deze update zijn er tijdens drie kleinere versies ook al verscheidende dingen fout gegaan bij meerdere van onze opdrachtgevers.

**Comment by EdieLemoine** [comment]
Goedemorgen,

De instellingen voor de PostNL bezorgopties staan onder PostNL instellingen. Kun je kijken of dat wel werkt zoals je verwacht? De verplaatste settings zouden allemaal gemigreerd moeten zijn vanuit de oude versie van de plugin, maar mogelijk is er daar toch iets misgegaan.

**Comment by outlandweb-ecom** [comment]
Goedemorgen Edie,

Helaas niet inderdaad, ik zie nu dat je naar het PostNL tabje moet, daar de optie opnieuw moet aanzetten, en dan ook nog eens de optie Activeer PostNL levering moet aanzetten om alle onderliggende mogelijkheden te zien.
Daar waren de prijzen inderdaad leeg, en keuzes niet onthouden.

Afhaalpunt gek genoeg was dus wel gemigreerd.

Voor nu werkt het zo weer goed en weten wij wat te doen. Dank voor de snelle reactie.

**Comment by EdieLemoine** [comment]
Fijn dat het zo is opgelost! 

Dit zou natuurlijk niet nodig moeten zijn, het moet gewoon overgezet worden. Dit nemen we mee in de eerstvolgende release, bedankt voor het melden.

**Comment by outlandweb-ecom** [comment]
Ok, super, weten we dat voor de andere shops.

**Comment by EdieLemoine** [comment]
Er komt eerst nog een 4.0.7 met een grote update (#430), deze fix (#438) gaat toch in de release daarna.
