### ISSUE TITLE
PostNL-plugin: Track en trace in email werkt niet bij automatische orderstatus

### ISSUE THREAD

**Issue by NikitaMyParcel** [myparcelnl/woocommerce#435]
PostNL track en trace mail issue: 
Barcode wordt niet in mail gezet wanneer track en trace in email aan staat en de orderstatus automatisch wordt aangepast naar Afgerond, wordt de barcode niet meegenomen in de mail 'Bestelling afgerond en/of verzonden'. 

Wanneer je de automatische orderstatus uitschakelt en de mail handmatig verstuurt of de status na export handmatig aanpast naar afgerond, dan wordt de barcode wel toegevoegd aan de mail.

**Comment by joelvdvoort** [comment]
Hoi,

Ik wil bij deze aangeven dat ik het probleem ook ervaar.

**Comment by Mitchell-MyParcel** [comment]
@joelvdvoort : Dit is gefixed in v4.2.0. We hebben deze versie uiteraard zelf uitvoerig getest maar willen deze nu ook met een aantal klanten testen voordat we deze versie breed beschikbaar stellen. Mocht je alvast gebruik willen maken van v4.2.0 dan raden we je aan om dit te doen op een veilige (test) omgeving. Om hiervan gebruik te maken de-installeer je de plug-in en installeer je handmatig de .zip die je hier kunt vinden: https://github.com/myparcelnl/woocommerce/releases/tag/v4.2.0

**Comment by RichardPerdaan** [comment]
Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin. De update is vanmorgen live gezet en kan via de reguliere update worden geïnstalleerd.
