### ISSUE TITLE
Afleverdagen kunnen niet worden gewijzigd

### ISSUE THREAD

**Issue by Nikitaverh** [myparcelnl/woocommerce#437]
Afleverdagen niet goed op te slaan, hierdoor verkeerde data in checkout:

[https://monosnap.com/file/5T133NsX8hlWVzYYe3qVegAINWrFov]

**Comment by Nikitaverh** [comment]
00867839

**Comment by Mitchell-MyParcel** [comment]
Duplicate of #402 hence closed
