### ISSUE TITLE
Variabel product op een juiste manier exporteren 

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#440]
Binnen WooCommerce kan je een variabel product aanmaken.
Hierin is de HS-code wel te zien, maar bij een export wordt
zowel de HS-code als het land van oorsprong uit de standaard exportinstellingen gehaald.

**Comment by TimBlom** [comment]
Case

**Comment by Mitchell-MyParcel** [comment]
@TimBlom : Dit lijkt in de laatste versie gefixed te zijn. Ik maak van het toevoegen van land van oorsprong voor een variabel product een feature request.

**Comment by RichardPerdaan** [comment]
Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin. De update is vanmorgen live gezet en kan via de reguliere update worden geïnstalleerd.
