### ISSUE TITLE
Zending type niet meer zichtbaar in besteloverzicht

### ISSUE THREAD

**Issue by joelvdvoort** [myparcelnl/woocommerce#441]
Sinds de overgang naar versie 4.x is de type zending niet meer zichtbaar in het order overzicht. Voorheen zag je in het selectie knopje welke zending type voor de order geselecteerd was. 

Myparcel 3.2.1
![myparcel3](https://user-images.githubusercontent.com/73742511/97779480-a26fd780-1b7e-11eb-9a1f-5d74b77cb730.png)

Myparcel 4.x
![myparcel4](https://user-images.githubusercontent.com/73742511/97779478-a1d74100-1b7e-11eb-9497-6fe2582f43ab.png)

In onze shop wordt standaard het type pakketzending gekoppeld en koppelen we later de brievenbus zendingen met de hand. Voorheen was het overzichtelijker welke zending al op de juiste type ingesteld was.

**Comment by EdieLemoine** [comment]
Wordt opgelost in 4.0.7 (#430)
