### ISSUE TITLE
'Bewaar barcode in een notitie' werkt dubbel bij 'exporteren en printen' en niet bij export vanuit order

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#443]
Versie 4.0.6

Wanneer je gebruik maakt van de optie 'Bewaar barcode in een notitie' wordt de barcode dubbel in de notities geplaatst wanneer je gebruik maakt van de bulk actie 'exporteren en printen'. Als je exporteert en print vanuit de order zelf, werkt deze functie niet.

**Comment by TimBlom** [comment]
Wanneer je weer opnieuw het label download (nadat 'exporteren en printen' gebruikt is) wordt de barcode weer dubbel toegevoegd.

**Comment by snelweg** [comment]
sterker nog, ik heb soms wel drie keer die notitie staan bij een order. Dit is zelfs nog voordat ik iets uitgeprint heb.

**Comment by snelweg** [comment]
Mooi dat er een fix is (ik neem aan dat deze uitgebreid getest is!), maar jammer dat er dan weer geen release is.
Huidige en meest recente versie is 4.1.3 en deze is al weer 10 dagen oud.


v4.1.3
Latest
10 days ago
