### ISSUE TITLE
No Checkout options when Elementor Pro is active

### ISSUE THREAD

**Issue by TeunSmit** [myparcelnl/woocommerce#444]
**Describe the bug**
When using Elementor Pro to design the checkout, you can't see any of the PostNL checkout options. When Elementor Pro is active you can still see the checkout JS, but where the actual options should be it is empty. 

**Details**
 - WordPress version: 5.5.3
 - WooCommerce version: 4.6.1
 - WooCommerce MyParcel/PostNL version: 3.1.7
 - Theme: Astra 2.6.0

**Comment by RichardPerdaan** [comment]
Ik heb deze functionaliteit getest met de laatste versie van de MyParcel plugin. Wat mij is opgevallen is dat het probleem sinds versie [v4.2.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.2.0) opgelost is
