### ISSUE TITLE
As a client I want the MyParcel fields to be filled in when I manually create an order.

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#445]
As a client I want the MyParcel fields to be filled in when I manually create an order.

[Screen record of steps](https://monosnap.com/file/vWgW76XC3nUfWVh8zypAHm2rbeFYBg)

**Comment by TimBlom** [comment]
###

**Comment by TimBlom** [comment]
Also PostNL-plugin

**Comment by Mitchell-MyParcel** [comment]
Duplicate of #399
