### ISSUE TITLE
PHP Fatal error: Uncaught TypeError: Return value of WCMP_Export::getPackageTypeFromOrder() must be of the type string

### ISSUE THREAD

**Issue by DarkAllMan** [myparcelnl/woocommerce#448]
**Describe the bug**
In my test environment I get errors
`Got error 'PHP message: PHP Fatal error: Uncaught TypeError: Return value of WCMP_Export::getPackageTypeFromOrder() must be of the type string, null returned in /wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmp-export.php:900
Stack trace:\n#0 /wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmypa-admin.php(244): WCMP_Export->getPackageTypeFromOrder()
#1 /wp-includes/class-wp-hook.php(287): WCMYPA_Admin->showMyParcelSettings()
#2 /wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#3 /wp-includes/plugin.php(478): WP_Hook->do_action()
#4 /wp-content/plugins/woocommerce/includes/admin/list-tables/class-wc-admin-list-table-orders.php(311): do_action()
#5 /var/www/vhosts/..', referer: https://xyz.nl/wp-admin/admin.php?page=wcmp_settings&tab=checkout`

**Steps to reproduce this behaviour**
1. Go to wp-admin/edit.php?post_type=shop_order
In the last column (actions) some order show:
`Er heeft zich een kritieke fout voorgedaan op je site. 

**Expected behaviour**
Show action buttons

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/1582343/98794615-8afbde80-2409-11eb-96ea-0fb8fef3bca5.png)

**Details**
 - Latest
 - Latest
 - Latest
 - Avada

Access to dev site is possible. Just contact me.

**Comment by RichardPerdaan** [comment]
Hi @DarkAllMan ,

I have sent you an email for access to your dev environment.
