### ISSUE TITLE
Elke keer wordt er bij de digitale zegel 2 keer porto gerekend ook al selecteer ik duidelijk 0-20 gram.

### ISSUE THREAD

**Issue by snelweg** [myparcelnl/woocommerce#449]
Elke keer wordt er bij de digitale zegel 2 keer porto gerekend ook al selecteer ik duidelijk 0-20 gram.

![myparcel_1](https://user-images.githubusercontent.com/1257901/98801164-b387d680-2411-11eb-9b6c-87b50cda6920.png)

`

Versie van WooCommerce: |   | 4.7.0
-- | -- | --
WooCommerce REST API-pakket: |   | 4.7.0 /home//domains/.nl/public_html/wp-content/plugins/woocommerce/includes
WooCommerce Blocks-pakket: |   | 3.6.0 /home//domains/.nl/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/
Action Scheduler-pakket: |   | 3.1.6 /home//domains/.nl/public_html/wp-content/plugins/woocommerce/packages/action-scheduler
WooCommerce Admin-pakket: |   | 1.6.3 /home//domains/.nl/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin
Logmap beschrijfbaar: |   | /home//domains/.nl/public_html/wp-content/uploads/wc-logs/
Versie van WordPress: |   | 5.5.3
WordPress multisite: |   | –
WordPress geheugenlimiet: |   | 2 GB
WordPress debug-modus: |   | –
WordPress cron: |   | –
Taal: |   | nl_NL

`

**Comment by snelweg** [comment]
Ik heb dit maar extra gemeld op de Wordpress plugin site. Hier krijg ik dus geen reactie.
https://wordpress.org/support/?post_type=topic&p=13654427#new-topic-0

Wel een drama hoor die 'support' van MyParcel, via e-mail en de website heb ik  maar opgegeven om hulp te vragen, daar gebeurt helemaal nooit iets.

**Comment by Nikitaverh** [comment]
Goedemiddag, 
Zou je hierover contact willen opnemen met de Support van MyParcel? Je kunt bellen of mailen naar support@myparcel.nl. 
Fijne middag!

**Comment by snelweg** [comment]
> Goedemiddag,
> Zou je hierover contact willen opnemen met de Support van MyParcel? Je kunt bellen of mailen naar [support@myparcel.nl](mailto:support@myparcel.nl).
> Fijne middag!

waarom? Die support is waardeloos en een totale tijdsverspilling. Trouwens dit is inderdaad gemeld via jullie web-site, nooit reactie op gehad. MyParcel staat wel mooi voor schut op deze manier. Ik dacht dat jullie een professionele organisatie waren.

navraag bij collega's leert dat ik niet de enige ben die last heeft van de fouten die er steeds weer in sluipen bij de plugin sinds de originele ontwikkelaar er niet meer is. Flink balen dit, kost me alleen maar tijd en ergernis.

**Comment by RichardPerdaan** [comment]
Beste @snelweg,
Vorige week is er bij development een story aangemaakt en het is met de product owner besproken.
Doordat wij gebruik maken van de twee wekelijkse sprints, zal er gekeken worden wanneer het probleem het beste opgepakt kan worden.

Ik heb bij ons in het systeem gekeken en op alle berichten die bij ons binnen zijn gekomen via de mail, website en telefoon zijn nettjes afgehandeld en er is overal op gereageerd.

**Comment by snelweg** [comment]
jeetje, wat een rare woorden. Geen wonder dat het steeds mis gaat.
Dus wij als gebruikers blijven  met problemen zitten totdat jullie weer eens een sprintje gaan trekken? Ik zou er naast sarcastisch ook nog eens erg boos om kunnen worden. Waarom fixen en testen jullie niet gewoon voordat jullie de plugin vrijgeven. Je zal vast wel een harnas kunnen vinden waar je middels scrum en continuous integration van sprint naar sprint kunt zwalken. De kwaliteit zoals deze de laatste paar releases was is beschamend en zou niet mogen voorkomen bij een bedrijf als het jouwe.

En nee, er is niet op alle berichten adequaat gereageerd. Hoe je daar bij komt is mij een raadsel. 

Geen reactie graag, bewaar je energie maar voor je volgende spint poging.

**Comment by snelweg** [comment]
Ohja, wanneer wordt dit probleem opgelost? Want daar ga je dus weer niet op in.

**Comment by Mitchell-MyParcel** [comment]
This is fixed in the latest version (v4.1.4.).
