### ISSUE TITLE
kritieke fout  type E_ERROR werd veroorzaakt op regelnummer 900 van het bestand /home/x/domains/x.nl/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmp-export.php.

### ISSUE THREAD

**Issue by snelweg** [myparcelnl/woocommerce#452]
```
Er heeft zich een kritieke fout voorgedaan op je site. Controleer je inbox van je beheerder e-mailadres voor instructies.

Meer informatie over probleemoplossing in WordPress

Sinds WordPress 5.2 is er een ingebouwde functie die herkent wanneer een plugin of thema een fatale fout veroorzaakt op je site en die je op de hoogte stelt met deze automatische e-mail.

In dit geval heeft WordPress een probleem gevonden met één van je plugins: WooCommerce MyParcel.

```
Wat is dat toch met die ontwikkeling daar bij jullie, testen jullie wel eens iets?????????

`WordPress versie 5.5.3
Huidig thema: Storefront child (versie 2.2.8)
Huidige plugin: WooCommerce MyParcel (versie 4.1.0)
PHP versie 7.4.10

Foutdetails
===========
Een fout van het type E_ERROR werd veroorzaakt op regelnummer 900 van het bestand /home/x/domains/x.nl/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmp-export.php. Foutmelding: Uncaught TypeError: Return value of WCMP_Export::getPackageTypeFromOrder() must be of the type string, null returned in /home/x/domains/x.nl/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmp-export.php:900
Stack trace:
#0 /home/x/domains/x.nl/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmypa-admin.php(244): WCMP_Export->getPackageTypeFromOrder(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#1 /home/x/domains/x.nl/public_html/wp-includes/class-wp-hook.php(287): WCMYPA_Admin->showMyParcelSettings(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#2 /home/x/domains/x.nl/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 /home/x/domains/x.nl/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /home/x/domains/x.nl/public_html/wp-content/plugins/woocommerce/includes/admin/list-tables/clas`

**Comment by RichardPerdaan** [comment]
Beste @snelweg ,

De plugins die wij live zetten, worden door minimaal 3 personen nagekeken, daarbij hebben wij een regressie document die wij hanteren om heel de plugin te testen.

Het probleem wat je heb gemeld, is opgelost in versie 4.1.1 van de MyParcel WooCommerce versie.

Ik sluit hierbij dan ook de issue

**Comment by snelweg** [comment]
Heb toch erge twijfels over jullie release methodologie. Dit is niet de eerste keer dat er een dikke fout in een net opgeleverde plugin zit. 
Hopelijk komt er snel verbetering in de kwaliteit van de opgeleverde plugins,
