### ISSUE TITLE
 Verkeerd gewicht DPZ

### ISSUE THREAD

**Issue by Nikitaverh** [myparcelnl/woocommerce#455]
Bij het veranderen van pakkettype naar digitale postzegel wordt niet het juiste gewicht gekozen aan de hand van het gewicht van de bestelling. 

<img width="410" alt="Bestelling bewerken ‹ MyParcel — WordPress 2020-11-12 13-12-14" src="https://user-images.githubusercontent.com/54140706/98947135-1f8f3b00-24f5-11eb-817d-e17b5352b18f.png">

Reproduceerbaar door een bestelling te plaatsen en het pakkettype te wijzigen naar DPZ en het gewicht leeg te laten. Na opslaan verandert het gewicht naar 350-2000 in plaats van het gewenste gewicht.

**Comment by RichardPerdaan** [comment]
Fixed in version 4.1.4 of the MyParcel plugin
