### ISSUE TITLE
In version 4.1.2. pakjegemak still always visable

### ISSUE THREAD

**Issue by phemels** [myparcelnl/woocommerce#457]
Probleem:
PakjeGemak optie altijd zichtbaar in de checkout,

Oorzaak:
de MyParcel PakjeGemak reageerd alleen op de shippingclass/verzendklasse “Vast Tarief”.
Het probleem is dat “Vast Tarief” wordt gebruikt door WooCommerce voor alle producten die GEEN verzendklasse hebben.
Echter als verzendklasse “Vast Tarief” is toegevoegd bij: Standaard exportinstellingen -> Pakkettype -> Pakket Dan is er bij de checkout altijd de optie PakjeGemak zichtbaar.

![image](https://user-images.githubusercontent.com/29940263/99040906-421f6380-258a-11eb-9e2e-b6c5afe059dc.png)

Voeg ik shippingclass/verzendklasse “Vast Tarief” niet toe bij Pakket dan is de PakjeGemak optie nooit zichtbaar in de checkout!!

![image](https://user-images.githubusercontent.com/29940263/99041229-d5f12f80-258a-11eb-9f3a-3efe0f6545d7.png)

Hopelijk hebben jullie hier iets aan en snel een FIX.

P.S. ik gebruik geen Digitale postzegel maar er moet iets geselecteerd zijn, leeg laten kan niet. Waarom?

**Comment by phemels** [comment]
M.b.v. Soedesh de "namen" van de verzenklassen aangepast, blijkbaar is dit een must.

Echter op de live site werkte het nog steeds niet :(

Maar na blijven testen heb ik een probleem ontdekt, de MyParcel checkout opties worden alleen getoond voor ingelogde gebruikers!!
Vandaar dat het bij eerst steeds niet werkte, ik teste namelijk NIET ingelogd in Edge. 
Log ik in dan werkt het, maar dit lijkt me niet de bedoeling.

**Comment by RichardPerdaan** [comment]
Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin. De update is vanmorgen live gezet en kan via de reguliere update worden geïnstalleerd.
