### ISSUE TITLE
4.1.3. Link 3S code in backend status popup doesn't work

### ISSUE THREAD

**Issue by phemels** [myparcelnl/woocommerce#459]
Link 3S code in backend status popup doesn't work, click on it doesn't do annything.

When I copy the link, it starts with "myparcel", not with "jouw.postnl.nl"

![image](https://user-images.githubusercontent.com/29940263/99108100-239b8580-25e7-11eb-97f3-770ef8abdc44.png)

Also closing the popup doen't work annymore :(

**Comment by phemels** [comment]
When will this be fixed? It's still a bug in version 4.4.0 :(

**Comment by wthijmen** [comment]
Hi @phemels,
This issue is fixed since release [v4.13.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.13.0)
