### ISSUE TITLE
Bezorgopties zomaar zichtbaar + bbp met ochtendlevering

### ISSUE THREAD

**Issue by NikitaMyParcel** [myparcelnl/woocommerce#460]
**Describe the bug**
Na update staan alle bezorgopties aan, ook al stonden dezevoor de update niet aan. Alles is gratis, dus ook voor ochtendlevering wordt geen toeslag genomen. Ook wordt bijvoorbeeld brievenbuspakje met ochtendlevering opgeslagen en dit is niet aan te passen. 

De bezorgopties staat dus aan na de update, en gaan uit zodra je de instellingen 1 keer opslaat. (in de instellingen staan de opties namelijk helemaal niet aan, terwijl ze wel getoond worden)

**Steps to reproduce this behaviour**
Zie case 00899774

**Expected behaviour**
Ochtendlevering zou niet aan brievenbuspakje gekoppeld mogen worden. En checkout moet na de update niet zomaar alle bezorfgopties tonen. 

**Details**
 - WordPress version: 5.5.1
 - WooCommerce version: 4.5.2
 - WooCommerce MyParcel version: 4.1.3

**Comment by RichardPerdaan** [comment]
Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin. De update is vanmorgen live gezet en kan via de reguliere update worden geïnstalleerd.
