### ISSUE TITLE
Post locatiekiezer standaard te laten openen met de lijst ipv de kaart in checkout

### ISSUE THREAD

**Issue by Chris707** [myparcelnl/woocommerce#464]
Graag een instelling om te kunnen kiezen tussen lijst of kaart als standaard in de checkout

**Comment by MaaikeB-create** [comment]
Dit zou ik ook graag willen zien. De kaart laat in mijn geval namelijk niet direct het dichtstbijzijnde PostNL punt zien. Daarvoor dient de klant dan in te zoomen op de kaart. Een lijst met winkel- en straatnamen is i.m.o. dan handiger. Zeker om het afrekenproces te versnellen.

**Comment by onlinemusketeers** [comment]
Helemaal mee eens Chris!

**Comment by phemels** [comment]
@Chris707 @onlinemusketeers Als jullie de lijst kiezen is de volgorde dan ook random? en niet de dichtstbijzijnde bovenaan?

**Comment by Chris707** [comment]
En dan graag ook wanneer de lijst getoond wordt gelijk het adres ernaast. En dus de adresgegevens niet verstoppen onder de … optie.

**Comment by Mitchell-MyParcel** [comment]
@onlinemusketeers @phemels : Dit zit er inmiddels in en kan ingesteld worden onder de tab "checkout instellingen". De volgorde wordt bepaald o.b.v. nabijheid. M.b.t. de wens om het adres te tonen in de lijst heb ik een issue aangemaakt in de delivery options omdat dat daarin gefixed gaat worden en zodat deze gesloten kan worden.

https://github.com/myparcelnl/delivery-options/issues/78
