### ISSUE TITLE
Selected shipping methode Brievenbuspakje in order backend Pakket

### ISSUE THREAD

**Issue by phemels** [myparcelnl/woocommerce#471]
When I customer buys a product with Verzendmethode “Brievenbuspakje”, in the backend it’s a normal Pakket!! (I have to change it manual)

Version 4.1.3

**Comment by Mitchell-MyParcel** [comment]
@phemels Dit is gefixed in v4.2.0. We hebben deze versie uiteraard zelf uitvoerig getest maar willen deze nu ook met een aantal klanten testen voordat we deze versie breed beschikbaar stellen. Mocht je alvast gebruik willen maken van v4.2.0 dan raden we je aan om dit te doen op een veilige (test) omgeving. Om hiervan gebruik te maken de-installeer je de plug-in en installeer je handmatig de .zip die je hier kunt vinden: https://github.com/myparcelnl/woocommerce/releases/tag/v4.2.0

**Comment by phemels** [comment]
@Mitchell-MyParcel Ik heb een test gedaan, met een brievenbus pakje product (wel zoveel dat het gratis verzenden wordt)
In de backend is het echter "Package" (alles is in het Engels nu, rara).
Nog niet helemaal goed dus lijkt me.
Nog een aantal punten, die nog niet goed zijn:
- Lijst met afhaal punten is niet op volgorde van dichtstbijzijnde eerst
![image](https://user-images.githubusercontent.com/29940263/105481385-4319f300-5ca7-11eb-931e-1bda0f9d0213.png)
- De verzendprijs wordt ex. btw weergegeven bij de MyParcel opties, waarom opeens? De consumenten prijzen zijn altijd incl. btw Dit schept nu onnodige verwarring!!
- Alles van de plugin is nu in het Engels in de backend en frontend en mail
![image](https://user-images.githubusercontent.com/29940263/105481044-c9820500-5ca6-11eb-9786-6f74289827ca.png)
- Als je het huisnummer invult bij de pakjegemak gegevens wordt niet direct overgenomen bij de "normale" adres gegevens
![image](https://user-images.githubusercontent.com/29940263/105481296-25e52480-5ca7-11eb-8cda-359fd5eb367e.png)
etc..

**Comment by phemels** [comment]
@RichardPerdaan @Mitchell-MyParcel ik heb een pakje gemak zending aangepast naar brievenbus pakje (de optie is er) maar daarna gaat het mis, krijg deze error:
![image](https://user-images.githubusercontent.com/29940263/105482944-6776cf00-5ca9-11eb-898b-8fb4a646fe51.png)

**Comment by Mitchell-MyParcel** [comment]
@phemels : Ik heb het eerste issue op onze testomgeving proberen te reproduceren maar bij ons wordt een product met verzendklasse brievenbuspakje zoals verwacht zonder bezorgopties in de checkout gezet en in de backend als brievenbuspakje getoond. Je geeft aan dat je genoeg producten hebt besteld zodat de bezorging gratis is. Kan het zijn dat je gewichten aan het product hebt gehangen en dat de gezamenlijke order daarmee boven de 2KG uitkomt? Of dat er 1 product in de order zit zonder verzendklasse brievenbuspakje?

Het issue met de prijzen die niet overeenkomen vanwege BTW pakken we ook na andere feedback deze sprint op en voegen we als pre release v4.2.1 toe. 

Ik ga dadelijk kijken of ik het issue van Engelse teksten waar Nederlandse teksten verwacht worden kan reproduceren. Zo ja dan gaan we die ook in v4.2.1. fixen. Hetzelfde gaat op voor de adresgegevens die niet gecorrigeerd worden na een aanpassing aan de adresgegevens bij de bezorgopties.

Het issue wat je meldt over de zending aanpassen is strikt genomen zoals het zou moeten werken. We zouden dit alleen netter op kunnen vangen. We neigen ernaar om de optie niet mogelijk te maken omdat dit de keuze is van een consument is. We zouden dan ook de optie niet in de backoffice willen tonen. Zijn er momenten waarop je als webwinkelier er toch bewust voor kiest om deze keuze van de consument te overrulen?

De volgorde van de afhaallocaties is helaas niet iets wat we niet direct op kunnen pakken.

**Comment by phemels** [comment]
@Mitchell-MyParcel 
V.w.b. het eerste punt het was 1 product en dit product heeft geen maten en gewichten ingevuld, heb het net nogmaals geprobeerd en weer pakket in de backend.
In de frontend gaat het wel goed , want er wordt geen pakjegemak kiezer getoond tijdens het afrekenen!!

V.w.b. de zending aanpassen, het komt wel eens voor dat de klant kiest voor pakjegemak en het daar ook heen gaat, maar dat er later iets moet worden nagestuurd, wat gewoon in een enveloppe kan met 1 postzegel.
Nu ben je "verplicht" om dit naar een pakjegemak locatie testuren, met alle extra kosten van dien.
(Of zelf iets te maken)

**Comment by Mitchell-MyParcel** [comment]
@phemels Ik heb voor de zekerheid maten en gewichten ook nog verwijderd maar op onze omgeving gaat alles goed. We zouden graag even mee kijken bij jou op de omgeving, is dat mogelijk? Zo ja dan is het denk ik het handigst als je een mail stuurt naar support@myparcel.nl met tijdelijke credentials. Als je mijn naam erbij noemt zal een van mijn collega's zorgen dat ik de mail ook te zien krijg.

Ik snap begrijp je tweede opmerking over het omzetten naar een brievenbuspakje. Goed punt. We gaan de BTW en bovenstaande issue eerst oppakken maar we gaan zorgen dat deze feedback meegenomen wordt.

**Comment by phemels** [comment]
@Mitchell-MyParcel Geen probleem mail is gestuurd.

**Comment by Mitchell-MyParcel** [comment]
Dit issue is gewijzigd naar een feature. Onder normale omstandigheden wordt een zending waaraan de verzendklasse brievenbuspakje gekoppeld is ook als zodanig verwerkt. Als de verzendmethode 'Gratis verzenden' geactiveerd is en deze wordt ook voor de zending geselecteerd wordt er echter door WooCommerce geen verzendklasse aan de zending gehangen en wordt teruggevallen op het pakket. De overige issues dit genoemd zijn hierboven zullen opgepakt worden.

**Comment by phemels** [comment]
> @phemels Ik heb voor de zekerheid maten en gewichten ook nog verwijderd maar op onze omgeving gaat alles goed. We zouden graag even mee kijken bij jou op de omgeving, is dat mogelijk? Zo ja dan is het denk ik het handigst als je een mail stuurt naar [support@myparcel.nl](mailto:support@myparcel.nl) met tijdelijke credentials. Als je mijn naam erbij noemt zal een van mijn collega's zorgen dat ik de mail ook te zien krijg.
> 
> Ik begrijp je tweede opmerking over het omzetten naar een brievenbuspakje. Goed punt. We gaan de BTW en bovenstaande issue eerst oppakken maar we gaan zorgen dat deze feedback meegenomen wordt.

@Mitchell-MyParcel wordt de "tweede opmerking" nog aangepast? ("pakjegemak" zending omzetten naar "brievenbuspakje" in backend, i.v.m. b.v. nasturen onderdeel)

**Comment by phemels** [comment]
> Dit issue is gewijzigd naar een feature. Onder normale omstandigheden wordt een zending waaraan de verzendklasse brievenbuspakje gekoppeld is ook als zodanig verwerkt. Als de verzendmethode 'Gratis verzenden' geactiveerd is en deze wordt ook voor de zending geselecteerd wordt er echter door WooCommerce geen verzendklasse aan de zending gehangen en wordt teruggevallen op het pakket. De overige issues dit genoemd zijn hierboven zullen opgepakt worden.

@Mitchell-MyParcel Dit is namelijk een losstaande "Feature"

**Comment by phemels** [comment]
Voor openstaande item nieuw ticket gemaakt #613
