### ISSUE TITLE
Undefined index: use_split_address_fields

### ISSUE THREAD

**Issue by Timmer247** [myparcelnl/woocommerce#472]
**Probleem**
Na het upgraden van MyParcel v3.2.1 naar MyParcel v4.1.3 kan de optie **MyParcel address fields** in **Checkout settings** niet meer worden gewijzigd (instelling blijft altijd disabled na het opslaan). In bijna ieder beheer scherm (en log file) wordt de volgende melding getoond:
`Undefined index: use_split_address_fields in ../public/wp-content/plugins/woocommerce-myparcel/includes/admin/settings/class-wcmp-settings-data.php on line 126`

**Details**
 - WordPress version: 5.5.3
 - WooCommerce version: 4.7.0
 - WooCommerce MyParcel version: 4.1.3
 - PHP version: 7.4.0

**Toelichting**
Na de upgrade van v3.2.1 naar v4.1.3 heb ik de plugin verwijderd en versie v3.2.1 opnieuw geïnstalleerd.
Dan treedt dit issue niet op.

Vervolgens heb ik de daarop volgende versie (v4.0.0) geïnstalleerd. Nu treedt dit issue direct op. 
Vervolgens heb ik iedere daarop volgende versie geïnstalleerd  (v4.0.1, v4.0.2, v4.0.4, ..., v4.1.2, v4.1.3) en gecontroleerd of het issue nog steeds aanwezig is. Bij iedere versie vanaf v4.0.0 treedt dit issue op.

**Comment by Timmer247** [comment]
Na het installeren van versie 4.1.4 wordt de foutmelding (Undefined index: use_split_address_fields) niet meer getoond maar is het niet meer mogelijk om bij de **Checkout instellingen** de **MyParcel adresvelden** in te stellen. Je kan de optie wel selecteren maar bij het opslaan wordt de selectie weer uitgeschakeld (ongedaan gemaakt).

**Comment by Timmer247** [comment]
Het issue wordt waarschijnlijk veroorzaakt door de WooCommerce NL Postcode Checker plugin (versie 2.4.0). Op het moment dat deze plugin gedeactiveerd is kunnen de MyParcel adresvelden wel worden ingesteld.

**Comment by Spreeuw** [comment]
Het probleem dat hier wordt omschreven wordt veroorzaakt door een verouderde versie van de WooCommerce NL Postcode Checker plugin, die niet compatible is met MyParcel 4.X. De laatste versies van de Postcode Checker (2.5.2 of hoger) zijn compatible met MyParcel 4.X. De "MyParcel adresvelden" instelling wordt dan geheel verborgen (zoals in 2.4.0 met MyParcel 3.X ook gebeurde). Dit wordt gedaan omdat er slechts 1 plugin de adresvelden kan inregelen. Als de instelling getoond zou worden zou dit voor verwarring zorgen doordat hij geen effect zou hebben aangezien de postcode checker niet zonder de losse adresvelden werkt.

Mochten er verder nog problemen zijn met de Postcode Checker, dan kunnen we dat het beste direct via de WP Overnight support afhandelen, ik zie dat je daar inmiddels ook al contact hebt opgenomen 👌

**Comment by RichardPerdaan** [comment]
Beste @Timmer247 ,

Is dit probleem inmiddels opgelost ?
Als het probleem opgelost is, zou je dan de issue willen sluiten?
