### ISSUE TITLE
Pakkettype koppelen aan verzendtype slaat geselecteerde opties niet correct op

### ISSUE THREAD

**Issue by Timmer247** [myparcelnl/woocommerce#473]
**Probleem**
Als ik bij **Pakketttype** in de tab **Standaard exportinstellingen** bij een verzendmethode de pakkettypes selecteer dan worden deze niet correct opgeslagen. 

**Stappen om probleem te reproduceren**
1. Ga naar tab 'Standaard exportinstellingen'
2. Selecteer bij 'Pakket' de volgende opties: Vast tarief, Gratis verzending, Afhalen
2. Verwijder alle opties bij Brievenbuspakje, Ongefrankeerd, Digitale postzegel
3. Sla de wijzigingen op
4. Na het opslaan hebben alle 4 de pakketttypes de volgende 3 opties: Vast tarief, Gratis verzending en Afhalen

**Verwachting**
Per pakkettype 0 of meerdere verzendmethodes kunnen selecteren

**Screenshot**
![woocommerce-myparcel-pakkettype](https://user-images.githubusercontent.com/7815069/99937041-f2e4ea00-2d64-11eb-800e-1cace6b5bd47.png)

**Details**
- WordPress version: 5.5.3
- WooCommerce version: 4.7.0
- WooCommerce MyParcel version: 4.1.3
- PHP version: 7.4.0

**Toelichting**
In debug mode worden er geen fouten gemeld op het scherm of in het log bestand.

**Comment by Brugman** [comment]
Same problem here. This was previously reported in #403 .

I've just installed this plugin today and I'm very worried about the reliability of this plugin if fixing a bug related to saving settings can not be done in 7 weeks. Is it even safe to use in production if this setting cannot save properly?

Minor addition: If you save the page without any linked package types you get the following notice
`Notice: Undefined index: shipping_methods_package_types in \plugins\woocommerce-myparcel\includes\admin\settings\class-wcmp-settings-data.php on line 126`

**Comment by RichardPerdaan** [comment]
Fixed in version 4.1.4 of the MyParcel plugin
