### ISSUE TITLE
Notice on plugin activation

### ISSUE THREAD

**Issue by Brugman** [myparcelnl/woocommerce#480]
I just activated the plugin for the first time on a local setup and got a screen filled with one error.

`Notice: Trying to access array offset on value of type bool in \plugins\woocommerce-myparcel\includes\admin\settings\class-wcmp-settings-data.php on line 126`

Loading any other page afterwards does not show the error anymore. It's probably inside an on activation function.

**Details**
 - PHP: 7.4.10
 - WordPress version: 5.5.3
 - WooCommerce version: 4.7.1
 - WooCommerce MyParcel version: 4.1.3
 - Theme: Custom

**Comment by RichardPerdaan** [comment]
This has been fixed in version [4.3.1] (https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1) of the MyParcel WooCommerce plugin
