### ISSUE TITLE
Make the action icons more unique

### ISSUE THREAD

**Issue by Brugman** [myparcelnl/woocommerce#481]
![screenshot](https://i.imgur.com/AQc9HJg.jpeg)

![too small](https://media.tenor.com/images/97f8775d19a3ea396e451875ba219e07/tenor.gif)

The action icons are way too similar. At this size I can only assume store owners are only going to click them
1. After checking the on-hover label every single time.
2. By using their order. I.e. _I know the 2nd button is to print the label._

This is bound to cause mistakes.

**Describe the solution you'd like**
Give each functionality a unique color and possibly shape!

**Comment by EdieLemoine** [comment]
The icons have recently been replaced, but the version with that change hasn't been released yet. You can see the new icons here: #453 

Please let me know what you think!

**Comment by Brugman** [comment]
Looks better!
