### ISSUE TITLE
403 error in console and no export

### ISSUE THREAD

**Issue by keeslamper** [myparcelnl/woocommerce#483]
When I try to export an order to Myparcel from WooCoommerce I get a red cross and in console is this: https://***.nl/wp-admin/admin-ajax.php?action=wcmp_export&request=add_shipments&order_ids=***&_wpnonce=*** with an 403 error. 

I've this issue on different client webshops.

**Comment by RichardPerdaan** [comment]
Hi @keeslamper ,
Can you indicate which version of the MyParcel plugin is used?

**Comment by keeslamper** [comment]
Hi @RichardPerdaan,

Tried different version from last three till newest. Now running 4.1.4.

**Comment by keeslamper** [comment]
I get this errors within different webshops now. No JS errors, only 403 error.

**Comment by RichardPerdaan** [comment]
Good morning @keeslamper ,

Do you use the BBQ Firewall plugin? 
It seems that this plugin blocks outgoing requests from the MyParcel plugin.

**Comment by keeslamper** [comment]
Hi,

Yes we use this.

Regards,
Kees

Van: Richard Perdaan <notifications@github.com>
Beantwoorden - Aan: myparcelnl/woocommerce <reply@reply.github.com>
Datum: maandag 30 november 2020 om 10:45
Aan: myparcelnl/woocommerce <woocommerce@noreply.github.com>
CC: Lamper Design | Algemeen <info@Lamper-design.nl>, Mention <mention@noreply.github.com>
Onderwerp: Re: [myparcelnl/woocommerce] 403 error in console and no export (#483)


Good morning @keeslamper<https://github.com/keeslamper> ,

Do you use the BBQ Firewall plugin?
It seems that this plugin blocks outgoing requests from the MyParcel plugin.

**Comment by RichardPerdaan** [comment]
This has been fixed in version [4.3.1] (https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1) of the MyParcel WooCommerce plugin
