### ISSUE TITLE
4.1.4: Standard weight of packaging in kg

### ISSUE THREAD

**Issue by NikitaMyParcel** [myparcelnl/woocommerce#485]
**Describe the bug**
When the settings : WooCommerce>Products>Dimensions/WooCommerce>Producten>Afmetingen are set to KG, the packaging weight filled in at WooCommerce>MyParcel>Standard exportsettings will be exported as KG as well. 

At export; errror with physical properties.weight appears. 

**Expected behaviour**
Delete text '(grams)' 

**Details**
 - WordPress version: unknown
 - WooCommerce version: Latest
 - WooCommerce MyParcel version: 4.1.4
 - Theme: ...

**Additional context**

Edit: changed 'expected behaviour'

**Comment by Nikitaverh** [comment]
00913469

**Comment by Nikitaverh** [comment]
FYI: You should fill in the 'packaging weight' in the same measure of weight as your products.
