### ISSUE TITLE
Bestelling overzicht toont altijd pakket' 

### ISSUE THREAD

**Issue by snelweg** [myparcelnl/woocommerce#486]
zie afbeelding, dit had bij een simpele oplever test meteen moeten opvallen bij jullie!

Benieuwd wat voor verborgen fouten er nu nog steeds zijn. Had gehoopt dat de kwaliteit omhoog zou zijn gegaan met jullie sprinten en ander vak jargon, maar helaas blijkt nu weer dat testen niet op de juiste manier gebeurt bij jullie.

![myparcel_3](https://user-images.githubusercontent.com/1257901/100662150-cc224700-3354-11eb-91d7-742d4ea10bb3.png)

bij verversen pagina verandert de tekst wel. Dit was voorheen niet, daar veranderde het onmiddellijk.

**Comment by RichardPerdaan** [comment]
Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin

**Comment by snelweg** [comment]
> Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin

Nope, nog steeds precies hetzelfde gedrag
