### ISSUE TITLE
Fast Velocity Minify-compatibility

### ISSUE THREAD

**Issue by NikitaMyParcel** [myparcelnl/woocommerce#487]
**Plugin/Theme**
De Fast Velocity Minify-plugin 

**Describe the problem**
Kan niet betaald worden als deze plugin staat ivm niet ingevulde velden 

**Steps to reproduce this behaviour**
Zie case 00896940 (ivm privacy) 

**Expected behaviour**
Er zou niet moeten worden gekeken naar shipping fields als er niet verzonden wordt

**Screenshots**

**Additional context**

**Comment by RichardPerdaan** [comment]
De Fast Velocity is te gebruiken vanaf versie [v4.2.0 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.2.0) van de MyParcel plugin
