### ISSUE TITLE
Pakjegemak locatie niet zichtbaar in order emails en pakbon etc

### ISSUE THREAD

**Issue by phemels** [myparcelnl/woocommerce#491]
Pakjegemak locatie wordt niet getoond in order e-mails, alleen in popup in backend.

![image](https://user-images.githubusercontent.com/29940263/101392321-eb295780-38c5-11eb-9fee-fcef6c3a3b1e.png)

Als de optie "show delivery day" wordt aangezet bij de checkout instellingen, dan wordt er iets getoond.

![image](https://user-images.githubusercontent.com/29940263/101392519-24fa5e00-38c6-11eb-965a-cfb528c27289.png)

Dan wordt dit getoond:

![image](https://user-images.githubusercontent.com/29940263/101392267-d2b93d00-38c5-11eb-900d-ce9e59d0daed.png)

De klant kiest voor PostNL pakjegemak locatie, niet voor MyParcel afhalen!!

Pakjegemak locatie moet onafhankelijk zijn van de checkout instelling "show delevery day".

**Comment by onlinemusketeers** [comment]
Ben het met je eens. In de transactionele emails wordt ook MyParcel vermeld.  Voor de ontvanger is dat eerder verwarrend dan informatief. 
Want de verzending gaat met PostNL.

**Comment by phemels** [comment]
De bezorg dag kun je beter niet vermelden tegenwoordig, die wordt helaas toch niet gehaald 9 van de 10 keer.

**Comment by onlinemusketeers** [comment]
lol

**Comment by RichardPerdaan** [comment]
Dit probleem is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin

**Comment by phemels** [comment]
@RichardPerdaan Op de pakbon is de afhaal locatie nog niet zichtbaar, gebruik deze shortcode {{myparcel_delivery_options}}
Enig idee hoe dat kan?
In de emails is het nu wel zichtbaar.
