### ISSUE TITLE
PostNL: Check for virtual product

### ISSUE THREAD

**Issue by robindelaater** [myparcelnl/woocommerce#492]
**Is your feature request related to a problem?**
When a virtual product is in the shop checkout it loads the delivery options.

**Describe the solution you'd like**
When a virtual product is in the shop checkout it shouldn't load the delivery options.

This should be easily fixed by checking if it's a virtual product, if it is, then don't load the delivery options.

**Comment by Mitchell-MyParcel** [comment]
This has been fixed in the lates version. There is one issue with a virtual product that is added to rest of world shipments resulting in an error when exporting. This issue will be fixed next Tuesday.
