### ISSUE TITLE
cut off tijd van zondag werkt niet

### ISSUE THREAD

**Issue by soedesh** [myparcelnl/woocommerce#496]
bestellingen tussen zondag 18:00 uur en 23:00 uur krijgen ook de bezorgdag maandag te zien. Pas vanaf 23:00 uur komt de leverdag dinsdag. Het lijkt wel of de tijdsinstelling van 18:00 uur volledig wordt genegeerd.

![afbeelding](https://user-images.githubusercontent.com/46486914/101979853-eddad280-3c60-11eb-9c2f-0c600d51050e.png)

**Comment by RichardPerdaan** [comment]
Issue is solved with version: [v4.9.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.9.0)
