### ISSUE TITLE
Ongefrankeerd label geprint, maar niet volgens plugin 

### ISSUE THREAD

**Issue by phemels** [myparcelnl/woocommerce#498]
Als ik een ongefrankeerd label maak en print, blijft er waar normaal de 3S code wordt getoond staan:
Concept aangemaakt maar nog niet geprint.

Deze tekst staat in het order overzicht, kolom "Barcode"

![image](https://user-images.githubusercontent.com/29940263/102104171-27ad0400-3e2e-11eb-9fc3-9b2b005980d0.png)

MyParcel Plugin versie 4.1.4
WooCommerce Versie: 4.7.1

**Comment by Mitchell-MyParcel** [comment]
@phemels : Hier wordt deze melding nu standaard getoond omdat voor deze verzendopties per definitie geen barcode gegenereerd wordt. We zullen een aanpassing op de backlog zetten om te kijken naar de verzendoptie om vervolgens deze melding daarop aan te passen. Dit zal dan iets worden in de trant van: Label is geprint.

**Comment by Mitchell-MyParcel** [comment]
@phemels : Dit is gefixed in v4.2.0 voor zowel ongefrankeerd als een digitale postzegel.

**Comment by RichardPerdaan** [comment]
Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin. De update is vanmorgen live gezet en kan via de reguliere update worden geïnstalleerd.

**Comment by phemels** [comment]
> Label is geprint

@Mitchell-MyParcel kan de tekst anders? Er staat nu, als de gegevens zijn geëxporteerd (en nog NIET geprint) al "Label is geprint"
B.v. tekst: "Gegevens zijn geëxporteerd" en pas als er geprint is "Label is geprint"

P.S. de melding staat dubbel in de order notities:

![image](https://user-images.githubusercontent.com/29940263/112182465-99e76e80-8bfd-11eb-9872-8399431f698e.png)
