### ISSUE TITLE
Brievenbuspakje artikel naar België is niet aan te passen in backend, gevolg ERROR!!

### ISSUE THREAD

**Issue by phemels** [myparcelnl/woocommerce#499]
Als een klant uit Belgie een brievenbuspakje artikel besteld, dan moet dit of als pakket of als ongefrankeerd worden verstuurd.
België kent geen Brievenbuspakje!

Echter in de backend is het NIET aan te passen, zie:

![image](https://user-images.githubusercontent.com/29940263/102177288-85c7fe80-3ea3-11eb-96c6-63506af97b2c.png)

Ook op de MyParcel site zelf is Brievenbuspakje niet mogelijk, zie:

![image](https://user-images.githubusercontent.com/29940263/102177483-f3742a80-3ea3-11eb-951c-78e648f942aa.png)

Waarom "stuurt" de plugin hier dan wel op?

Gevolg deze ERROR:

![image](https://user-images.githubusercontent.com/29940263/102177619-37ffc600-3ea4-11eb-9790-abd11561ad9e.png)

**Comment by RichardPerdaan** [comment]
Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin. De update is vanmorgen live gezet en kan via de reguliere update worden geïnstalleerd.
