### ISSUE TITLE
Pakjegemak locatie kiezer wordt getoond bij Brievenbuspakje, en een prijs!!

### ISSUE THREAD

**Issue by phemels** [myparcelnl/woocommerce#502]
Bij een Brievenbus pakje wordt ook de locatie kiezer getoond.

![image](https://user-images.githubusercontent.com/29940263/102245974-7cb84b00-3efe-11eb-95dc-366dbcdde015.png)

Ook wordt nu de prijs ex. btw getoond.

Versie 4.1.5

**Comment by Mitchell-MyParcel** [comment]
@phemels Begrijp ik uit je opmerking in #471 goed dat dit issue nu wel opgelost is in de laatste versie? Ik doel dan niet op de prijs ex BTW maar dat Pakjegemak in v4.2.0 niet meer getoond wordt als de verzendklasse op brievenbuspakje staat.

**Comment by phemels** [comment]
@Mitchell-MyParcel klopt dit probleem is gefixed in v4.2.0
