### ISSUE TITLE
Pakjegemak locatie lijst niet in volgorde van dichtstbijzijnde locatie eerst

### ISSUE THREAD

**Issue by phemels** [myparcelnl/woocommerce#503]
Screenshot spreekt voor zich neem ik aan!

![image](https://user-images.githubusercontent.com/29940263/102346408-120b1c00-3f9f-11eb-90a2-164aebced434.png)

**Comment by phemels** [comment]
Op de PostNL website gaat het wel goed, https://www.postnl.nl/locatiewijzer

**Comment by RichardPerdaan** [comment]
Dit is een duplicated issue: [https://github.com/myparcelnl/delivery-options/issues/37](https://github.com/myparcelnl/delivery-options/issues/37)
Het onderdeel zal aangepast moeten worden in de delivery options.

**Comment by phemels** [comment]
Hi @RichardPerdaan dank je, ik was hem kwijt en dacht heb het toch gemeld. Maar hij verzet :)
Fijne dag.
