### ISSUE TITLE
Als klant wil ik zelf per zending aangeven hoeveel gewicht er in een zending zit

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#504]
**Is your feature request related to a problem?**
Wanneer ik 2 labels aanmaak en elk product is 16kg, krijg ik een error omdat het pakket te zwaar is.

**Describe the solution you'd like**
Het gewicht zou over de labels moeten worden verspreid of ik moet zelf aan kunnen geven hoeveel gewicht in elke zending zit.

**Additional context**
De klant verkoopt stoelen van 16 kg per stuk. Als een consument 2 stoelen koopt, kunnen zendingen niet worden aangemaakt.

**Comment by TimBlom** [comment]
Case 00933372

**Comment by RichardPerdaan** [comment]
Opgelost en is te gebruiken in de laatste versie van de MyParcel plugin [v4.11.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.11.0)
