### ISSUE TITLE
Error 500 with latest version in adminpanel (page orders)

### ISSUE THREAD

**Issue by ERR1R** [myparcelnl/woocommerce#510]
In adminpanel when checking the orders you get the following error on the orders page (wp-admin/edit.php?post_type=shop_order)

Status Code: 500 

php error:

Uncaught Error: Call to undefined method WCMP_Export::find_order_shipping_classes() in /wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmp-export.php:870\nStack trace:\n#0 /wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmp-export.php(916): WCMP_Export->getOrderShippingClass(Object(Automattic\\WooCommerce\\Admin\\Overrides\\Order), 'flat_rate:1')\n#1 /wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmypa-admin.php(244): WCMP_Export->getPackageTypeFromOrder(Object(Automattic\\WooCommerce\\Admin\\Overrides\\Order))\n#2 /wp-includes/class-wp-hook.php(287): WCMYPA_Admin->showMyParcelSettings(Object(Automattic\\WooCommerce\\Admin\\Overrides\\Order))\n#3 /wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(...\n', referer: https://xxxxxx/wp-admin/admin.php?page=wc-admin

**woocommerce version: 4.8.0
wordpress: 5.6
php: 7.2.33 
mysql: 10.3.24-MariaDB
MyParcel:  4.1.5**

**Comment by RichardPerdaan** [comment]
This has been fixed in version [4.3.1] (https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1) of the MyParcel WooCommerce plugin.
