### ISSUE TITLE
As a client I want the right weight to be visually selected.

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#512]
**Describe the bug**
When the weight of an order is 100 grams I want the right weight to be visually selected. This works for the weight of 75 grams, but other weight seem to show 0-20 grams.

![image](https://user-images.githubusercontent.com/22811561/103228490-41237500-4931-11eb-960f-ed5e746bcf16.png)

**Steps to reproduce this behaviour**
1. Go to 'WooCommerce' > 'Orders'
2. Click on the package type in the column 'shipping'
3. See the right calculated weight but the wrong selected weight in the dropdown.

**Expected behaviour**
As a client I always want the right weight to be visually selected.

**Comment by TimBlom** [comment]
Case 00937166

**Comment by RichardPerdaan** [comment]
This has been fixed in version [4.3.1] (https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1) of the MyParcel WooCommerce plugin
