### ISSUE TITLE
As a client I want to us KGs as weight measurement

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#517]
**Describe the bug**
When I use Kgs as weight measurement the plugin does not create the right digital stamp

**Steps to reproduce this behaviour**
1. Go to 'WooCommerce' > 'Orders'
2. Click on 'the packagetype'
4. See:
![image](https://user-images.githubusercontent.com/22811561/103631098-dd0d3c00-4f42-11eb-8773-06b137388243.png)
5. Export digital stamp

**Expected behaviour**
When I export the label it should be 146 grams

**Comment by RichardPerdaan** [comment]
This has been fixed in version [4.3.1] (https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1) of the MyParcel WooCommerce plugin
