### ISSUE TITLE
Verzendklasse onafhankelijk van de verzendmethode

### ISSUE THREAD

**Issue by TeunSmit** [myparcelnl/woocommerce#520]
**Describe the solution you'd like**
Op het moment is het niet mogelijk flatrate en flatrate+verzendklasse onafhankelijk van elkaar te gebruiken. Flatrate krijgt in dit geval altijd voorrang. Als je bijvoorbeeld flatrate koppelt onder BBP ivm channable bol.com zendingen, dan zal een flatrate+verzendklasse geen pakket meer aan kunnen maken.

**Additional context**
<img width="727" alt="MyParcel— WordPress 2021-01-06 " src="https://user-images.githubusercontent.com/54140671/103770227-f1763500-5025-11eb-982c-d0c8e912fa27.png">

**Comment by TeunSmit** [comment]
00945567

**Comment by RichardPerdaan** [comment]
Dit is een functionaliteit wat wij niet kunnen aanpassen. Het is namelijk afhankelijk hoe WooCommerce de verzendmethoden/verzendklassen opslaat.
