### ISSUE TITLE
Als klant wil ik dat het barcode-veld in Channel Engine weer wordt ingevuld

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#521]
**Omschrijving**
In vorige zendingen werd het veld **Channel Engine - Track&Trace** automatisch ingevuld na het aanmaken van een label. Dit gebeurt nu niet meer

![image](https://user-images.githubusercontent.com/22811561/103886996-ac640880-50e2-11eb-92c4-fa9891239fe0.png)

**Verwacht gedrag**
Na het aanmaken van een zending moeten de ChannelEngine vulden ingevuld worden.

**Comment by RichardPerdaan** [comment]
Wanneer je de volgende instelling gebruikt met dezelfde format dan zal dit probleem opgelost zijn"
![image](https://user-images.githubusercontent.com/11389731/146526761-cbca411e-4b7e-4677-a81e-0083ffe0fba2.png)
