### ISSUE TITLE
Cannot export due to "Product data must be set for international MyParcel shipments. Use addItem()." error

### ISSUE THREAD

**Issue by larsrengersen** [myparcelnl/woocommerce#522]
**Describe the bug**

When I try to export an order to MyParcel from Woocommerce I get the following message
Product data must be set for international MyParcel shipments. Use addItem().
It's an order to Ukraine.

All the obvious things have been checked:
- Latest versions, no updates available
- All parameters entered (size, weight, HS code, country of origin with 2 letter ISO code)

Some "special" circumstances:
- Backordered item
- Variable product
- Product with extra options
But except for the backorder factor that used to work OK.

I tried using the latest master but that does not help either.

**Steps to reproduce this behaviour**
2. Click on '...'
3. Scroll down to '...'
4. See an error

**Expected behaviour**
Successful export

**Screenshots**

**Details**
 - WordPress version: 5.6
 - WooCommerce version: 4.8.0
 - WooCommerce MyParcel version: 4.1.5
 - Theme: Generatepress

**Additional context**

**Comment by RichardPerdaan** [comment]
This has been fixed in version [4.3.1] (https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1) of the MyParcel WooCommerce plugin
