### ISSUE TITLE
Export via actions at the bottom of the page does not work

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#526]
**Describe the bug**
In WooCommerce > Orders you have two 'actions' drop downs. Exporting with the one at the bottom of the page does not work. The actions at the top of the pages works.

![image](https://user-images.githubusercontent.com/22811561/104311370-65588780-54d5-11eb-9207-bc51ab8b7372.png)

**Comment by RichardPerdaan** [comment]
Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin
