### ISSUE TITLE
Als klant wil ik enkel de meerprijs bij de bezorgopties tonen, niet de totaalprijs

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#538]
Omdat binnen WooCommerce de verzendmethoden losstaan van de bezorgopties, lijkt het alsof prijzen dubbel worden berekend. Met enkel het tonen van de meerprijs ben je van dit probleem af.

**Comment by TimBlom** [comment]
Case 00967771

**Comment by DarkAllMan** [comment]
+1
Tevens laat hij nu de prijs zien ex btw. Persoonlijk is dit onduidelijk voor de klant.
Liever idd alleen de meerprijs, mocht je toch de mogelijkheid behouden om de prijs te zien, dan graag ook de optie om inc BTW/VAT te laten zien.

**Comment by DarkAllMan** [comment]
De nieuwe pre-release laat nu de prijs inc BTW zien. Dat is al een verbetering.
Echter, wanneer ik de lokatie "SHOW AFTER SUBTOTAL" is, is het voor de klant nog steeds onduidelijk. In deze opzet, zou ik de kosten nog steeds willen verbergen, omdat ze al in het subtotaal zijn opgenomen.

![afbeelding](https://user-images.githubusercontent.com/1582343/108836094-b8435580-75d0-11eb-9a01-9e6cbddac1e2.png)

**Comment by aqdennis** [comment]
Wordt de BTW wel goed berekend rekening houdend met mandjes waar artikelen met alleen lage BTW in kunnen zitten of zowel lage als hoge BTW?  Dat was in een verder verleden namelijk nog wel eens het probleem....dat er maar één BTW tarief werd toegepast.

**Comment by DarkAllMan** [comment]
Die vraag moet MyParcel beantwoorden, aangezien wij geen laagtarief items voeren.

**Comment by Mitchell-MyParcel** [comment]
We hebben vanmiddag v4.3.0 via github beschikbaar gesteld. Daarin kun je via de checkout instellingen de prijzen tonen als meerprijs. 

@DarkAllMan: In jouw specifieke voorbeeld wordt er dan geen prijs meer getoond. We tonen dan wel nog prijzen voor bezorgopties met toeslagen.
@aqdennis: We volgen voor het optellen van BTW op de shipment deze logica: https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/#section-5 Dit komt erop neer dat we het hoogste BTW tarief in de order toepassen op de shipping costs.

**Comment by DarkAllMan** [comment]
Ik heb de pre-release nu op mijn test site draaien. Ziet er goed uit!

**Comment by DarkAllMan** [comment]
Ik heb de pre-release nu losgelaten op mijn livesite en daar krijg ik de opties niet te zien.
MyParcel plugin instellingen identiek..... moet ff kijken wat er aan de hand is.

**Comment by Mitchell-MyParcel** [comment]
@DarkAllMan We hebben deze versie ook bij een select groepje gebruikers uitgerold en daaruit kwam vanochtend de melding dat gewicht en HS code voor NL en EU zendingen verplicht was. Mocht je een leeg pakket gewicht of HS code ingevuld hebben bij de standaard exportinstellingen (of voor je producten gewichten ingevuld hebben) dan is er niks aan de hand. Anders raad ik je aan om de installatie van 4.3.0 even opnieuw te doen, daar zit inmiddels een fix in.

**Comment by DarkAllMan** [comment]
Ik heb zojuist nog de laatste versie vd pre-release gedownload en geinstalleerd.
We hebben nog geen export gedaan op deze versie, dat zal maandag worden.
Zie wel in de mails nu dat een afleverdatum wordt gegeven... dat is niet de bedoeling. Kan ik deze uitschakelen?

![afbeelding](https://user-images.githubusercontent.com/1582343/111836068-0f99c480-88f6-11eb-8aac-06badb8a59ab.png)

**Comment by RichardPerdaan** [comment]
@DarkAllMan ,
Vorige week zijn wij bezig geweest met het onderdeel omtrent het tonen van de afleverdatum. Deze #589 aanpassing zal niet in de huidige release komen maar in de release die daar op volgt.

**Comment by DarkAllMan** [comment]
@RichardPerdaan Is er een manier dat ik dit kan uitzetten met wat code/filter (tijdelijk, tot de nieuwe release?)

**Comment by RichardPerdaan** [comment]
@DarkAllMan,
Als je een mail stuurt naar support@myparcel.nl dan kunnen we een zip bestand met je delen waardoor je de aanpassing kan proberen. Als je mijn naam in de mail benoemd dan weten de collega's van IT-support dat ze bij mij moeten zijn.

**Comment by RichardPerdaan** [comment]
Het probleem omtrent de meerprijs en de totaal prijs is opgelost in versie [4.3.1](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1). Deze versie is vanmorgen live gezet en kan via de reguliere update worden geïnstalleerd.
