### ISSUE TITLE
 Error in MyParcel API request

### ISSUE THREAD

**Issue by Brisked** [myparcelnl/woocommerce#541]
Als ik meerdere zendingen wil exporteren naar MyParcel vanuit WooCommerce krijg ik telkens de volgende error:

Error in MyParcel API request: 0 - data.shipments[19].recipient.street Must be at least 1 characters long - Failed validation against JSON-SCHEMA shipment/post_shipments_request-v1.1.json Url: https://api.myparcel.nl/shipments Request:

Terwijl de straatnaam wel ingevuld staat bij WooCommerce. Hoe kan dit worden opgelost?

**Comment by Mitchell-MyParcel** [comment]
@Brisked Het lijkt erop dat 1 van de adressen in de batch geen straatnaam heeft terwijl we dit wel verwachten. We hebben recent v4.2.0 als pre-release beschikbaar gesteld. In deze versie zitten verbeteringen voor het afhandelen door errors waardoor je na export zou moeten zien welke order het probleem veroorzaakt.

Mocht je deze versie willen gebruiken dan raden we je aan om dit te doen op een veilige (test) omgeving. Voor een goede werking de-installeer je eerst de huidige versie van de plugin en installeer je v4.2.0 door handmatig de .zip te uploaden.

Je kunt de .zip samen met de release notes hier vinden: https://github.com/myparcelnl/woocommerce/releases/tag/v4.2.0

**Comment by RichardPerdaan** [comment]
Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin
