### ISSUE TITLE
Version 4.2.1 gives lot's of Notice: Undefined index:  in excisting orders

### ISSUE THREAD

**Issue by phemels** [myparcelnl/woocommerce#568]
After installing version 4.2.1. I see this in my backend :(
![image](https://user-images.githubusercontent.com/29940263/108381273-f07d1980-7207-11eb-9b6a-c6735d436d19.png)

**Comment by phemels** [comment]
En in nieuwe pakjegemak locatie orders :(

**Comment by phemels** [comment]
Als ik een bestelling die de status "wacht op betaling" heeft op "in behandeling" zet krijg ik een kritieke fout melding!

![image](https://user-images.githubusercontent.com/29940263/108382861-8bc2be80-7209-11eb-8c70-226cf759ebc3.png)

**Comment by Mitchell-MyParcel** [comment]
@phemels We hebben het ook even bij jou op je testomgeving geprobeerd en zien inderdaad al een error op de thank-you page. We gaan er meteen even naar kijken. Die kritieke fout lijkt overigens dezelfde oorzaak te hebben.

**Comment by Mitchell-MyParcel** [comment]
@phemels Als je handmatig de oude verwijdert en de nieuwe installeert zijn deze problemen opgelost.

**Comment by phemels** [comment]
@Mitchell-MyParcel waar vindt ik de installeerbare nieuwe file :)

**Comment by RichardPerdaan** [comment]
@phemels ,
Als je op de onderstaande link klikt, zal gelijk het juiste bestand worden gedownload:
[woocommerce-myparcel.zip](https://github.com/myparcelnl/woocommerce/releases/download/v4.2.1/woocommerce-myparcel.zip)

**Comment by phemels** [comment]
Het zijn wel minder meldingen, maar weg is nog niet alles :(

![image](https://user-images.githubusercontent.com/29940263/108874965-feaea980-75fc-11eb-94f3-90476e7fa813.png)

**Comment by Mitchell-MyParcel** [comment]
Hoi @phemels , dit lijkt een zending te betreffen waarvoor je een export hebt gedaan net nadat je vorige week de update naar 4.2.1. geïnstalleerd hebt. Kan dit kloppen? We hebben het nu zo gemaakt dat zendingen ouder dan 4.2.1. en nieuwe zendingen goed gaan. Deze zendingen vallen daar nu net tussen waardoor deze error toont. We zien dat nieuwe zendingen goed gaan, kun je dit bevestigen?

**Comment by phemels** [comment]
@RichardPerdaan @Mitchell-MyParcel Het betrefd test zendingen van op of na 7 december 2020
zie

![image](https://user-images.githubusercontent.com/29940263/109016680-b05de100-76b6-11eb-8df3-2b4edb3637b6.png)

**Comment by Mitchell-MyParcel** [comment]
@phemels : Dit is veroorzaakt door de update van vorige week. Helaas kunnen we niet met terugwerkende kracht deze testzendingen fixen omdat die update de informatie van de retaillocaties verwijderd heeft. Met de versie die we je nu hebt geïnstalleerd komt dat niet meer voor maar kunnen we helaas dus niet zendingen herstellen waar het reeds gebeurt is.

**Comment by phemels** [comment]
@Mitchell-MyParcel Ok geen probleem, zolang het straks niet met de live site gebeurd :)

**Comment by EdieLemoine** [comment]
@Mitchell-MyParcel @phemels Voor die laatste heb ik een oplossing, ik dacht dat het aan mijn omgeving lag en ik zelf orders zo kapot had gemaakt, maar dan zal ik hem toch in PR zetten ☺️

**Comment by RichardPerdaan** [comment]
Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin. De update is vanmorgen live gezet en kan via een reguliere update worden geïnstalleerd.

**Comment by phemels** [comment]
> @Mitchell-MyParcel @phemels Voor die laatste heb ik een oplossing zodat in ieder geval de notices verdwijnen, ik dacht dat het aan mijn omgeving lag en ik zelf orders zo kapot had gemaakt, maar dan zal ik hem toch in PR zetten ☺️

@EdieLemoine  de update is geïnstalleerd, maar de meldingen zijn niet weg :(
