### ISSUE TITLE
As a client I want to be able to hide the export buttons if a customers picks up the order 

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#570]
**Describe the solution you'd like**
When a customers chooses to pick up the order at the store I do not want to see an export button in the column 'actions'.

**Comment by TimBlom** [comment]
Case 01001079

**Comment by wthijmen** [comment]
Hi @TimBlom,
This issue is fixed since release [v4.13.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.13.0)
