### ISSUE TITLE
[MyParcel Pre-Release 4.2.1] Pickup Point resets when changing payment method

### ISSUE THREAD

**Issue by DarkAllMan** [myparcelnl/woocommerce#572]
**Describe the bug**
When I select a pickup point first and then change/select a payment method, the pickup point is reset.

**Steps to reproduce this behaviour**
1. Go to checkout form and select a pickup point
2. Scroll to payment options and select a different payment option
3. Scroll back to pickup points and see no pickup point is selected

**Expected behaviour**
I expect that the selected pickup point stays selected, even when I change payment methods

**Details**
 - WordPress version: Latest
 - WooCommerce version: Latest
 - WooCommerce MyParcel version: 4.2.1
 - Theme: Avada

You can check this behaviour at https://test.lievelabels.nl

**Comment by Mitchell-MyParcel** [comment]
@DarkAllMan We zijn het op jouw testomgeving gebeuren maar op onze omgeving niet. We vermoeden dus dat het aan de theme ligt. Ik zet deze op de backlog.

**Comment by DarkAllMan** [comment]
Dank!

**Comment by DarkAllMan** [comment]
Ik heb dit probleem niet meer in de pre-release van vandaag.....
