### ISSUE TITLE
[4.2.1] PHP8.0 Warning: Only the first byte will be assigned to the string offset

### ISSUE THREAD

**Issue by Spreeuw** [myparcelnl/woocommerce#576]
**Describe the bug**
The code below triggers a warning in PHP8.0:

`Warning: Only the first byte will be assigned to the string offset`

https://github.com/myparcelnl/woocommerce/blob/d94c7c9832c58af1db8825fa26db7f8511c93ace/includes/frontend/class-wcmp-checkout.php#L153-L157

This is because `wp_localize_script` expects an array but `get_delivery_options_config()` returns a string (JSON).
WP actually handles the JSON conversion, so either this should simply `return $myParcelConfig;`:
https://github.com/myparcelnl/woocommerce/blob/d94c7c9832c58af1db8825fa26db7f8511c93ace/includes/frontend/class-wcmp-checkout.php#L254

OR the JSON should be put in a single array element (I think returning the array is actually safer).

Delivery options are not loading unless I return the data array instead of the JSON.

**Comment by wthijmen** [comment]
Hi @Spreeuw,

This issue is solved since January 2022.
