### ISSUE TITLE
Shipping address is validated even when not enabled

### ISSUE THREAD

**Issue by Spreeuw** [myparcelnl/woocommerce#578]
**Describe the bug**
In this code:
https://github.com/myparcelnl/woocommerce/blob/d94c7c9832c58af1db8825fa26db7f8511c93ace/includes/class-wcmp-postcode-fields.php#L740-L749

the line:
```php
array_key_exists('ship_to_different_address', $address)
```

will evaluate to `true` even when the checkbox is not actually checked, the value being `false`:
![xdebug-myparcel-checkout-variables](https://user-images.githubusercontent.com/3217773/109662955-e1815a00-7b6b-11eb-884f-773698bb41d5.png)

changing this to:
```php
!empty( $address['ship_to_different_address'] )
```

Will prevent error notices from showing up when the shipping address doesn't pass validation (but would be overwritten by billing address anyway):
![vul-een-geldig-verzendadres-in](https://user-images.githubusercontent.com/3217773/109663075-feb62880-7b6b-11eb-8568-b07a9fa51d92.png)

**Comment by Spreeuw** [comment]
Quick note that this appears to be triggered specifically when combining the plugin with [Checkout Field Editor for WooCommerce](https://www.themehigh.com/product/woocommerce-checkout-field-editor-pro/) by ThemeHigh (the paid version, not the free one from wordpress.org). The fix works universally though!

**Comment by DarkAllMan** [comment]
Deze fix zit nog niet in de pre-release update van vandaag? Ik voer hem maar even handmatig door.
