### ISSUE TITLE
Bezorgdag en "vanaf" prijs voor pickup zijn in het Nederlands op Engelse webshop

### ISSUE THREAD

**Issue by aqdennis** [myparcelnl/woocommerce#581]
**Describe the bug**
Ik heb een engelsetalige webshop, maar bij de bezorgopties wordt de bezorgdag en de "vanaf" prijs bij pickup altijd in het Nederlands aangegeven. Blijkbaar zijn deze teksten nergens aan te passen?

**Expected behaviour**
Invoervelden voor deze strings in de backend óf een automatische vertaling.

**Screenshots**
![image](https://user-images.githubusercontent.com/48013601/109781230-04f9e280-7c08-11eb-8725-86f333fb75d3.png)

**Details**
 - WordPress 5.6.2
 - WooCommerce 5.0.0
 - WooCommerce MyParcel 4.1.5
 - Theme: Storefront/Deli

**Comment by Mitchell-MyParcel** [comment]
@aqdennis : Er komt binnenkort een release aan waardoor je hier optioneel alleen maar de meerprijzen getoond krijgt. In dit geval zou dan dus het tonen van Vanaf <prijs> komen te vervallen. Het is niet precies waar je naar op zoek bent maar ik denk dat je daarmee wel mogelijk geholpen bent. Klopt dit? Zo ja dan zal ik hier een bericht achterlaten zodra die release gedeeld is.

**Comment by aqdennis** [comment]
@Mitchell-MyParcel. Dit is zelfs nog beter, en het zou ook meteen issue #557 oplossen. Ik wacht dus even op de nieuwe release, bedankt!

**Comment by Mitchell-MyParcel** [comment]
@Mitchell-MyParcel In die release zit ook een fix voor het refreshen van de prijs, dus 557 zou dan ook inderdaad opgelost moeten zijn. Ik heb eerder gezegd dat we die versie deze week zouden delen op github maar dat wordt volgende week.

**Comment by Mitchell-MyParcel** [comment]
@aqdennis: De release waar ik hierboven naar refereer is inmiddels beschikbaar via github. Volgende week gaan we deze waarschijnlijk ook als stable releasen. Hierin zit o.a. onder checkout instellingen de optie om prijzen te tonen als meerprijs waardoor " Vanaf x prijs' komt te vervallen. Ook het refreshen van de prijs zou nu goed moeten gaan.

Als je gebruik wil maken van deze release graag eerst de huidige versie deactiveren en verwijderen en handmatig de nieuwe .zip installeren. Je kunt de .zip hier vinden:

https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.0

**Comment by RichardPerdaan** [comment]
Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin. Deze is te installeren doormiddel van een reguliere update.
