### ISSUE TITLE
Bezorgdag wordt altijd getoond

### ISSUE THREAD

**Issue by aqdennis** [myparcelnl/woocommerce#582]
**Describe the bug**
In the checkout settings in the backend heb ik "show delivery day" uit staan, maar in de front end bij de bezorgopties zie ik nog altijd de bezorgdag.

**Expected behaviour**
Als "show delivery day" uit staat zou ik verwachten dat ik dus geen bezorgdag zie bij de bezorgopties.

**Screenshots**
![image](https://user-images.githubusercontent.com/48013601/109784046-f660fa80-7c0a-11eb-931d-2ff35e62e718.png)

**Details**
 - WordPress 5.6.2
 - WooCommerce 5.0.0
 - WooCommerce MyParcel 4.1.5
 - Theme: Storefront/Deli

**Comment by EdieLemoine** [comment]
Deze optie hebben we gisteren toevallig besproken! Ik heb hem als Feature gemarkeerd omdat deze optie hier nooit iets mee gedaan heeft, dus technisch gezien werkt hij naar behoren... Maar het is niet logisch. 

Wanneer we dit oppakken gaan we ervoor zorgen dat deze optie meteen overal de bezorgdatum verbergt, dus ook in het orderoverzicht en e-mails etc.

**Comment by aqdennis** [comment]
Workaround is top!  
De reden dat ik 'm uit wil is omdat we geen leveringsdatum kunnen garanderen. We zijn koffiebranders die branden op bestelling, dus ik kan de koffie niet zo van het schap halen en dezelfde dag nog op de bus doen.....dat duurt soms 1-2 dagen.

**Comment by DarkAllMan** [comment]
Ik heb deze optie ook op 0 staan, echter in de order confirmatie wordt nog wel steeds een dag meegestuurd.... dat is niet de bedoeling, idd, omdat we geen afleverdag garanderen.

**Comment by Mitchell-MyParcel** [comment]
@DarkAllMan : We hebben gekozen om 4.3.1. live te zetten omdat daar inmiddels best veel klanten op zaten te wachten. De optie om de bezorgdag te deactiveren in de mails, account en thank-you page hebben we al gebouwd en gaan we naar verwachting begin volgende week releaseen.

**Comment by DarkAllMan** [comment]
@Mitchell-MyParcel Ik heb inmiddels een testversie van Richard ontvangen.. ik ga deze even testen in mijn dev omgeving.

**Comment by RichardPerdaan** [comment]
@DarkAllMan,
Zou je kunnen bevestigen of dit probleem opgelost is door gebruik te maken van de testversie ?

**Comment by DarkAllMan** [comment]
Confirmed!

**Comment by DarkAllMan** [comment]
Bevestigd!

**Comment by RichardPerdaan** [comment]
@DarkAllMan,

Goed om te horen dat de oplossing heeft gewerkt. Inmiddels is deze versie [4.3.2 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.2)ook live gezet en kan worden geüpdatet via de reguliere updates.
