### ISSUE TITLE
Versie 4.1.4 Error export Brievenbuspakje

### ISSUE THREAD

**Issue by phemels** [myparcelnl/woocommerce#586]
Ik heb bij een order de zending veranderd van "Pakket" naar "Brievenbus" pakje, echter krijg deze er bij exporteren:

![image](https://user-images.githubusercontent.com/29940263/110252363-52b67800-7f85-11eb-9d56-d2d0ca3928e9.png)

Het gewicht is 0.2 Kg van het pakket, voldoet dus aan de eisen.

Als "Pakket" exporteren gaat wel goed.

Wanneer komt de nieuwe versie uit?

**Comment by Mitchell-MyParcel** [comment]
@phemels: De planning is dat de laatste pre-release volgende week als stable wordt uitgebracht. Daarin is dit probleem ook verholpen.

**Comment by phemels** [comment]
@Mitchell-MyParcel ok dank je.
Zit er in de Next version ook verwerkt dat je de zending kan aanpassen? b.v. van verzekerd naar niet verzekerd? als je dit nu aan past "onthoud" hij het niet.

![image](https://user-images.githubusercontent.com/29940263/110428836-437d1a80-80aa-11eb-8f20-72c206e43a10.png)

**Comment by RichardPerdaan** [comment]
Beste @phemels,
Dit punt is inderdaad meegenomen en zal weer moeten werken vanaf versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin

**Comment by phemels** [comment]
> Beste @phemels,
> Dit punt is inderdaad meegenomen en zal weer moeten werken vanaf versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin

@RichardPerdaan Verzekerd uitvinken wordt nog niet onthouden in versie 4.3.1

Omzetten naar Brievenbuspakje gaat wel goed.

**Comment by RichardPerdaan** [comment]
Beste @phemels ,
Dit onderdeel zal in de volgend release worden opgelost.
De volgende PR zal dit oplossen: #608

Vandaag worden de laatste testen gedaan en wij verwachten dinsdag versie 4.3.2 live te zetten

**Comment by RichardPerdaan** [comment]
Hi @phemels  ,
Het opslaan van de verzekering is opgelost in versie [4.3.2](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.2) van de MyParcel plugin
