### ISSUE TITLE
Missing translation files fr_FR

### ISSUE THREAD

**Issue by athiry** [myparcelnl/woocommerce#590]
Lots of webshops in Belgium are using language "French" and not "French (Belgium)" in general settings of Wordpress. This for a simple reason : many plugins are translated into French but do not contain "French (Belgium)" translation files. So for non-english speaking customers, they maximize their chances to have as much plugins as possible translated in french if they select "French" instead of "French (Belgium)" in Wordpress general settings. With such setting, My Parcel plugin pages don't get translated into French as there are missing translation files.

That's why it would be great to include fr_FR files (in addition to fr_BE) into myparcelbe plugin as well. 

It does not require a lot of job, just duplicate the file "languages/woocommerce-myparcel-fr_BE.po" and rename it to "languages/woocommerce-myparcel-fr_FR.po" + change 1 line inside : "Language: fr_BE\n" to "Language: fr_FR\n".

Note: issue also raised in myparcelbe repository.

**Comment by athiry** [comment]
See https://github.com/myparcelnl/woocommerce/pull/591 for proposed solution

**Comment by RichardPerdaan** [comment]
This has been fixed in version [4.3.1] (https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1) of the MyParcel WooCommerce plugin

**Comment by RichardPerdaan** [comment]
Hi @athiry ,
The fr_FR translation is included in version [4.3.2](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.2) of the MyParcel plugin.
