### ISSUE TITLE
WooCommerce leeg pakket gewicht meenemen icm DPZ

### ISSUE THREAD

**Issue by Chris707** [myparcelnl/woocommerce#592]
Graag bij een DPZ het  leeg pakket gewicht wordt meegenomen.
(dit ivm producten (kaarten briefpapier enz) en dit op grammen hangt)

Eventueel een extra veld?

<img width="809" alt="DPZLEEG" src="https://user-images.githubusercontent.com/25433104/110944419-bc93a080-833c-11eb-947a-0f7651c742d1.png">

**Comment by snelweg** [comment]
Dit is een zo stomme fout dat we er nooit over geklaagd hebben. Maar nu ik zie dat we niet de enige zijn die dit is opgevallen zou het wel leuk zijn als dit opgelost werd.

**Comment by Mitchell-MyParcel** [comment]
We have added a new field specifically for DPZ in the latest version like is suggested in the thread. There is one issue that will be fixed next Tuesday which results in the empty dpz weight to be added to the parcel weight (not the other way around) if both are filled.
