### ISSUE TITLE
Versie 4.3.0 ondersteunt geen ongefrankeerd voor EU zendingen. 

### ISSUE THREAD

**Issue by soedesh** [myparcelnl/woocommerce#599]
Wanneer je bij de zending pakket EU omzet naar ongefrankeerd, wordt dit niet opgeslagen. Bij het refreshen van de pagina wordt weer pakket getoond en geprint.

 - WordPress version: 5.6
 - WooCommerce version: 5.1.0 
 - WooCommerce MyParcel version: 4.3.0

Case : 01024307

**Comment by RichardPerdaan** [comment]
Dit is opgelost in versie [4.3.1 ](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.1)van de MyParcel WooCommerce plugin
