### ISSUE TITLE
wpm-config.json is not included in the .zip

### ISSUE THREAD

**Issue by soft79** [myparcelnl/woocommerce#605]
**Describe the bug**
wpm-config.json is missing in the released .zip although the file is in the git repo. This file is required for compatiblity with the WP-Multilang plugin and allows for translations of settings (e.g. 'Delivery options', 'Bezorgopties') in different languages.

**Steps to reproduce this behaviour**
Download a release, eg https://github.com/myparcelnl/woocommerce/releases/download/v4.3.1/woocommerce-myparcel.zip and see that the file is missing.

**Expected behaviour**
The file to be included.

**Comment by soft79** [comment]
File was introduced in #466

**Comment by RichardPerdaan** [comment]
Hi @soft79 ,
The wpm-config.json is included in version [4.3.2](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.2) of the MyParcel plugin.
