### ISSUE TITLE
'Home address only' remains selected in the checkout

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#61]
After a customer selects 'evening' or 'morning' delivery the option 'Home address only' is being selected as well. When the customer changes the choice for 'morning' or 'evening' back to 'standard delivery' the option 'Home address only' remains selected in the MyParcel checkout.

**Comment by TimBlom** [comment]
Case 00280527

**Comment by RichardPerdaan** [comment]
This feature request has been resolved in version 3.0.2 of the plugin
