### ISSUE TITLE
Default open list instead of map with takeaway

### ISSUE THREAD

**Issue by JasperMulder** [myparcelnl/woocommerce#611]
There is currently no option for selecting a default value while choosing takeaway. The default is now showing the map of the closest takeaway points, I'd like to show the list instead as a default option. Also, de buttons 'Lijst' and 'Kaart' don't have an active state for styling them.

**Comment by RichardPerdaan** [comment]
Duplicated #464

**Comment by Mitchell-MyParcel** [comment]
The active state issue will be solved in the delivery options entry mentioned in this thread. Opening the map or list by default has been added.
