### ISSUE TITLE
"pakjegemak" zending omzetten naar "brievenbuspakje" of "Ongefrankeerd" in backend geeft Error bij export

### ISSUE THREAD

**Issue by phemels** [myparcelnl/woocommerce#613]
Als een klant heeft gekozen voor "Pakjegemak" maar je wilt later iets naar het huisadres sturen, kun je in de backend de zending aanpassen naar b.v. "Ongefrankeerd".

![image](https://user-images.githubusercontent.com/29940263/112715393-36e92680-8ee0-11eb-9418-3569eccb54b7.png)

Echter bij export krijg je dan deze error:

![image](https://user-images.githubusercontent.com/29940263/112715373-1b7e1b80-8ee0-11eb-91ba-23bf577914ed.png)

Het zou heel handig zijn als dit wel kan worden aangepast van "Pakjegemak" naar huisadres (pakket/brievenbuspakje/ongefrankeerd), i.v.m. b.v. nalevering / garantie geval etc..

Je kunt het nu wel aanpassen, maar vervolgens komt er een error, omdat hij naar het Pakjegemak blijft kijken bij export :(

**Comment by wthijmen** [comment]
Hi @phemels,

Wij kunnen deze functionaliteit niet integreren omdat de eind gebruiker hierbij ook een rol speelt en keuze maakt voor pickup.

Als je zelf toch deze mogelijkheid wilt hebben kan je zelf een aanpassing verrichten in `includes/admin/OrderSettingsRows.php` en dan in de `getOptionRows` functie.

Hier kan je de volgende array vinden die begint met `'name' => self::OPTION_DELIVERY_TYPE`. In deze array staat het element `'custom_attributes'  => ['disabled => 'disabled']`. Zodra je deze verwijderd is het mogelijk om het aan te passen.

**Comment by phemels** [comment]
Dank je voor tip, het  werkt :)

**Comment by phemels** [comment]
Beste @wthijmen 

Het was toch geen goed idee, overal staat nu bij bezorg optie: shipment_options_delivery_standard,
En als ik van pickup naar standaard doe en vervolgens weer naar pickup, heb ik een FATAL ERROR op de website :(
En bij Barcode staat als er nog geen label is gemaakt: export_hint_no_label_created_yet

Niet zo mooi allemaal, enig idee hoe dit weer goed te krijgen is?

Groet Paul.

**Comment by phemels** [comment]
@wthijmen dit is de error tekst (de order is onbruikbaar hierdoor:

![image](https://user-images.githubusercontent.com/29940263/187264896-d1f4d19f-3362-4db6-8758-3bd4390d688b.png)
