### ISSUE TITLE
Brievenbuspakje wordt als pakket behandeld door MyParcel 4.3.1

### ISSUE THREAD

**Issue by phemels** [myparcelnl/woocommerce#614]
Brievenbuspakje product wordt behandeld als pakket tijdens het afrekenen!
Niet qua prijs maar wel voor Pakjegemak afleverlocatie, in de backend staat ook pakket

Op test site gaat het goed maar niet op live site.

Zie hier het product: https://alarmsysteemwebshop.nl/product/accupack-voor-de-ajax-hub/
Voorraad beheer staat uit.

![image](https://user-images.githubusercontent.com/29940263/112757141-bd892b00-8fe8-11eb-8b4d-d3346d065ae3.png)

**Comment by Mitchell-MyParcel** [comment]
@phemels: Ik denk dat dit komt door een instelling die niet goed staat (helemaal omdat het op de testomgeving wel goed gaat). Zou je deze instellingen willen controleren?

<img width="725" alt="Screenshot 2021-03-29 at 11 01 08" src="https://user-images.githubusercontent.com/69574208/112813381-6e8dd500-907e-11eb-8018-273aa69bb2c4.png">

Is de verzendklasse correct gekoppeld aan het producttype?

<img width="704" alt="Screenshot 2021-03-29 at 11 04 33" src="https://user-images.githubusercontent.com/69574208/112813566-9d0bb000-907e-11eb-8a4d-92ee7925303a.png">

Staat 'Toon' bij, geconfigureerd op ' Verzendmethode gekoppeld aan pakkettype' en niet op 'Alle verzendmethoden'.

Staan deze setting goed?

**Comment by phemels** [comment]
@Mitchell-MyParcel staat allemaal zoals het hoort, zie:

![image](https://user-images.githubusercontent.com/29940263/112841866-4a8fbb00-90a1-11eb-8970-7ab1da02a7e7.png)

![image](https://user-images.githubusercontent.com/29940263/112842039-70b55b00-90a1-11eb-846b-4b0eda39740b.png)

**Comment by RichardPerdaan** [comment]
Beste @phemels ,
Zou je willen proberen om `vast tarief` bij pakket weg te halen?
Ik heb namelijk een idee dat de verzendmethoden en de verzendklassen door elkaar lopen.

**Comment by phemels** [comment]
@RichardPerdaan Done, nu is het goed :)
