### ISSUE TITLE
Versie 4.3.2 Bewaar barcode in een notitie "geen barcode"

### ISSUE THREAD

**Issue by phemels** [myparcelnl/woocommerce#618]
Na update naar versie 4.3.2 komen er geen barcodes meer in de order notities (4.3.1 dubbel, nu geen)

![image](https://user-images.githubusercontent.com/29940263/113039352-d97eff00-9197-11eb-8c2a-af320ee46996.png)

![image](https://user-images.githubusercontent.com/29940263/113039441-f582a080-9197-11eb-832f-cb72d80016dc.png)

**Comment by RichardPerdaan** [comment]
Beste @phemels ,
Dit probleem is nauwkeurig getest en de notie zou na het printen van het label zichtbaar moeten zijn.

**Comment by phemels** [comment]
Ok, dacht meteen al.
Maar na het printen staat hij er inderdaad bij, wel dubbel.

![image](https://user-images.githubusercontent.com/29940263/113134500-2955d880-9221-11eb-96b1-3b072d523b17.png)

**Comment by phemels** [comment]
@RichardPerdaan moet deze tekst dan niet veranderen in "geprint"

![image](https://user-images.githubusercontent.com/29940263/113136970-42ac5400-9224-11eb-9505-10f9665a851d.png)

**Comment by snelweg** [comment]
Ik heb ook nog steeds die dubbele vermelding als order is afgerond. Staat nogal stom en voegt niets toe, zeker omdat er altijd iets over de track en trace code staat terwijl meeste orders digitale postzegels zijn! 
Wanneer wordt dat nu eens opgelost?

![myparcel2_1](https://user-images.githubusercontent.com/1257901/114751230-2ac0ee00-9d55-11eb-9a4b-2e725290bfe6.png)

**Comment by phemels** [comment]
Versie 4.4.5. geeft 3x barcode in notities !! (vorige versie 2x)

![image](https://user-images.githubusercontent.com/29940263/131623560-b365ef48-2676-425e-85a3-4cee914d0f06.png)

**Comment by RichardPerdaan** [comment]
Dit probleem is gefixed met minimaal 5.0.0-beta.1 van de MyParcel plugin
