### ISSUE TITLE
As a client I want to save the package type without seeing a fatal error in the logs 

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#619]
**Describe the bug**
Saving a package type on the 'orders' page results in a fatal error

**Steps to reproduce this behaviour**
1. Go to 'orders'
2. Click on 'package type'
3. Change package type (parcel to mailbox)
4. Click on 'save'
5. Red cross on save button

**Expected behaviour**
The package type should be saved without any issues

**Error**
<code>PHP Fatal error:  Uncaught TypeError: Return value of OrderSettings::getExtraOptions() must be of the type array, string returned in /home/redacted/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/OrderSettings.php:465\nStack trace:\n#0 /home/redacted/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmypa-admin.php(589): OrderSettings->getExtraOptions()\n#1 /home/redacted/public_html/wp-includes/class-wp-hook.php(292): WCMYPA_Admin->save_shipment_options_ajax()\n#2 /home/redacted/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()\n#3 /home/redacted/public_html/wp-includes/plugin.php(484): WP_Hook->do_action()\n#4 /home/redacted/public_html/wp-admin/admin-ajax.php(187): do_action()\n#5 {main}\n  thrown in /home/redacted/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/OrderSettings.php on line 465', referer: https://www.redacted.nl/wp-admin/edit.php?post_type=shop_order</code>

**Additional information**
Can be recreated with order 539 on our test invironment. Possibly a conflict between shipping options?

**Comment by RichardPerdaan** [comment]
This issue is resolved in [4.4.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.4.0) of the MyParcel plugin
