### ISSUE TITLE
As a client I do not want to show the shipping options when all the products are virtual products

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#620]
**Describe the bug**
When I add a virtual product to the cart the shipping options will be shown in the checkout. This should not be the case.

**Steps to reproduce this behaviour**
1. Add a virtual product to the cart
2. Go to the checkout
3. See the shipping options

**Expected behaviour**
The shipping options should be hidden

**Comment by Mitchell-MyParcel** [comment]
This is fixed in the latest version.
