### ISSUE TITLE
As a client I want the MyParcel plugin to support the plugin 'WooCommerce side cart"

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#621]
**Is your feature request related to a problem?**
Using this plugin causes the checkout to keep reloading

**Comment by TimBlom** [comment]
Case 01038752

**Comment by adem-demir** [comment]
https://nl.wordpress.org/plugins/side-cart-woocommerce/

**Comment by adem-demir** [comment]
For time being you can add the checkout page at the settings of side cart for don't show at page. See attached example

![image](https://user-images.githubusercontent.com/37372250/114531192-f6153f80-9c4b-11eb-911a-5da943f8af25.png)
