### ISSUE TITLE
_myparcel_delivery_options is not hidden in checkout

### ISSUE THREAD

**Issue by TeunSmit** [myparcelnl/woocommerce#623]
**Describe the bug**
When the checkout options are loaded it will show the following field: name="_myparcel_delivery_options" 
![Checkout • Naturally Granola 2021-04-08 09-46-10](https://user-images.githubusercontent.com/54140671/113995034-2b89e980-9856-11eb-88ce-44450b0d70bc.png)

**Expected behaviour**
The field should be hidden. 

**Additional context**
If type="hidden" is used instead of hidden="hidden" then the field will be hidden.

**Comment by RichardPerdaan** [comment]
This issue is resolved in [4.4.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.4.0) of the MyParcel plugin
