### ISSUE TITLE
As a client I do not want to show 'soort zending' in my WooCommerce mail

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#627]
The client deactivated the following function:
![image](https://user-images.githubusercontent.com/22811561/114538463-b6eaec80-9c53-11eb-8b4c-e939ad0f4c89.png)

This is still visible:
![image](https://user-images.githubusercontent.com/22811561/114538413-aaff2a80-9c53-11eb-81db-fb8832b8e33d.png)

**Comment by TimBlom** [comment]
Case 01045677

**Comment by noalert** [comment]
Any timeframe on this? We're holding back from updating (we're still at 4.1.5) because of this issue.

**Comment by RichardPerdaan** [comment]
This issue is resolved in [4.4.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.4.0) of the MyParcel plugin
