### ISSUE TITLE
As a client I do not want to automatically export shipments when 'Afhalen in winkel' is selected

### ISSUE THREAD

**Issue by NikitaMyParcel** [myparcelnl/woocommerce#636]
**Is your feature request related to a problem?**
When 'Afhalen in winkel' is selected by the customer, it will automatically export after payment. It should not export as it is not necessary to create a label.

**Describe alternatives you've considered**
For now the shipping method 'Afhalen in winkel' is linked to a label without barcode (letter) so I don't create barcodes I do not use.

**Comment by RichardPerdaan** [comment]
In version [4.13.1](https://github.com/myparcelnl/woocommerce/releases/tag/v4.13.1) we added a function that the orders that are using "local_pickup" will be excluded for the MyParcel export.

I will close the issue as it was fixed in an earlier version of the plugin
