### ISSUE TITLE
As a client I want my customers to be able to change their address on the account page

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#644]
**Describe the bug**
When the MyParcel plugin is activated the customers are not able to change their address on the account page. When the MyParcel plugin is deactivated this issue does not occur.

**Steps to reproduce this behaviour**
1. Go to 'My Account'
2. Click on 'Address'
3. Edit the country of an address
4. Nothing happens

**Expected behaviour**
The country should be selected

**Screenshots**
![image](https://user-images.githubusercontent.com/22811561/117163025-8c5c0180-adc3-11eb-85ec-9bd495e0f751.png)
![image](https://user-images.githubusercontent.com/22811561/117163105-a1d12b80-adc3-11eb-8baa-debd6a3626d2.png)

**Comment by RichardPerdaan** [comment]
@TimBlom This problem is related to the MyParcel address fields. Once this setting is on, it is not possible to change the country. As soon as the MyParcel address fields are turned off, it will work

**Comment by TimBlom** [comment]
This issue also occurs by changing the region.
