### ISSUE TITLE
As a client I directly want to get feedback after changing the package type

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#653]
**Describe the bug**
Earlier the 'orders' page refreshed after changing the the package type. Now this does not work

**Steps to reproduce this behaviour**
1. Go to 'Orders'
2. Click on 'package type' of an order
3. Change package type
4. Save the settings

**Expected behaviour**
1) The page should refresh
or
2) The package type should change after saving

**Comment by RichardPerdaan** [comment]
The modification has been approved through the following PR: [674](https://github.com/myparcelnl/woocommerce/pull/674)
This change will be included in the next release.
