### ISSUE TITLE
"ReferenceError: id is not defined" when adding new address on account page

### ISSUE THREAD

**Issue by jeroenlammerts** [myparcelnl/woocommerce#660]
**Describe the bug**
"ReferenceError: id is not defined" on account page. When adding a new address this error occurs when selecting a country from the select2 field.

**Steps to reproduce this behaviour**
1. Go to '/en/my-account/edit-address/billing/'
2. Click on 'Country / Region'
3. Click a country'
4. The error occurs and is shown in the console

**Expected behaviour**
The clicked country is used as value in the select2 field. 

**Screenshots**
<img width="2402" alt="Screenshot 2021-06-16 at 15 53 24" src="https://user-images.githubusercontent.com/4282711/122375029-271f3280-cf63-11eb-83fe-b51a78b369bb.png">

**Details**
 - WordPress version: 5.7.2
 - WooCommerce version: 5.3.0
 - WooCommerce MyParcel version: 4.4.0
 - Theme: custom

**Comment by EdieLemoine** [comment]
Duplicates #644

**Comment by RichardPerdaan** [comment]
Fixed in [4.4.1](https://github.com/myparcelnl/woocommerce/releases/tag/v4.4.1) of the MyParcel WooCommerce plugin
