### ISSUE TITLE
Uitzetten "Bezorginformatie" in email als levering niet door POSTNL is.

### ISSUE THREAD

**Issue by Herbert-webvriend** [myparcelnl/woocommerce#662]
In de email komt onder het orderoverzicht de Bezorg informatie. Het geval is dat de bezorging niet altijd door POSTNL gedaan wordt. Het is namelijk zo bij bepaalde postcodes er zelf de bezorging gedaan wordt.

Probleem is dat het blokje Bezorg informatie uit POSTNL plugin altijd getoond wordt.

Kan iemand mij helpen dit uit te schakelen? 

Versie van WordPress: 5.7.2
Versie van WooCommerce:  5.4.1
WooCommerce PostNL Versie: 4.3.3

<img width="398" alt="Schermafbeelding 2021-06-18 om 09 31 03" src="https://user-images.githubusercontent.com/86099708/122528847-0ddabc80-d01d-11eb-99a8-83576f12121d.png">

**Comment by TimBlom** [comment]
+1: As a client I would like to see an option to hide all the information above.

**Comment by lukasknol** [comment]
Hoi Herbert-webvriend,

Ik loop tegen hetzelfde probleem aan. Heb jij ondertussen een oplossing gevonden? Ik wil het liefst het hele blok "Bezorginformatie" verwijderen op de "thankyou" pagina en email.
