### ISSUE TITLE
As a client I do not want a double export when using the bulk actions at the bottom

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#664]
**Describe the bug**
When you use the bulk actions at the bottom of the 'orders' page the export is doubled.

**Steps to reproduce this behaviour**
1. Go to 'Orders'
2. Select your orders
3. Scroll down to 'Bulk actions'
4. Use the bulk export

**Expected behaviour**
The orders should only be exported once.

**Comment by RichardPerdaan** [comment]
When you have exported and printed the order you will receive 1 label back in WooCommerce but in the backoffice there are 2 labels.
