### ISSUE TITLE
As a client I always want to add the age check when it is activated for at least one product in the order

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#669]
**Describe the bug**
When the customer orders multiple products and the age check is deactivated for one of the products the age check is not added as a shipping option

**Steps to reproduce this behaviour**
1. Order two products. One with age check and one without.
2. Click on 'the package type'
3. See that age check is deactivated.

**Expected behaviour**
The age check should be added as a shipping option

**Comment by RichardPerdaan** [comment]
Fixed in 4.4.4 of the MyParcel WooCommerce plugin
