### ISSUE TITLE
Edit a old order gives fatal error and brakes order

### ISSUE THREAD

**Issue by phemels** [myparcelnl/woocommerce#701]
I changed an old order, I added it to a customer

And at that moment I got an fatal error of the website caused by this plugin.
Now the order is broken :(

See:
WordPress versie 5.8.1
Huidig thema: Flatsome Child (versie 3.0)
Huidige plugin: WooCommerce MyParcel (versie 4.4.5)
PHP versie 7.3.30

Foutdetails
===========
Een fout van het type E_ERROR werd veroorzaakt op regelnummer 914 van het bestand /home/pahedomotica/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmp-export.php. Foutmelding: Uncaught TypeError: Return value of WCMP_Export::getOrderShippingClass() must be of the type int or null, string returned in /home/pahedomotica/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmp-export.php:914
Stack trace:
#0 /home/pahedomotica/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/class-wcmp-export.php(958): WCMP_Export->getOrderShippingClass(Object(Automattic\WooCommerce\Admin\Overrides\Order), 'free_shipping:3')
#1 /home/pahedomotica/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/OrderSettings.php(428): WCMP_Export->getPackageTypeFromOrder(Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(MyParcelNL\Sdk\src\Adapter\DeliveryOptions\DeliveryOptionsV2Adapter))
#2 /home/pahedomotica/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/OrderSettings.php(234): OrderSettings->setPackageType()
#3 /home/pahedomotica/public_html/wp-content/plugins/woocommerce-myparcel/includes/admin/OrderSettings.php(126): OrderSetti

![image](https://user-images.githubusercontent.com/29940263/133490840-7cf86ad8-7583-4704-b14c-5b1764068855.png)

![image](https://user-images.githubusercontent.com/29940263/133492254-ab018da3-8578-4f30-a69f-cc43bfc109d2.png)

**Comment by Mitchell-MyParcel** [comment]
Fixed in latest release

**Comment by phemels** [comment]
@Mitchell-MyParcel 
Heb de plug-in geupdate, maar gelijk een e-mail met "Uw site heeft een technisch probleem"!!

Als je hulp nodig hebt met dit probleem, kan je gevraagd worden om de volgende informatie:
WordPress versie 5.8.2
Huidig thema: Flatsome Child Test (versie 3.0)
Huidige plugin: WooCommerce MyParcel (versie 4.8.0)
PHP versie 7.3.33



Foutdetails
===========
Een fout van het type E_ERROR werd veroorzaakt op regelnummer 109 van het bestand /home/pahedomotica/test.pahedomotica.nl/wp-content/plugins/woocommerce-myparcel/vendor/myparcelnl/sdk/src/Adapter/DeliveryOptions/AbstractPickupLocationAdapter.php. Foutmelding: Uncaught TypeError: Return value of MyParcelNL\Sdk\src\Adapter\DeliveryOptions\AbstractPickupLocationAdapter::getCity() must be of the type string, null returned in /home/pahedomotica/test.pahedomotica.nl/wp-content/plugins/woocommerce-myparcel/vendor/myparcelnl/sdk/src/Adapter/DeliveryOptions/AbstractPickupLocationAdapter.php:109
Stack trace:
#0 /home/pahedomotica/test.pahedomotica.nl/wp-content/plugins/woocommerce-myparcel/includes/admin/OrderSettings.php(345): MyParcelNL\Sdk\src\Adapter\DeliveryOptions\AbstractPickupLocationAdapter->getCity()
#1 /home/pahedomotica/test.pahedomotica.nl/wp-content/plugins/woocommerce-myparcel/includes/admin/OrderSettings.php(278): MyParcelNL\WooCommerce\includes\admin\OrderSettings->setPickupLocation()
#2 /home/pahedomotica/test.pahedomotica.nl/wp-content/plugins/woocommerce-myparcel/includes/admin/OrderSettings.php(152): MyParcelNL\WooCommerce\includes\admin\OrderSettings->setAllData()
#3 /home/pahedomotica/test.pahedomotica.nl/wp-content/plugins/woocommerce-myparcel/includ

**Comment by Mitchell-MyParcel** [comment]
@phemels: We kunnen er meteen even naar kijken. Je hebt ooit login details met ons gedeeld voor jouw testomgeving. Zou je dat misschien via een case weer naar ons kunnen sturen?

**Comment by phemels** [comment]
@Mitchell-MyParcel ik heb een gebruiker aangemaakt voor je op het "bekende" e-mail adres.

**Comment by EdieLemoine** [comment]
@phemels Deze change zou je probleem moeten oplossen: myparcelnl/sdk#379. Ik heb direct even een nieuwe issue hiervoor aangemaakt: #757

**Comment by RichardPerdaan** [comment]
Aanpassing is terug te vinden in de volgende PR: https://github.com/myparcelnl/sdk/pull/403
