### ISSUE TITLE
As a client I want the delivery options to be shown on the right position

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#707]
**Describe the bug**
When using the function 'Position delivery options' I choose for 'After subtotals' but the options are shown below the totals.

**Steps to reproduce this behaviour**
1. Go to 'Checkout settings'
2. Select on 'After subtotals' in the function 'Position delivery options'
3. Go to the checkout
4. See that the wrong position is being used

**Expected behaviour**
The delivery options should be after the subtotals. Adding the delivery options after the shipping methods would be a great addition to this setting.

**Screenshots**
![image](https://user-images.githubusercontent.com/22811561/136347220-dc98c57c-c2e1-4a59-acbd-9370d42fda00.png)

![image](https://user-images.githubusercontent.com/22811561/136348993-c5105be9-c877-4926-a7aa-a3ec2bb0e609.png)

![image](https://user-images.githubusercontent.com/22811561/136347945-6808d038-22b5-4f19-aae8-cf79924c0a5b.png)

**Comment by RichardPerdaan** [comment]
Helaas heeft WooCommerce geen hook waar de delivery options goed op zal gaan werken (bij het overzicht van de verzendmethoden). Meerdere hooks geprobeerd maar doordat de delivery options meer ruimte nodig heeft, wat niet beschikbaar is, zal de delivery options niet juist werken.
