### ISSUE TITLE
shipping options not respecting country of delivery

### ISSUE THREAD

**Issue by codeagencybe** [myparcelnl/woocommerce#709]
**Describe the bug**
When a customer with delivery address in BE orders, it loads both Bpost AND PostNL (and DPD) options for the client to choose. 
Especially with the pickup points, this is very confusing and returns a mess because some pickup points from PostNL do not apply for Belgian customers. 

**Steps to reproduce this behaviour**
1. enable Bpost and PostNL in Myparcel plugin
2. create a shipping zone for BE and seperate for NL
3. add flat rate option to both shipping zone so each has 1 flat rate
4. set the price for the shipping method

**Expected behaviour**
If a client from BE orders, only show the Bpost options. 
If a client from NL orders, only show the PostNL options. 
I was expecting an option/filter in the shipping options while adding them to the shipping zone. 
To restrict the loading of the shipping method to a specific country. 

**Details**
 - WordPress version: 5.8.1
 - WooCommerce version: 5.7.1
 - WooCommerce MyParcel version: 4.4.1
 - Theme: Astrawp - 3.7.3

**Comment by RichardPerdaan** [comment]
Hi @codeagencybe ,

Thank you for posting your issue.
The pickup locations that are visible in the plugin are locations that are actually possible.

What we do is collect the possible options from Bpost, PostNL and DPD. So de pickup locations that your customer 
see, when ordering their order, are locations that are really possible.
