### ISSUE TITLE
Order Overview showing delivery times when we do not use them.

### ISSUE THREAD

**Issue by DarkAllMan** [myparcelnl/woocommerce#710]
Since the latest update Myparcel is showing delivery dates in the order overview:
![image](https://user-images.githubusercontent.com/1582343/137112469-05a6818f-5dfd-4efa-8ef2-a9080642a94b.png)
Excellent feature, if you give customer the possibility to choose this. We do not and therefor this information is overkill in our overview. Please give us the option to disable this information in the overview.

**Comment by DarkAllMan** [comment]
An update about this was promised some time ago. When can I expect the fix?

**Comment by DarkAllMan** [comment]
Today installed update, but was not fixed :(

**Comment by DarkAllMan** [comment]
Is anyone taking a look as this?

**Comment by RichardPerdaan** [comment]
Solved with [v4.12.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.12.0)
