### ISSUE TITLE
customs declaration items description too long

### ISSUE THREAD

**Issue by TeunSmit** [myparcelnl/woocommerce#711]
If your customs declaration items description is longer then 30 characters long then you will get this API error: 
data.shipments[0].customs_declaration.items[0].description - data.shipments[0].customs_declaration.items[0].description should be 30 characters or less - Shipment validation error

Label description has the same error, but this is solved by cutting the description at 42 characters and adding three dots. 

If it is possible do the same for the item description.

**Comment by RichardPerdaan** [comment]
fix: https://github.com/myparcelnl/sdk/pull/345

**Comment by Mitchell-MyParcel** [comment]
Fixed in latest release
