### ISSUE TITLE
: Duplicate queries in wordpress backend #706 

### ISSUE THREAD

**Issue by fjkuypers** [myparcelnl/woocommerce#732]
Bug report in : https://github.com/myparcelnl/woocommerce/pull/706#  is nog niet helemaal opgelost. 
Ik er heb daar melding van gemaakt maar er komt geen reactie.

@joerivanveen @RichardPerdaan @EdieLemoine

Team, de fix blijkt NOG NIET GOED te werken !

Met jullie laatste release is het wel al beter, maar als ik mijn WooCommerce Dashboard open. krijg ik weer de die onnodig veel duplicate queries. Als ik de myParcel plugin uitzet , zijn die duplicate queries ook weg. Als de plugin weer aanzet zijn de duplicate queries er ook weer.

Jullie mogen graag bij mij meekijken... of als ik ergens een dump van moet sturen hoor ik het wel

Hoor graag van jullie !

**Comment by joerivanveen** [comment]
Beste @fjkuypers,
Gaat het in het dashboard om Woocommerce -> Home en Woocommerce -> Customers? Daar zie ik inderdaad ook nog / weer duplicate queries verschijnen.
Zijn de duplicate queries ook aanwezig aan de voorkant van de site, de store waar de consumenten gebruik van maken? Daar zie ik ze zelf niet verschijnen op dit moment.

**Comment by fjkuypers** [comment]
@joerivanveen @RichardPerdaan @EdieLemoine
Team, komt er nog een vervolg op de bugfix?

Groeten
Frank

**Comment by fjkuypers** [comment]
@joerivanveen 
Dag Joeri,
Ja inderdaad alleen op:
-dashboard van Woocommerce -> Home  
- Woocommerce -> Customers?
Ergens anders ben ik het (nog) niet weer tegengekomen. Ook niet aan de voorzijde/klanten kant.

Op dit moment is is het niet meer zo storend als dat het was voor jullie laatste fix, maar helemaal weg is het nog
niet. 

Laat maar weten als ik iets kan doen/helpen.  ( Dumps, tests etc.... )

Groeten
Frank

**Comment by joerivanveen** [comment]
@fjkuypers bedankt voor de info, we maken morgen een nieuwe story om deze issue te fixen.

**Comment by EdieLemoine** [comment]
Hi @fjkuypers, in onze [v5.0.0 beta](https://github.com/myparcelnl/woocommerce/releases) versies zou de performance van de hele plugin een stuk beter moeten zijn.

Zie [deze issue](https://github.com/myparcelnl/woocommerce/issues/1057) voor meer informatie. We horen het graag als je nog steeds performance issues ervaart.
