### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 1 passed to WCMP_Upgrade_Migration_v4_1_0::roundUpToMatch()

### ISSUE THREAD

**Issue by nilsdewilde** [myparcelnl/woocommerce#736]
**Describe the bug**
Getting this error after upgrading from 3.2.0 to 4.6.0

Fatal error: Uncaught TypeError: Argument 1 passed to WCMP_Upgrade_Migration_v4_1_0::roundUpToMatch() must be of the type int, null given, called in /www/wp-content/plugins/woocommerce-myparcel/migration/wcmp-upgrade-migration-v4-1-0.php on line 200 and defined in /www/wp-content/plugins/woocommerce-myparcel/migration/wcmp-upgrade-migration-v4-1-0.php:212 Stack trace: #0 /www/wp-content/plugins/woocommerce-myparcel/migration/wcmp-upgrade-migration-v4-1-0.php(200): WCMP_Upgrade_Migration_v4_1_0->roundUpToMatch(NULL, Array) #1 /www/wp-content/plugins/woocommerce-myparcel/migration/wcmp-upgrade-migration-v4-1-0.php(81): WCMP_Upgrade_Migration_v4_1_0->correctPostNlInsurance() #2 /www/wp-content/plugins/woocommerce-myparcel/migration/wcmp-upgrade-migration.php(15): WCMP_Upgrade_Migration_v4_1_0->migrate() #3 /www/wp-content/plugins/woocommerce-myparcel/migration/wcmp-upgrade-migration-v4-1-0.php(55): migration\WCMP_Upgrade_Migration->__construct() #4 /www/wp-content/plugins/woocommerce-myparcel/migration/wcmp-upgrade-migration in /www/wp-content/plugins/woocommerce-myparcel/migration/wcmp-upgrade-migration-v4-1-0.php on line 212

**Steps to reproduce this behaviour**
upgrade from 3.2.0 to 4.6.0 

**Details**
 - WordPress version: 5.8.2
 - WooCommerce version: 5.9.0
 - WooCommerce MyParcel version: 3.2.0

**Comment by RichardPerdaan** [comment]
Hi @nilsdewilde .
Is this problem still present when you update the plugin to the latest version ([v4.11.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.11.0)) ?

**Comment by RichardPerdaan** [comment]
Hi @nilsdewild ,

I have tried to reproduce this problem several times. But unfortunately I don't see the problem. 

Since there has no response since April 19, I am closing the issue.

If this problem is still present, you can always open the issue again.
