### ISSUE TITLE
State in US not selected when exporting order

### ISSUE THREAD

**Issue by larsrengersen** [myparcelnl/woocommerce#739]
**Describe the bug**
State is not selected when I export an order to MyParcel

**Steps to reproduce this behaviour**
1. Export order for shipping 
2. Go to draft labels / shipments and select item
3. Edit item and manually select state is US

**Expected behaviour**
State automatically pre popoulated

**Screenshots**

**Details**
 - WordPress version: 5.8.2
 - WooCommerce version: 5.9.0
 -  WooCommerce MyParcel version: 4.6.0
 - Theme: Generatepress

**Additional context**

**Comment by Mitchell-MyParcel** [comment]
Fixed in latest release.

**Comment by larsrengersen** [comment]
Thanks! Works as expected now.
