### ISSUE TITLE
As a client I want to be able to export pickup shipments with 'return if no answer' selected by default

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#748]
**Describe the bug**
As a client I want to select 'Return if no answer' by default and be able to export shipments with a pickup delivery option.

**Steps to reproduce this behaviour**
1. Save 'Return if no answer' as a default shipping method via 'WooCommerce' > 'MyParcel' > 'PostNL'
2. Create an order with a pickup delivery option
3. Create a shipment
4. See an error

**Expected behaviour**
The order should be exported without the shipping option 'Return if no answer'

**Comment by RichardPerdaan** [comment]
fixed and tested with the latest version of the plugin (4.11.0)
