### ISSUE TITLE
Pickup Points is default selected without option to deselect.

### ISSUE THREAD

**Issue by DarkAllMan** [myparcelnl/woocommerce#760]
### Plugin version

4.8.1

### WooCommerce version

6.0.0

### WordPress version

5.8.3

### PHP version

7.4.27

### What went wrong?

I use MyParcel with Pickup Points, but **NOT** PostNL features.
![image](https://user-images.githubusercontent.com/1582343/148918978-35617a30-b504-4711-a614-3a1d691f313e.png)
Since one of the last updates, it seems that Pickup Point is now default selected and the radio option: Default Delivery (home address) is now gone. So my customers can only send to pickup points if I enable this.
![image](https://user-images.githubusercontent.com/1582343/148919141-fb7ae3d5-2041-493f-a1a1-207db6dbe1f4.png)

### Reproduction steps

Put items in shopping cart (enough to make it a package)
Then go to checkout.
I disabled pickuppoints on my production site, please check staging site: https://test.lievelabels.nl

**Comment by Mitchell-MyParcel** [comment]
@DarkAllMan : We cannot reproduce this so we will probably need to dive into this. One check question. Why is 'PostNL bezorging' disabled? This can be enabled without all the delivery options and that would result in the 'Home delivery' options being available.

**Comment by DarkAllMan** [comment]
ok, maybe the update changed some settings names? Cause it stopped working.
I will enable this feature without showing the delivery dates and check if this solves my issue.

**Comment by Mitchell-MyParcel** [comment]
@DarkAllMan Let us know if this fixes it. I have added my settings above for reference.

**Comment by DarkAllMan** [comment]
That actually did it. Thank you for your quick response!
