### ISSUE TITLE
As a client I want to make the +-symbol invisible

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#765]
### What problem does this feature solve?

I only want to show what the full price is. My clients think this will add extra shipping costs on top of the regular shipping costs.

### What should the solution look like?

Make the +-symbol optional.

**Comment by EdieLemoine** [comment]
Have you tried the surcharge option?

**Comment by TimBlom** [comment]
@EdieLemoine as a client I want to show the full price, not only the surcharge.

**Comment by EdieLemoine** [comment]
Okay, have you tried not using the surcharge option? Because that's what the surcharge true/false option is for.

**Comment by RichardPerdaan** [comment]
This issue is solved with the surcharge option : [v4.3.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.3.0)
