### ISSUE TITLE
No export if label description is higher than 45 characters

### ISSUE THREAD

**Issue by TeunSmit** [myparcelnl/woocommerce#766]
### Plugin version

4.8.2

### WooCommerce version

6.1.0

### WordPress version

5.8.3

### PHP version

7.4

### What went wrong?

If you select too many options in the settings for label description the export will crash.
<img width="694" alt="MyParcel ‹ wordpress — WordPress 2022-01-19 16-23-02" src="https://user-images.githubusercontent.com/54140671/150160951-4ff409fb-c8e2-4212-b959-ed4a079c1822.png">

Workaround is to clear the setting or only use order_nr.

### Reproduction steps

1. Go to your default exportsettings and add [PRODUCT_NAME] to the field a few times (easiest way to reproduce)
2. Try to export an order. (may be an older order)
3. The export will crash and give you a API error stating that the description field has a maximum length of 45 characters.

**Comment by RichardPerdaan** [comment]
Solved with: https://github.com/myparcelnl/sdk/pull/408
