### ISSUE TITLE
As a client I want to use the filter wc_myparcel_recipient

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#777]
### What problem does this feature solve?

With this filter I can exclude orders with 'pick up at store' as a shipping method, so the shipping labels are not being created.

### What should the solution look like?

The filter wc_myparcel_recipient should be available again

**Comment by BwamNL** [comment]
I submitted this ticket via support. I used this filter to remove recipients info so no label would be created when it was a local_pickup shipping method.

Maybe a better solution would be to create a filter to check if a MyParcel label should be created based on the shipping method.

**Comment by RichardPerdaan** [comment]
In version [4.13.1](https://github.com/myparcelnl/woocommerce/releases/tag/v4.13.1) we added a function that the orders that are using "local_pickup" will be excluded for the MyParcel export.

I will close the issue as it was fixed in an earlier version of the plugin
