### ISSUE TITLE
Invalid Full street error after install latest version

### ISSUE THREAD

**Issue by Mitchell-MyParcel** [myparcelnl/woocommerce#781]
### Plugin version

4.9.0

### WooCommerce version

all

### WordPress version

all

### PHP version

Supported

### What went wrong?

After install customers get:

`Een fout van het type E_ERROR werd veroorzaakt op regelnummer 162 van het bestand /home/customer/www/myparcel.nl/public_html/wp-content/plugins/woocommerce-myparcel/vendor/myparcelnl/sdk/src/Helper/SplitStreet.php. Foutmelding: Uncaught MyParcelNL\Sdk\src\Exception\InvalidConsignmentException: Invalid full street supplied:`

### Reproduction steps

Install latest version.

**Comment by Mitchell-MyParcel** [comment]
We will release a new version as soon as possible.

**Comment by directict-stephan** [comment]
Wij ervaren dezelfde error met het gebruik van jullie WordPress Myparcel plugin. Na het gebruik van een huisnummer toevoeging genereert hij dezelfde error. Een deel van de bestellingenlijst / besteloverzicht valt dan uit.

**Comment by RichardPerdaan** [comment]
Beste @directict-stephan,

Wij hebben 10 min geleden een nieuwe versie van de WooCommerce MyParcel plugin live gezet.
Met deze versie ([4.9.1](https://github.com/myparcelnl/woocommerce/releases/tag/v4.9.1)) moet dit probleem opgelost zijn.

**Comment by eskadesign** [comment]
Beste Richard,
Voor een klant draaien wij de laatste versie 4.9.1 maar het probleem blijft. Wij kunnen tevens geen bestellingen in bulk selecteren en een deel van het order overzicht valt van het scherm:

`Fatal error: Uncaught MyParcelNL\Sdk\src\Exception\InvalidConsignmentException: Invalid full street supplied: Lienaertsstraat in /home/678401.cloudwaysapps.com/sjsrcwhtcb/public_html/wp-content/plugins/woocommerce-myparcel/vendor/myparcelnl/sdk/src/Helper/SplitStreet.php:162

Stack Trace
1.	
MyParcelNL\Sdk\src\Helper\SplitStreet::validate('Lienaertsstraat', 0, Array)
/home/678401.cloudwaysapps.com/sjsrcwhtcb/public_html/wp-content/plugins/woocommerce-myparcel/vendor/myparcelnl/sdk/src/Helper/SplitStreet.php:100
2.	
MyParcelNL\Sdk\src\Helper\SplitStreet::splitStreet('Lienaertsstraat', 'NL', 'NL')
/home/678401.cloudwaysapps.com/sjsrcwhtcb/public_html/wp-content/plugins/woocommerce-myparcel/vendor/myparcelnl/sdk/src/Model/Recipient.php:353
3.	
MyParcelNL\Sdk\src\Model\Recipient->setFullStreet('NL')
/home/678401.cloudwaysapps.com/sjsrcwhtcb/public_html/wp-content/plugins/woocommerce-myparcel/vendor/myparcelnl/sdk/src/Model/Recipient.php:105
4.	
/home/678401.cloudwaysapps.com/sjsrcwhtcb/public_html/wp-content/plugins/woocomm in /home/678401.cloudwaysapps.com/sjsrcwhtcb/public_html/wp-content/plugins/woocommerce-myparcel/vendor/myparcelnl/sdk/src/Helper/SplitStreet.php on line 162
`
