### ISSUE TITLE
Instore pickup shows delivery information on succes page

### ISSUE THREAD

**Issue by TeunSmit** [myparcelnl/woocommerce#791]
### Plugin version

4.9.1

### WooCommerce version

6.1.1

### WordPress version

5.9.0

### PHP version

7.4

### What went wrong?

When a customer places an order with instore pickup as shipping method, the succes page shows the delivery information. There is no delivery information needed because this order will not be shipped.

The delivery information is also visible in the email communication with the customer.

### Reproduction steps

1. Have an instore pickup shipping method ready
2. Place an order with instore pickup as shipping method
3. On the succes page after placing the order you will see "delivery information" at the bottom of the page
<img width="1441" alt="Checkout – MyParcel test " src="https://user-images.githubusercontent.com/54140671/153206083-7e5e9dfc-ed45-4162-99b6-a6a86c3951a7.png">

**Comment by RichardPerdaan** [comment]
Solved with [v4.12.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.12.0)
