### ISSUE TITLE
As a client I do not want to get an error in the checkout if my customer splits his address in the two address fields

### ISSUE THREAD

**Issue by TimBlom** [myparcelnl/woocommerce#795]
### Plugin version

4.9.1

### WooCommerce version

6.2.0

### WordPress version

5.8.3

### PHP version

7.4.16

### What went wrong?

I get an error if I will in the house number on the second address field

![image](https://user-images.githubusercontent.com/22811561/153585105-f7b474e6-1ec2-477e-ab31-f08e7744b38e.png)

### Reproduction steps

1. Deactivate the MyParcel address fields
2. Go to the checkout
3. fill in the street name on address field 1 and the house nummber on address field 2

**Comment by RichardPerdaan** [comment]
The customer should use the MyParcel address fields.
