### ISSUE TITLE
As a client I want my product weights in LBS and a good conversion to grams

### ISSUE THREAD

**Issue by Barry020** [myparcelnl/woocommerce#805]
### Plugin version

4.9.2

### WooCommerce version

6.2.0

### WordPress version

5.8.3

### PHP version

7.4.16

### What went wrong?

When a client sets the products weight unit default on LBS. The MyParcel conversion to grams is not correct. E.g: The weight of 900 lbs is converted to 1985 grams.

### Reproduction steps

1. WooCommerce > Settings> Products > Weight unit > set to LBS
2. Set a product weight extreme example of a 900 lbs 
3. create an order and see the "wrong" converted weight (in admin)

**Comment by RichardPerdaan** [comment]
Solved in [4.10.1](https://github.com/myparcelnl/woocommerce/releases/tag/v4.10.1)
