### ISSUE TITLE
Faulty export to myparcel backend with housenumber suffix

### ISSUE THREAD

**Issue by Amelandbor** [myparcelnl/woocommerce#807]
### Plugin version

 4.9.2

### WooCommerce version

6.2.1

### WordPress version

5.9.1

### PHP version

7.4.28

### What went wrong?

When there is a housenumber suffix, the address isn't recognized in the backend of myparcel. The label created in the backend has the street name with the original housenumber at the end and the suffix is used in the housenumber field.

### Reproduction steps

1. Fill in a housenumber suffix when ordering
2. Export order to myparcel
3. See "check address" notification in backend myparcel

**Comment by RichardPerdaan** [comment]
fixed in version [v4.13.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.13.0)
