### ISSUE TITLE
Label description to long - must be at most 45 characters long

### ISSUE THREAD

**Issue by jojoba007** [myparcelnl/woocommerce#823]
### Plugin version

4.10.2

### WooCommerce version

6.2.2

### WordPress version

5.9.3

### PHP version

7.4

### What went wrong?

Issues with the character length for Woocommerce orders. As soons as we click to send the order over from WooCommerce to MyParcel we get this error. See screenshot: https://prnt.sc/ueQWNfB2tYQ0

Error:

"0 - data.shipments[0].options.label_description Must be at most 45 characters long - Unknown error:
{\"code\":0,\"fields\":[\"data.shipments[0].options.label_description\"],\"human\":
[\"data.shipments[0].options.label_description Must be at most 45 characters long\"]}. Please contact MyParcel."

Our WooCommerce orders are integrated to the popular WooCommerce Memberships extension, not sure if this has anything to do with it: https://woocommerce.com/products/woocommerce-memberships/

### Reproduction steps

As soons as we click to send the order over from WooCommerce to MyParcel we get this error. See screenshot: https://prnt.sc/ueQWNfB2tYQ0

### Relevant log output

```shell
"0 - data.shipments[0].options.label_description Must be at most 45 characters long - Unknown error:
{\"code\":0,\"fields\":[\"data.shipments[0].options.label_description\"],\"human\":
[\"data.shipments[0].options.label_description Must be at most 45 characters long\"]}. Please contact MyParcel."
```

### Additional context

https://prnt.sc/ueQWNfB2tYQ0

**Comment by RichardPerdaan** [comment]
Dear @jojoba007 , 
Thank you for posting your message. 
We started working on this issue and we have solved the problem in the latest version of the MyParcel WooCommerce plugin ([v4.11.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.11.0)).
