### ISSUE TITLE
Orders are not exporting + Fatal Error

### ISSUE THREAD

**Issue by FJVVCD** [myparcelnl/woocommerce#843]
### Plugin version

4.12.2

### WooCommerce version

6.6.0

### WordPress version

6.0

### PHP version

7.4.27

### What went wrong?

Orders are not exporting automatically anymore after the update to 4.12.2.
I uninstalled and installed the plugin, then i tried to make an order and set it on processing, so it exports.
Then i got:
![image](https://user-images.githubusercontent.com/107932442/174805694-4b312783-d527-40c3-a4a3-4f01aedb3f33.png)

### Reproduction steps

1. Navigate to ...
2. Click on ...
3. See ...

**Comment by RichardPerdaan** [comment]
fixed in version [v4.13.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.13.0)
