### ISSUE TITLE
Age check prevents creating non-domestic shipping labels 

### ISSUE THREAD

**Issue by bbrassem** [myparcelnl/woocommerce#853]
### Plugin version

4.12.2

### WooCommerce version

6.6.1

### WordPress version

5.8.3

### PHP version

7.4.16

### What went wrong?

When trying to create a shipping label for a non-domestic country (so EU and ROW shipments) you cannot export the order to MyParcel if the order contains products that have age-check enabled. This is inconvenient, you would expect the plugin to ignore the age check setting when shipping abroad.

Uploading screencast age check.mp4…

### Reproduction steps

1. Navigate to 'Products' and edit a random one
2. Go to shipping methods and enable 'age check'
3. Create a test order containing the product that has age check enabled, the country of destination can be any EU or ROW country
4. Once the order has been submitted, try creating a shipping label for said order in WooCommerce
5. You will see that the age check setting results in an error saying "The age check is not possible with an EU shipment or world shipment"

<img width="1753" alt="Schermafbeelding 2022-07-01 om 11 41 35" src="https://user-images.githubusercontent.com/100422476/176869898-b145c52c-d096-4288-b377-1064956bfb19.png">

**Comment by RichardPerdaan** [comment]
fixed in version [v4.13.0](https://github.com/myparcelnl/woocommerce/releases/tag/v4.13.0)
