### ISSUE TITLE
Barcode status "export_hint_no_label_created_yet" in order overview

### ISSUE THREAD

**Issue by DarkAllMan** [myparcelnl/woocommerce#875]
### Plugin version

4.13.2

### WooCommerce version

6.8.2

### WordPress version

6.0.2

### PHP version

8.0.22

### What went wrong?

When no export has been done, the Barcode status is now: export_hint_no_label_created_yet instead of a nice translation.

### Reproduction steps

1. Navigate to Woocommerce orders

### Additional context

![image](https://user-images.githubusercontent.com/1582343/188386956-4c30f2d0-5020-47fb-8ed4-d84b46c5f4cc.png)

**Comment by RichardPerdaan** [comment]
Solved in version [4.13.3](https://github.com/myparcelnl/woocommerce/releases/tag/v4.13.3)

**Comment by DarkAllMan** [comment]
Confirmed
