### ISSUE TITLE
Send type "Brievenbuspakket" changed to "Postvak"

### ISSUE THREAD

**Issue by DarkAllMan** [myparcelnl/woocommerce#876]
### Plugin version

4.13.2

### WooCommerce version

6.8.2

### WordPress version

6.0.2

### PHP version

8.0.22

### What went wrong?

Since the last update, Brievenbuspakket is renamed to Postvak. This makes no sense to me. This translation is no good for us. It makes things not clear. Can you please change it back?

### Reproduction steps

Go to order overview and check myparcel settings of an order.

### Additional context

![image](https://user-images.githubusercontent.com/1582343/188429243-cce97944-9d02-452b-8378-2a6b6b8b13ac.png)

**Comment by RichardPerdaan** [comment]
Solved in version [4.13.3](https://github.com/myparcelnl/woocommerce/releases/tag/v4.13.3)

**Comment by DarkAllMan** [comment]
Confirmed
