### ISSUE TITLE
Is MyParcel plugin ready for High-Performance Order Storage

### ISSUE THREAD

**Issue by Martje65** [myparcelnl/woocommerce#905]
### Plugin/theme name

Woocommerce HPOS

### Pricing

Free

### What problem does this feature solve?

Is MyParcel ready or considering update the plugin to make it compatible with the new option of WooCommerce “High-Performance Order Storage”

### What should the solution look like?

See:
<a href="https://developer.woocommerce.com/2022/09/29/high-performance-order-storage-backward-compatibility-and-synchronization/">High-Performance Order Storage: Backward Compatibility and Synchronization</a>

<a href="https://developer.woocommerce.com/2022/09/14/high-performance-order-storage-progress-report/">High-Performance Order Storage: progress report</a>

<a href="https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#declaring-extension-incompatibility">Github: What is High-Performance Order Storage (HPOS)?</a>

**Comment by EdieLemoine** [comment]
Hi @Martje65, HPOS is fully supported in the beta version of our plugin. You can wait a few more weeks until we release it on the main branch, or download and try it in advance from [the releases page](https://github.com/myparcelnl/woocommerce/releases). 

We've completely rewritten the plugin, vastly improving performance (8x faster), making the plugin easier to use, adding features and fixing any stale bugs the 4.x plugin has. We would love to hear any feedback you have if you decide to try it.

We also have an [accompanying newsletter](https://myparcelnl.activehosted.com/index.php?action=social&chash=07871915a8107172b3b5dc15a6574ad3.1012&nosocial=1) with more information.
