### ISSUE TITLE
 Apple Pay Validation Error

### ISSUE THREAD

**Issue by DFfar** [myparcelnl/woocommerce#911]
### Plugin version

4.14.0

### WooCommerce version

7.1.0

### WordPress version

6.1.1

### PHP version

7.4

### What went wrong?

I get this error message in Admin;
Apple Pay Validation Error Check [Apple Server requirements page](https://developer.apple.com/documentation/apple_pay_on_the_web/setting_up_your_server) to fix it in order to make the Apple Pay button work

### Reproduction steps

1. Navigate to Admin
Waring bar appears in the top

**Comment by RichardPerdaan** [comment]
Hi @DFfar ,

The current MyParcel plugin does nothing with the Apple Pay Validation. 
Are there any indications that this problem is caused by our plugin?
