### ISSUE TITLE
Geheugen gebruik Myparcel plugin v4.15.1

### ISSUE THREAD

**Issue by Martje65** [myparcelnl/woocommerce#928]
### Plugin version

4.15.1

### WooCommerce version

7.1.1

### WordPress version

6.1.1

### PHP version

7.4

### What went wrong?

Myparcel plugin v4.15.1 gebruikt 20MB meer geheugen gebruikt dan v4.14.0

Hier het geheugen gebruik met v4.14.0
![38MB](https://user-images.githubusercontent.com/112067446/207428209-a42ae4c6-ec3e-4519-95c1-94fd3a158873.png)

En hier het geheugen gebruik met v4.15.1
![58MB](https://user-images.githubusercontent.com/112067446/207428260-e898292f-670c-49b4-a8fb-ee723bc9be27.png)

Alle instellingen zijn het zelfde voor v4.14.0 als voor v4.15.1

### Reproduction steps

1. installeer MyParcel plugin v4.14.0
2. update naar MyParcel plugin v4.15.1
3. vergelijk het geheugen gebruik van beide plugins.

**Comment by wthijmen** [comment]
Hi @Martje65,

Ik heb dit even uitgezocht en het komt doordat wij sinds die versie de PDK in de plugin hebben verwerkt. 
Hier lees je meer over de PDK (https://github.com/myparcelnl/pdk)
