### ISSUE TITLE
Small css bug/typo

### ISSUE THREAD

**Issue by webwit** [myparcelnl/woocommerce#950]
### Plugin version

4.16.4

### WooCommerce version

7.3.0

### WordPress version

6.1.1

### PHP version

8.1

### What went wrong?

Hi, in woocommerce-myparcel/includes/admin/class-wcmypa-admin.php in function generateEmailConfirmation() it has this line:

`$htmlHeader .= "<table cellspacing='0' style='border: 1px solid #e5e5e5; margin-bottom: 20px;>";`

The inline style is missing a closing single quote, resulting in my browser ignoring the margin-bottom. So it should be this:

`$htmlHeader .= "<table cellspacing='0' style='border: 1px solid #e5e5e5; margin-bottom: 20px;'>";`

### Reproduction steps

See above.

**Comment by webwit** [comment]
Lol I can't believe you didn't fix it in the latest version I just installed. It takes 5 seconds to fix.

**Comment by webwit** [comment]
Still open.

**Comment by EdieLemoine** [comment]
Hi @webwit, thanks for your suggestion and detailed explanation. It's solved in pr #954.

Next time, you can try opening a pull request yourself, we generally process those a lot faster.
