### ISSUE TITLE
Fatal error in API request handler

### ISSUE THREAD

**Issue by Spreeuw** [myparcelnl/woocommerce#96]
The API request handler (class-wcmp-rest.php) doesn't handle WP_Errors, which results in fatal errors when the MyParcel server cannot be reached (or when there are other errors during the request)
```
PHP Fatal error:  Cannot use object of type WP_Error as array in /wp-content/plugins/woocommerce-myparcel/includes/class-wcmp-rest.php on line 139"
```

**Comment by RichardPerdaan** [comment]
Fixed in version 3.1.8 of the MyParcel plugin
