### ISSUE TITLE
Javascript breaking issue: Cannot change weight in back-end

### ISSUE THREAD

**Issue by DarkAllMan** [myparcelnl/woocommerce#975]
### Plugin version

4.19.1

### WooCommerce version

7.6.0

### WordPress version

6.2.0

### PHP version

8.0.28

### What went wrong?

https://wordpress.org/support/topic/kan-gewicht-niet-meer-aanpassen-door-javascript-issues/

When I open order overview I get several javascript console errors. When I open myparcel options for an order I get more and I cannot save changes for packages:

![image](https://user-images.githubusercontent.com/1582343/232705324-33404e85-ef29-4de0-a21e-b7e6c4fa7244.png)

### Reproduction steps

1. wp-admin/edit.php?post_type=shop_order
2. Click on MyParcel options in order
3. See console

### Additional context

Maybe related:
https://github.com/woocommerce/woocommerce/issues/37782

Staging site available!

**Comment by Mark-Ernst** [comment]
Hey @DarkAllMan,

I tried to reproduce your problem on our own test server and I'm not getting any errors. Nevertheless, we want to help you out. You pointed out that you have a staging site available. Can you please contact us at support@myparcel.nl and mention that you interacted with me (Mark) on GitHub.
