### ISSUE TITLE
Empty Street name and number woocommerce orders

### ISSUE THREAD

**Issue by leroynijstad** [myparcelnl/woocommerce#98]
when selecting a customer within woocommerce orders and pressing load billing address or load shipping address. The Street name and number are not filled in while the customer does have these in his account.

**Comment by RichardPerdaan** [comment]
Hi @leroynijstad,

Thank you for sending your message. 
You may have installed the plugin later than the orders you have received. 
If there are orders today where the input fields are not filled in, I would like to hear from you.

**Comment by leroynijstad** [comment]
The problem occurs when making a new order in the back end of the website. So this is not the case. 
So i go to create new order -> select a client from the dropdown -> press load in billing address; 
Everything loads expect the street name and number.

I even checked this by creating a new user in the shop, entering all user data + street name / number.
Then creating a new order -> selecting the client from the dropdown -> press load in billing address;
Still not loading the street name and number

**Comment by soft79** [comment]
Ik heb het vooralsnog met deze snippet in mijn child theme's functions.php opgelost:

```
add_filter( 'woocommerce_ajax_get_customer_details', function( $data ) {
    foreach( $data['meta_data'] as $meta) {
        switch($meta->key) {
            case 'billing_house_number':
                $data['billing']['house_number'] = $meta->value;
                continue;
            case 'billing_house_number_suffix':
                $data['billing']['house_number_suffix'] = $meta->value;
                continue;
            case 'billing_street_name':
                $data['billing']['street_name'] = $meta->value;
                continue;
            case 'shipping_house_number':
                $data['shipping']['house_number'] = $meta->value;
                continue;
            case 'shipping_house_number_suffix':
                $data['shipping']['house_number_suffix'] = $meta->value;
                continue;
            case 'shipping_street_name':
                $data['shipping']['street_name'] = $meta->value;
                continue;
        }
    }
    return $data;
}, 10, 1 );
```
